### ISSUE TITLE
Media Library Panel UI Fixes

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1199]
## Bug Description

The library panel does not match the [designs in Figma ](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2731%3A1757)

## Expected Behaviour

2. Duration Placement on Videos is not correct
3. Spacing / Padding of Panel is off

See #354 and #1319 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
I believe only the duration placement is left to fix (needs to be moved just a bit slightly to the left).

**Comment by diegovar** [comment]
@samitron7 Should we hold off on this work if the UI will change to the new designs?

**Comment by samitron7** [comment]
@diegovar Let's go ahead fix because the duration label won't change too much in the new design

1. Font changes
<img width="233" alt="Screen Shot 2020-07-28 at 8 11 41 AM" src="https://user-images.githubusercontent.com/10889431/88684962-480c3a00-d0aa-11ea-932a-f263e023c694.png">

2. Bottom left align the duration label (8px padding from left and bottom). Please remove the play button. We don't need that as it's redundant information that you're looking at a video
![Media Panel](https://user-images.githubusercontent.com/10889431/88685083-70943400-d0aa-11ea-9a21-e54d6b56f996.png)
