### ISSUE TITLE
Restrict User Access to only those with ability to upload media and publish

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1372]
## Feature Description

Display clear messaging when users lack permission to upload media or publish stories.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. If as user does not have capabilities to upload media, display a [dialog](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9631%3A10) saying "You don't have access to upload media. Check with your administrator to request access."
2. If as user does not have capabilities to publish a story, disable "Publish" button.  
    1. When you hover over the publish button, display a tooltip with message "You don't have access to publish a story. Check with your administrator to request access."

**Comment by spacedmonkey** [comment]
@o-fernandez Some fixes have been applied to how capabilities are handled in the editor. So now, the editor fails gratefully when the user do not have the correct permissions. So I am not sure this ticket is a p0 anymore.

**Comment by o-fernandez** [comment]
@spacedmonkey can you share screenshots/recording of the new handling for permissions-related failures? That would be helpful context for reviewing the priority.

**Comment by spacedmonkey** [comment]
@o-fernandez This is a screen recording of a contributor using the editor. 
https://youtu.be/PPBVQUChfbU

As you can see, a snackbar now shows when a user can not upload media or tries to save the story. But the editor is usable. 

The only thing I may change I would disable the publish button..

**Comment by samitron7** [comment]
@spacedmonkey Just seeing this but for this use case I think we may need to use the dialog box with the following message and button (apologize if I said snackbar earlier)

Message:  You don't access rights to upload images. Please check with your administrator to grant you upload access rights
Button: OK, got it

**Comment by spacedmonkey** [comment]
@samitron7 Reviewing other file upload errors, these are all snackbar messages? Is there a reason why this one is different from the others? Should all other file upload error be changed to dialog now?

Example from file upload.

![Screenshot 2020-05-25 at 17 09 26](https://user-images.githubusercontent.com/237508/82829264-c54ce000-9eaa-11ea-9fb5-1b8bedfc35d1.png)

**Comment by swissspidy** [comment]
@samitron7 would you be able to provide feedback here?

**Comment by samitron7** [comment]
First off - super sorry I missed this. Slack is the best place to catch me.

@spacedmonkey Can you provide me a screenshot of the other messages so I know what you mean when you say "Is there a reason why this one is different from the others?" And no, all the upload error message should remain as snackbars.

This particular one use case requires special attention from the user since they won't be able to upload or publish. It's not sufficient enough to just tell them that they are unable to upload files. We need to be specific here and give them a path to resolve the issue if possible. I think we already have the dialog component implemented on the editor. @swissspidy Can an adminstrator grant a person permission to upload and publish - sorry I'm not familiar with all the WP permission. the message in the dialog box will depend on what you say.

I added a flow [here](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=9631%3A10) for the dialog box. @o-fernandez I see that there is a related ticket to disable features when user roles does not have permission (which we had a thread on) that is ready for QA. That ticket pretty much covers the error message. I think the dialog box is clear but if we don't want to make that change now, we should at least change the message in the snackbar to read:

You don't have access to upload images. Check with your administrator to request access.

When you hover over the publish button, display a tooltip with message "You don't have access to publish. Check with your administrator to request access."

**Comment by swissspidy** [comment]
> Can an administrator grant a person permission to upload and publish - sorry I'm not familiar with all the WP permission. the message in the dialog box will depend on what you say.

Sure, yeah, an admin can change another user's role so they get those permissions.

Edit: In theory, one can also have permissions to _upload_ but **not** to _publish_

**Comment by swissspidy** [comment]
> When you hover over the publish button, display a tooltip with message "You don't have access to publish. Check with your administrator to request access."

That's a very very long tooltip 🤔 

We need to make sure we communicate this right also to users with screen readers

**Comment by swissspidy** [comment]
Updated the ACs accordingly.

**Comment by swissspidy** [comment]
Moving out of beta because this now is just about changing the way the error message is presented.

**Comment by spacedmonkey** [comment]
@swissspidy I think we should close this. I think this is ticket is valid / make sense anymore.

**Comment by swissspidy** [comment]
@spacedmonkey Shall I create a new issue about updating the error message then?

**Comment by o-fernandez** [comment]
I've created a new issue since this is good to go for Beta. 

https://github.com/google/web-stories-wp/issues/2464

This one can be closed.

**Comment by swissspidy** [comment]
@o-fernandez Also needs one for implementing a dialog when they don't have upload permissions

**Comment by swissspidy** [comment]
Created #2481 now.

So the two follow-up issues are:

* #2464
* #2481
