### ISSUE TITLE
Rotation angle issues (negative values, rotation beyond 360 degrees, etc.)

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#1407]
## Bug Description

There are two issues we should address re: rotation angle values in the design panel. 

1. Rotation beyond 360 degrees
2. Negative rotation values

## Expected Behaviour

- As the user rotates an element clockwise, the value should cap at 360 degrees. 
- If the user rotates counterclockwise, the value should decrease from 360, not from zero and into negative values. 
- Design panel should just not accept values above 359 degrees, if a user tries to enter a value above 359 show some error/UI indicator that says rotation needs to be between 0-359 degrees.

## Steps to Reproduce

1. Add object to page (e.g., shape)
2. Rotate object

While rotating keep an eye on the rotate value in the design panel. 

## Screenshots

Attached video (zipped due to git file format limitations)
[Rotation value issues.zip](https://github.com/google/web-stories-wp/files/4558589/Rotation.value.issues.zip)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
If user rotates counterclockwise, a negative value is recorded in the field (i.e. if they rotate counterclockwise to -90 degrees - should this instead record as the equivalent 270 degrees?)

**Comment by dvoytenko** [comment]
I agree. The rotation angle should always be in 0-360 range.

**Comment by cvolzke4** [comment]
> If user rotates counterclockwise, a negative value is recorded in the field (i.e. if they rotate counterclockwise to -90 degrees - should this instead record as the equivalent 270 degrees?)

Yes, -90 degrees should be recorded as 270 degrees. I think this is what's happening? This is how I've been testing this (and likewise for multi-selection):
https://share.getcloudapp.com/12uydxvx

What steps can I take to see a negative rotation value?

**Comment by o-fernandez** [comment]
@csossi can you retest? Please attach a screenshot/video if you see odd behavior.

**Comment by barklund** [comment]
What's the status here? Is @csossi testing or?

**Comment by barklund** [comment]
Ping @kmyram, not sure what's the deal here.

**Comment by o-fernandez** [comment]
Moved it to "ready for QA" so it shows up on @csossi pipeline

**Comment by csossi** [comment]
Thanks for moving this over, @o-fernandez 

Verified in QA - tested in Master as this was merged

NOTE: Under Expected Behaviour above, it's noted "Design panel should just not accept values above 359 degrees, if a user tries to enter a value above 359 show some error/UI indicator that says rotation needs to be between 0-359 degrees."

Currently, NO error or UI indicator exists if a user enters a value greater than 360. What happens is that the value is converted to its equivalent - i.e. if a user enters 450, then the editor sets at the equivalent 90 degrees. I think this is fine, but if it isn't let me know

**Comment by o-fernandez** [comment]
Thanks for flagging, Claudio. At this point, I think it's fine. I'll file a separate enhancement/bug in the future if it becomes an issue. 

> Thanks for moving this over, @o-fernandez
> 
> Verified in QA - tested in Master as this was merged
> 
> NOTE: Under Expected Behaviour above, it's noted "Design panel should just not accept values above 359 degrees, if a user tries to enter a value above 359 show some error/UI indicator that says rotation needs to be between 0-359 degrees."
> 
> Currently, NO error or UI indicator exists if a user enters a value greater than 360. What happens is that the value is converted to its equivalent - i.e. if a user enters 450, then the editor sets at the equivalent 90 degrees. I think this is fine, but if it isn't let me know

That's OK for now, let's leave as it is and we can file a separate enhancement / bug fix request if its confusing to users.

**Comment by samitron7** [comment]
@merapi @o-fernandez We don't need to file an enhancement for the following because an error UI is not needed. It's a pattern that is common in a lot of tools now and is considered 'smart'. 

"Currently, NO error or UI indicator exists if a user enters a value greater than 360. What happens is that the value is converted to its equivalent - i.e. if a user enters 450, then the editor sets at the equivalent 90 degrees. I think this is fine, but if it isn't let me know"
