### ISSUE TITLE
Groundwork to Filter Explore Templates View

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#1510]
## Description
This is the foundation for adding in various filters to the explore templates view. All filters are based on metadata for now and filtering will occur client side. Having it centralized is a) good practice and b) sets us up for potentially having the templates as their own api and the query updating to filter. 

## Acceptance criteria 
- Set the groundwork in packages/dashboard/templates to filter the templates based on different metadata or strings. 
-  Tests to verify the above actions (no user facing changes)

**Comment by BrittanyIRL** [comment]
@littlemilkstudio since we're pivoting here midsprint lets use this ticket to document the discovery that you've done. Once you've added that you can just move this issue to done.

**Comment by maxyinger** [comment]
coolio.

Basically rn we have:
  - 59 templates
  - around 180 unique colors
  - around 160 unique tags
  - 14 unique verticals

Challenge with colors and tags is displaying an input that's digestible to users with that many options is tough. Especially colors which would be technically challenging to sort into visual expectations.

I looked into sorting/grouping/finding similar colors. here's a couple resources:
https://tomekdev.com/posts/sorting-colors-in-js
https://www.npmjs.com/package/color-diff

Discovered something nice about color labels while implementing the search. most (if not all) color labels contain the parent color in the name. this makes colors a lot easier to map to a primitive color because it's easy to compute that the name "electric blue" belongs to the "blue" family.

anyway, current recommendations if we want to implement further filters past the search:
  - select component with primitive colors as options. (I think should only be like 8 or so colors here), and use labels to map something like "electric blue" to "blue"
  - possibly the datalist component for tags. might be nice to implement something like the freeform taxonomy input later here to combine tags, but might be too robust

Lastly I think it's important to keep in mind the level of filtering we need relative to the amount of templates we have. Currently in the editor page layouts we have 7 filters for 294 page layouts and that works well. I think if we ever have the level of granularity that combining two filters commonly results in only 0 to 1 results, the searching is too robust for the amount of templates we have.
