### ISSUE TITLE
Template Internationalization

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1722]
## Feature Description

We need to figure out how to best localize templates once we have more templates and the editor is used globally.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #7196

**Comment by BrittanyIRL** [comment]
I'm unclear how we're supposed to internationalize templates since they are designed in a given language and translating them would alter the design. 🤔  

Eventually, when templates are external and we have templates written in other languages or contributed in other languages it would make sense to maybe prioritize those ones in the explore templates on the dashboard based on language settings if possible - but none of this would be actually translating the templates which is how i am reading this issue. 

I know this is an old one but it's been in our backlog for quite some time and I just wanted to bring it up. I remember a text sets internationalization issue getting discussed a while ago and we scrapped that for the same reasons as above.

**Comment by swissspidy** [comment]
Yeah because of questions like that this is still a P4 and basically on ice for now.

This will become more relevant once we have a more sophisticated template library where users could potentially provide their own templates etc.

Might as well just close this for now though :-)
