### ISSUE TITLE
Story Not Auto-Advancing When Video Set To Loop

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#1795]
## Bug Description

Story is not auto-advancing to the next frame if it contains a video set to "Loop"

## Expected Behaviour

If set to auto-advance, story should advance based on user defined setting regardless of "loop"

## Steps to Reproduce

- create a story (2+ pages)
- set page advance to "auto" for the Document
- add a video to a page
- set video to "Loop" in design panel
- preview page

Note that page doesn't auto-advance past the page with the "loop" video

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
That sounds like a bug in the AMP story viewer.

We set `auto-advance-after` to the video element's ID. But because of the loop it just keeps beginning from the start.

@wassgha @dvoytenko Perhaps one of you could confirm whether this is an (already known) upstream bug?

If it's intended behavior we could prevent setting `auto-advance-after` for looping videos.

**Comment by swissspidy** [comment]
Only found https://github.com/ampproject/amphtml/issues/22174 so far.

> Videos should either be used for `auto-advance`, or loop. If they're not the video used in the page's `auto-advance` attribute, we should enforce the fact that they loop.

Sounds like we should enforce that in our editor; or at least prevent setting `auto-advance` for looping videos.

**Comment by swissspidy** [comment]
Paul confirmed on Slack that only non-looping videos should be considered here.

**Comment by csossi** [comment]
Verified in QA

Merged into master as part of #1992
