### ISSUE TITLE
Clicking a title on the dashboard story grid should do something.

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#1867]
## Feature Description

Clicking a title or the preview card on the dashboard story grid should do something. This was raised in the demo and will require UX to define what the something is.

**Comment by jauyong** [comment]
Sam is currently updating this

**Comment by o-fernandez** [comment]
I talked to Sam and we discussed the following for now, let's go with this since Sam's bandwidth is limited: 

- The default when clicking on a story (in either grid or list view) should be to open the story in the editor.
- Exception would be parts that have other specific actions. For example, if you click on 3-dot menu or on preview button/area then those should trigger their respective action. 
- In the list view, not sure if this is spec'd, but it'd be great to also have the 3-dot menu show up on hover and let the user access the actions in there. If not spec'd, we can ignore for now.

**Comment by BrittanyIRL** [comment]
Thanks for this Omar! 

I am going to separate the ask for the list view into its own ticket to avoid scope increase and i'll follow up with questions/demos.

**Comment by BrittanyIRL** [comment]
Ticket for the list view ask: https://github.com/google/web-stories-wp/issues/2124

**Comment by BrittanyIRL** [comment]
For testing: this is the PR https://github.com/google/web-stories-wp/pull/2138

**Comment by csossi** [comment]
Verified in QA

(image is underline on mouseover - click led to Editor)
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/caeaa9e5-ff1a-4958-a9b2-40a8307d62e3)
