### ISSUE TITLE
Templates - Add Animations

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#1893]
This ticket was set with an intentionally high estimate because it needs to be broken up more.

The goal of this ticket is to add all animations to the templates. This includes going through each template page and:
- Creating a ticket for the template animations
- Applying animations in the animation editor `/story-anim-tool`
- Altering it's static layout if needed to accommodate the animation
- If template requires a new animation part that doesn't already exist
  - Create ticket for missing animation part
  - Add animation part
  - Add animation part controls to editor

We have 8 templates right now with around 8-9 pages that need to be animated per template. More likely than not each template will require several PRs to incapsulate all the animation requirements and be manageable sizes to review.

**Comment by jauyong** [comment]
This ticket may be broken down into smaller tickets

**Comment by mariano-formidable** [comment]
Closing this issue because we've broken it down into 8 tickets (1 for each template):
- [DIY](https://github.com/google/web-stories-wp/issues/2206)
- [COOKING](https://github.com/google/web-stories-wp/issues/2207)
- [FITNESS](https://github.com/google/web-stories-wp/issues/2208)
- [ENTERTAINMENT](https://github.com/google/web-stories-wp/issues/2209)
- [TRAVEL](https://github.com/google/web-stories-wp/issues/2210)
- [BEAUTY](https://github.com/google/web-stories-wp/issues/2211)
- [WELLBEING](https://github.com/google/web-stories-wp/issues/2212)
- [FASHION](https://github.com/google/web-stories-wp/issues/2213)
