### ISSUE TITLE
Clarify the callback reuse for `useContextSelector`

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#1938]
I'm setting this bug to P0, but feel free to lower if this doesn't cause any serious issues.

The question is with what deps should go to `useCallback` in the [assets/src/edit-story/utils/context.js](https://github.com/google/web-stories-wp/pull/1589/files#r428831688).

IMHO the selector/equalityfn should be always reenterable and immutable. The fact that it's very convenient to inline this function should not change the architecture significantly, IMHO. I think we'll be better of to pick the first version of each function and use them for the lifecycle of a component that uses the hook. Otherwise, we are regenerating the `useCallback` each time and thus the `useCallback` is not even really used.

**Comment by barklund** [comment]
This should probably be fixed by ref'ing the two arguments so the callback is stable:

```js
export const useContextSelector = (
  context,
  selector,
  equalityFn = shallowEqual
) => {
  const ref = useRef();
  const selectorRef = useRef(selector);
  const equalityFnRef = useRef(equalityFn);

  useEffect(
    () => selectorRef.current = selector,
    [selector]
  );
  useEffect(
    () => equalityFnRef.current = equalityFn,
    [equalityFn]
  );

  const equalityFnCallback = useCallback(
    (state) => {
      const selected = selectorRef.current(state);
      if (equalityFnRef.current(ref.current, selected)) {
        return ref.current;
      }
      ref.current = selected;
      return selected;
    },
    []
  );

  // Update the selector fn to memoize the selected value by [equalityFn].
  const patchedSelector = equalityFn ? equalityFnCallback : selector;
  return useContextSelectorOrig(context, patchedSelector);
};
```

**Comment by dvoytenko** [comment]
@barklund this looks good, but one question. Do we need `useEffect` in this case? It'd just be enough to do:

```
const selectorRef = useRef();
...
selectorRef.current = selector;

const callback = useCallback(() => {
  ... selectorRef.current(...); ...
}, []);
```

**Comment by barklund** [comment]
> ```js
> const selectorRef = useRef();
> selectorRef.current = selector;
> ```

🤦 

Why did I never think of this? Of course this works! It does unnecessarily re-set the ref even if selector doesn't change, but I'm pretty sure that doesn't matter at all!

I've been doing that other thing way too often - probably just because it's necessary with a `useState` but of course not a ref... D'oh!

Or am I missing something? Hm... Not sure about anything anymore really.

**Comment by cvolzke4** [comment]
Actually useCallback isn't needed at all, since useContextSelector uses the selector without re-rendering when the fn changes:
https://github.com/dai-shi/use-context-selector/blob/master/src/index.js#L69

Creating the 'equalityFnCallback' lambda is cheap, as it only creates a temporary object to wrap equalityFn and selector.

I think 'selectorRef' shouldn't be used, as the selector _could_ technically change between calls to useContextSelector.

**Comment by dvoytenko** [comment]
@cvolzke4 yeah, i see your point. imho in that case let's remove `useCallback`?

**Comment by swissspidy** [comment]
@cvolzke4 why close with still a PR open?

**Comment by cvolzke4** [comment]
> @cvolzke4 why close with still a PR open?

I thought that I had merged the PR. The is merged now.
