### ISSUE TITLE
Media Zooming: Group actions in history and remove reset button

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#1945]
## Bug Description

Currently, when zooming Media, each zoom step is considered as a separate history entry.

## Expected Behaviour

Zooming should be considered as one history entry.

## Steps to Reproduce

1. Add Media
2. Go to edit mode and change the zoom setting for a few times from the slider.
3. Now exit the edit mode and use History Undo.
4. See all the Zoom steps being shown one by one as opposed to all together.

## Screenshots

![zooming](https://user-images.githubusercontent.com/3294597/82670221-00e27280-9c3d-11ea-9ab0-d3b3254bd43b.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@samitron7 & @o-fernandez , how do you feel about this proposal:

### All editing in image edit mode is only ever 1 history entry.
If you enter image edit mode, you can make as many edits on crop, zoom and positioning as you want. When you exit edit mode and press "undo" (by keyboard or button), all your edits will be undo'ed in a single action.

This makes image editing and undo synchronous with text editing, where all your edits, once you leave edit mode, happens in a single entry and can be undone by a single undo.

### In-edit history: only text, not image
Unlike text edit mode, we will not support in-edit history.

If you enter text edit mode, you can delete something and press undo (using keyboard only) while still in edit-mode. This will undo the deletion and you stay in edit-mode. This is due to draftjs (the underlying utility for rich text editing) having its own history management tool.

If you enter image edit mode, there will be no such support (currently). If you enter image editing, change the zoom and press undo (using keyboard), you will leave image editing and revert to the state before entering edit-mode.

We _can_ in the future support a local history state for while in image edit mode, but it's a pretty complex feature with minimal returns, so I recommend against it for now.

**Comment by o-fernandez** [comment]
@barklund that sounds like a great proposal. I'd move forward with it.

**Comment by samitron7** [comment]
+1 with moving forward and I'd say we actually don't need to store a history state in the future. The story page is not big so it's quite easy to redo or manually resize and reposition the image.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT. Zooming looks to be grouped into one history entry but there is a regression with cropping (filed ticket [5464](https://github.com/google/web-stories-wp/issues/5464))

FYI @barklund
