### ISSUE TITLE
Creators should not be able to change the height of the text box

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#1950]
## Feature Description

Creators should not be able to change the height of the text box

Behavior is incorrect. If we don’t allow you to drag to resize the height, we should also not allow you to manually input a H value. 
[Figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8315%3A0)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Creators should not be able to change the height by manipulating the H field of the textbox size in the design panel while the size aspect ratio is unlocked

## Screenshot 
![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/4b013dd8-4cad-44e5-9b80-09fcdd905174)

**Comment by jauyong** [comment]
@samitron7 @o-fernandez 
Since we can actually drag the corner, I specified in the AC that they shouldn't be able to manipulate the H IFF the aspect ratio of the textbox size is unlocked. What do you think?

**Comment by samitron7** [comment]
Here's the [figma flow](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=8315%3A0). When you select the text box, the height value is set to AUTO. Both height and the lock are grayed out so that the user can not adjust the value. If seeing the height value becomes an issue with users we can change AUTO to a numeric value but I notice that I rarely look at the input value as I work. (Side note and a feature request: add tooltip with H/W value on page as you scale/resize an element).

I removed the UX needed label.

**Comment by miina** [comment]
@samitron7 / @o-fernandez One specification:
in case of multi-selection (e.g. a shape and a text), should the logic be the same -- as for single selected text.

**Comment by o-fernandez** [comment]
> @samitron7 / @o-fernandez One specification:
> in case of multi-selection (e.g. a shape and a text), should the logic be the same -- as for single selected text.

If I select a shape and a text I don't think the line height should show at all, isn't that right? I thought that we hide the design panel items that don't apply to an element, and shapes don't have (I think) line height. Can you clarify/confirm?

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT
