### ISSUE TITLE
Text edit mode: background color same as white text

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#2040]
## Bug Description

When the background mode is "highlight", it displays white in edit mode.
When using white text, it's not visible in edit mode.

## Expected Behaviour

- The edit mode background should never match the used color.

## Steps to Reproduce

1. Add a Text element.
2. Assign white as the Text color
3. Assign Highlight as the background mode.
4. Now go to the edit mode.
5. See no visible text.

## Screenshots

![white-bg](https://user-images.githubusercontent.com/3294597/83039743-cc0c5c00-a03e-11ea-9b38-ce65d4f7a9ef.gif)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
From discussing with Sam + the conversation below:
- The edit mode should not have whiteout / special background, it should remain transparent as the display mode is.
- When in highlight mode, the highlight should be displayed in the edit mode as well even though it will not 100% match the display mode (see the comments below)
- Please tag Sam when the PR for that is ready so that she can check it in the QA environment and confirm.

**Comment by samitron7** [comment]
@barklund Can you create a 2 line text box (white text) with a green hilite bg and attach images for:
- just the styled textbox 
- click into textbox to write with the focus state in green
- click into textbox to write. this time, the entire box is text box green

Also remove the border radius.

**Comment by barklund** [comment]
Here are the screenshots:

| Display mode | Edit mode with text background | Edit mode with solid background |
| - | - | - |
| ![Screen Shot 2020-06-09 at 11 05 11 PM](https://user-images.githubusercontent.com/637548/84222532-ce8e9d00-aaa5-11ea-972e-b9b5532cc77c.png) | ![Screen Shot 2020-06-09 at 11 05 02 PM](https://user-images.githubusercontent.com/637548/84222528-cdf60680-aaa5-11ea-9f91-f5abbe84d008.png) | ![Screen Shot 2020-06-09 at 11 05 20 PM](https://user-images.githubusercontent.com/637548/84222533-ce8e9d00-aaa5-11ea-9ed1-802f9127aa73.png) |

As you can see, the height of the highlight in display mode follows the line-height, where in the edit mode it doesn't follow line-height, just regular character height. It's only a slight difference though.

Also I found out, that when we remove border radius, there's no need to keep `box-decoration-break` in the CSS at all anymore - which will greatly simplify a lot of the source code, as we don't need all those annoying elements. That'll reduce quite a bit of complexity and technical debt!

(ping @pbakaus)

**Comment by samitron7** [comment]
Thanks for getting us these screens @barklund . This helped quite a bit. I prefer the "Edit mode with text background" even if we loose all styling (ie line height padding) when we do into edit mode. I think the users will quickly learn there is a difference between edit mode and display mode once they click in and out of it a couple times.

And @pbakaus From a design perspective, border radius is not a good look for hi-lite text

So my final recommendation (and @o-fernandez is onboard):
1. Use  Edit mode with text background option
2. Remove border radius

Removing UX needed label

**Comment by pbakaus** [comment]
I think the line height and line wrap jumps are very jarring - more jarring than the switch from highlight to solid, so disagree. might make sense to prototype both. I also still don't understand why they can't be exactly the same - it's CSS on both ends? is the edit mode adding any styling we can't override?

Also disagree on the border radius. I also prefer highlight without radius (slightly), but border radius on highlight text is a popular look. It's so popular that in fact there's no way to *not* have border radius on Instagram. Just because we don't love it is imho not a great reason to get rid of it.

**Comment by samitron7** [comment]
@pbakaus - I'll let @barklund chime in why it's not possible to have the same but it's due to the library that we're using and it not supporting certain styles. Injecting it would mean we need to reflect the changes when the library changes @o-fernandez, you and Morten can decide on whether or not we custom build. Obviously on the UX side, we would like to have it be exactly the same but my discussion with Morten was based on what we can't technically do right now.

As for border radius, Paul/Omar and I had an offline conversation and let's remove for now mainly because border radius will become a feature in the future and it should not be forced as the default for hilite textbox.

**Comment by miina** [comment]
@samitron7 To confirm: Should the white background still stay as well? So it would be the white edit mode background + the text highlight background?

Or would it be just the text highlight without the white edit mode background?

**Comment by miina** [comment]
Updated the description based on discussion with Sam. Should be ready to be worked on now.

**Comment by samitron7** [comment]
@miina and I resolved this over chat but remove the white background:

"Would it be hard to remove that for all cases. Regardless of whether you have a bg fill/hilite, if you go into edit mode, the textbox container itself should just be transparent. The reason why I would like to do this is because the users can see the style (color, bg fill etc) over the bg image when they are typing without an additional white box"

**Comment by merapi** [comment]
We need some more work here because of the latest changes to the main branch (https://github.com/google/web-stories-wp/pull/2699 merged in the meantime).

The last case is broken:
https://drive.google.com/file/d/1vvTZ0cxXaOvfENAFmsCchEa5UhcN5WPQ/view?usp=sharing

**Comment by bmattb** [comment]
based on sprint planning review updated to 3pts to finish

**Comment by csossi** [comment]
Tested in 3184

Verified in QA

**Comment by samitron7** [comment]
@miina I thought we were able to hide the white background in the edit mode as discussed [here](https://github.com/google/web-stories-wp/issues/2040#issuecomment-649553993) between you and I?

**Comment by miina** [comment]
@samitron7 Correct, there is currently no white background in the edit mode:
![bg](https://user-images.githubusercontent.com/3294597/89866991-c68bd000-dbb0-11ea-92fa-5b1f1bf92184.gif)


Could you elaborate your comment a bit -- are you still seeing the white background when testing?

**Comment by merapi** [comment]
BTW, I just realized that when in FILL mode we should also display the BG in the edit mode.
Pushed a [fix](https://github.com/google/web-stories-wp/pull/3806).

**Comment by samitron7** [comment]
Verified in UAT
