### ISSUE TITLE
Increase requested stories in dashboard

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#2076]
## Feature Description

Currently only 10 stories are being requests when dashboard is requested. This means lots of waiting scrolling. The api allows for 100 items to be requested in a simple request. This should used to making scrolling smoother. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
the count per request was updated to 20 items this week. I'd opted for less than the max to prevent grabbing more data than we need at once. Am happy to adjust this further. 

@o-fernandez thoughts?

**Comment by BrittanyIRL** [comment]
^^ @o-fernandez friendly nudge on this just so we can keep the board clean.

**Comment by spacedmonkey** [comment]
For the record the max is 100. 20 is not much more than the existing 10. Why get the full amount? Or at least half, say 50?

**Comment by BrittanyIRL** [comment]
My only hesitation to set it to the max is you're really never going to be looking at 100 stories at once, so why not grab them as we need them to avoid excess data. Happy to split the difference. Mostly just think either way this ticket is easy to solve and it'd be nice to get it off the board!

**Comment by spacedmonkey** [comment]
We load 100 items in the media library and there is very little chance a user will see all of them. But you simple don't know what the user will see. For example, I have a monitor that is portrait and 20 is not enough. I think it is better to overload data and have a little more data than you need than give some users a bad experience. From a WordPress stand point, the response time should be that different at all.

**Comment by BrittanyIRL** [comment]
Ok, i will update to 100.

**Comment by o-fernandez** [comment]
Thanks for this update, but I think this may have been a disservice (as @BrittanyIRL feared) because the full page load time is now taking long... I'm on a fast network and here are the stats from a full page load of the dashboard for our dashboard.

161 requests
50.9 MB transferred
58.6 MB resources
**Finish: 5.44 s**
DOMContentLoaded: 625 ms
Load: 661 ms

With cache enabled it's a little better at 4.3 seconds, but it still feels laggy. 

There's probably opportunity to do code optimizations and refactoring to make this snappier and keep the 100 results, but I think we should start by reducing the number of results to see how the end to end looks and aim to get to a page load of p95 <3s (ideally <1s, but for this page I think aiming for <3s for now is fine). 

Brittany, I'm sorry for the back and forth, but is it possible for you to test what the end-to-end page load time (on an adequate network) is if you set this to 24 results or 60 results? 

I'm thinking we'd do one of those (24 or 60) so that way you get full rows of results for screens that display 2, 3, or 4 results across, so you don't get the odd last row that doesn't have incomplete results even if there are more stories.

**Comment by BrittanyIRL** [comment]
No worries! I'll do some testing and get back to you. Moving this back to in progress.

**Comment by BrittanyIRL** [comment]
@o-fernandez can you review the PR description from this update here and confirm that this update is ok for now? 

Ultimately, this is a bandaid for some perf issues with loading the data and time to first paint. 

https://github.com/google/web-stories-wp/pull/2789

**Comment by o-fernandez** [comment]
Looks good! Given your findings, it seems that 24 is a reasonable load.

**Comment by o-fernandez** [comment]
Tested in QA and this is way better, I'm at 1.89s. You can probs merge this and I'll do a UAT testing in master. :)

**Comment by BrittanyIRL** [comment]
Awesome, thanks for jumping on this so fast - glad to get this merged!
