### ISSUE TITLE
Add a snackbar notification to the bottom of the media library after upload

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2223]
## Feature Description

Add a snackbar/toast notification to the bottom of the media library to indicate that a media upload has commenced.

https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A303081

<img width=200 src=https://user-images.githubusercontent.com/45087979/83701783-1ba9e380-a64e-11ea-8159-e4bd4b239a5b.png>

Having a snackbar also means that the Video tab won't be activated when uploading a video while the Images tab is selected.

## Alternatives Considered

The file(s) being uploaded are added to the top of the media pane, with a progress indicator. So an alternative is to scroll to the top of the media pane so that the items (and their progress) are visible.

## Additional Context

This feature was discussed as a part of https://github.com/google/web-stories-wp/issues/1971.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
NOTE: I'm moving this to "ready for sprint" as it is spec'd out and feasible to be picked up, but it is not a high priority, thus labeling as P3.

**Comment by o-fernandez** [comment]
UX: would be good to draw the user's attention to the uploaded video while it's processing (e.g., go to the library/upload view in the left panel, and scroll to the top automatically, maybe even flash/highlight the in-progress video). I dragged a video to the canvas and then couldn't see the progress since I had my left panel on the 3P media tab.
