### ISSUE TITLE
Drag and dropping shapes results in a shape that is bigger than thumbnail being added

### ISSUE THREAD

**Issue by ezxyz** [GoogleForCreators/web-stories-wp#2237]
![drag anchor correct](https://user-images.githubusercontent.com/13947816/82792865-617ae500-9eb3-11ea-86f3-ef685d9eb86f.gif)

The thumbnail shape is smaller than the actual dropped shape. With images it is the exact same size. I'm not sure how the UX for this should work, so creating an issue to spec out the UX and then implement the solution.

**Comment by pbakaus** [comment]
This must have been broken recently. Was working perfectly before the aspect ratio changes.

**Comment by dvoytenko** [comment]
Hmm. Definitely doesn't look like aspect-ratio-change related.

**Comment by dvoytenko** [comment]
@pbakaus To be more specific, only blobs have a wrong aspect ratio. Everything else has the right one.

**Comment by pbakaus** [comment]
ooooh - yes, the blobs were always wrong, AFAIK. Need to be corrected. Maybe something for @wassgha

**Comment by samitron7** [comment]
@jhtin All elements inside the media panels are thumbnail views so when you drag it onto the page, the actual size will be different. Otherwise, everything will be too small including fonts. And when you say the images are the same size, that doesn't seem true to me?

@jauyong this is an enhancement but here are [rules](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7507%3A304080) for sizing when a user places an image to the stage

There is already a ticket for fix the wrong aspect ratio for blobs: https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/1896

I'm removing UX Needed for this

**Comment by o-fernandez** [comment]
Given Sam's review and there's no action here (the only issue was captured in #1896) I'm closing this issue.
