### ISSUE TITLE
Google Analytics (Site Kit)

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#225]
Automatic insertion of Google Analytics tracking code when Site Kit is installed

**Comment by miina** [comment]
Was looking into this and originally had the idea that perhaps we can add a HTML comment into the story content (e.g.`<!--WEB_STORIES_ANALYTICS-->`) which could then be replaced as needed in the server side, however, it doesn't seem to be possible to add a HTML comment like this via React.
It is possible to add a tag and then set it's content (`dangerouslySetInnerHTML`) as the comment, however, only specific tags are allowed as a children for `amp-story`, so can't really do that either. 

~~I'm now thinking that one way could be creating a new REST endpoint for analytics which would currently include the GA tag config data only, however, it would pass an array of configs for enabling adding other analytics information, too, in the future.~~

EDIT: see the next comment.

~~Thoughts? cc @spacedmonkey @dvoytenko~~

**Comment by miina** [comment]
Just remembered that the analytics code should be rendered dynamically anyway and not statically saved to the content, so using REST endpoint wouldn't work really since the output is static, will just add it on the server-side, without having to replace the tag in the saved content.

**Comment by dvoytenko** [comment]
Do we have an example of Google Analytics code that we need to insert?

**Comment by miina** [comment]
@dvoytenko #616 is currently using the logic that is used for AMP Plugin by Site Kit, however, would be good to specify it specific for Stories, who should be deciding the default configuration?

**Comment by miina** [comment]
@pbakaus Tagging you here as well for the default configuration (which is currently a replication of what SiteKit adds to AMP Plugin).

**Comment by pbakaus** [comment]
The default config is specified here: https://docs.google.com/document/d/1q8rkYYMKZh3R2eqkpwgGkx6QX0oSXoLYtIO6ml1BFD0/edit#heading=h.xqcejitqohdk

**Comment by dvoytenko** [comment]
Ok, so if I understand it right, we just need to replace the "YOUR_GOOGLE_ANALYTICS_ID" in the amp-analytics? If so, we have a few options:

1. Get the YOUR_GOOGLE_ANALYTICS_ID to the client side and generate the final JSON with it on the client side. This will produce a fully-valid AMP, but would require re-saving the story if the ID changes.
2. Build the full config client side, but use substitution marker within. E.g. `"gtag_id": "[YOUR_GOOGLE_ANALYTICS_ID]"`. Then we can replace this marker server-side. We could do it either during save/publish time or even serving time. Makes it easy to control server-side, but the analytics config is not truly valid.
3. Just output an empty `<amp-analytics>` tag and replace it whole on the server at save/publish or serve time. This will leave more options for controlling this server-side, especially if we decide to do it at the serving time. But we'll have to do bunch of tries for what an "empty" `<amp-analytics>` would work: completely empty or maybe with an empty `{}` config. Replacing such an HTML fragment will also be difficult, given unpredictably whitespaces.

I'd say we should start with either 1 or 2.

**Comment by miina** [comment]
@dvoytenko 
For 1: Note that this issue is specific to Site Kit meaning that we should track when the ID in Site Kit changes and then update all the stories when the analytics ID changes, not sure if that's the best option.

2. Note that it also needs to be filterable on the server-side, e.g. being able to remove the Site Kit analytics tag fully, so the second option also doesn't seem to be the best. Also, currently, the rest of the saving / server-side logic is based on the assumption that it's not necessarily WordPress, it would be better not to save any invalid content assuming that we're replacing it within WP.

For this specific Site Kit integration issue, the fully server-side approach in #616 still seems to make sense to me, it just needs updating the analytics output now, PTAL.

For the AMP Stories internal Google tag ID (non-Site Kit) global settings, we could consider option 1, however, if the GA is global through all the stories, this would mean that we'd need to re-save every single story when that changes, not sure if that's a good option either, considering that some stories might be from a previous version and have some differences? Also, triggering resave for all the stories seems potentially a bit much. This would be a good discussion under #570.

**Comment by dvoytenko** [comment]
@miina, to clarify then, what's your proposal for this?

**Comment by dvoytenko** [comment]
I guess also, another option, we could look for the `<amp-story ...>` and insert analytics tag right after it?

**Comment by miina** [comment]
@dvoytenko The proposal is in #616 which looks for `</amp-story>` tag and inserts `amp-analytics` tag if the configuration is OK and Site Kit plugin is enabled. The PR should be ready for review, perhaps that's easier to look at compared to describing it here in text :)

**Comment by dvoytenko** [comment]
oh. awesome!

**Comment by felixarntz** [comment]
Hey all, I just randomly found this Site Kit integration while browsing the plugin code. There's currently a lot of code duplicated there from Site Kit. Maybe that's intentional if you want to keep the story template completely locked for extensions (which may break AMP compatibility) - but if not, I think it would be a more elegant solution to introduce an action here, something like `web_story_analytics`. Site Kit could easily hook into that action.

Then all that would be left to the Web Stories plugin would be to in turn hook into Site Kit's `googlesitekit_gtag_amp_opt` filter to conditionally include all the story-specific events. This would overall reduce duplicate code in here and also decrease the chance for breakage from conflict, should the Site Kit plugin logic around rendering the snippet change.

cc @swissspidy

**Comment by miina** [comment]
@felixarntz Thanks for the note. Yes, it's currently purposefully duplicating some code, however, there's a `@todo` comment in the code to note that the logic should come directly from Site Kit. The action introduced for that is `web_stories_print_analytics`.

The GA current implementation is partial and will be continued in #570, however, it might be good to create a separate follow-up issue for addressing this specific (Site Kit + GA) improvement separately -- will add one.

**Comment by miina** [comment]
Added https://github.com/google/web-stories-wp/issues/1168
