### ISSUE TITLE
Paste upload 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#230]
As a user I want to be able to upload files by pasting them

[Feature Brief - Epic: Media Gallery](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#)

**Acceptance Criteria**
1. The user is able to paste anywhere on the screen, no matter the focus, ( e.g. via ⌘ + V )
2. Functionality behaves like #229

**QA**
1. Copy file (image) into clipboard from finder / explorer.
2. Open editor. 
3. Paste ( either via keyboard or context menu ) in editor.
4. Library should reload and show image.

**Comment by csossi** [comment]
Copied image from PC explorer.  Pasted (ctrl-v) in Editor but media didn't reload and image not copied

**Comment by spacedmonkey** [comment]
> Copied image from PC explorer. Pasted (ctrl-v) in Editor but media didn't reload and image not copied

Can you provide steps to replicate, browser version etc. @csossi

**Comment by spacedmonkey** [comment]
I have done some testing myself. As you can see from this [video](https://youtu.be/vUhPblPRp7M). However, to as there is no progress bar, it hard to see what is happening. Also it seems like paste events on handled unless the canvas is selected ( see [useCanvasSelectionCopyPaste.js](https://github.com/google/web-stories-wp/blob/c29f388b8135b9b20e061d036c01222f8fa10cbb/assets/src/edit-story/components/canvas/useCanvasSelectionCopyPaste.js) ). 

I think we need to handle paste events on the window and not just when the canvas is selected. However I think this is a different ticket as it covers what happens when pasting text, files and links and what should happen. CC @pbakaus @dvoytenko for visibility.

**Comment by pbakaus** [comment]
Yes. I consider this feature broken if paste doesn't work globally in the editor, and if a placeholder doesn't show up instantly.

**Comment by dvoytenko** [comment]
I think this is less about the progress bar (which I think we had another issue filed?), but more about creating a placeholder?

> Also it seems like paste events on handled unless the canvas is selected ( see useCanvasSelectionCopyPaste.js ).

It looks like the `useCanvasSelectionCopyPaste` ignores the paste if it doesn't understand it. So, it should be all good? But that code shouldn't involve media pastes - it's solely for element copy/paste operations.

> However I think this is a different ticket as it covers what happens when pasting text, files and links and what should happen. 

I think any non-resource/non-internal-element copy/paste (including links, text, and html) should be handled by another ticket. By any resource upload and insertion should be handled by this ticket.

**Comment by spacedmonkey** [comment]
Closing this ticket in favour of #519
