### ISSUE TITLE
Support category (de-)selection

### ISSUE THREAD

**Issue by winterDroid** [GoogleForCreators/web-stories-wp#2364]
Mainly UI work.

**Comment by winterDroid** [comment]
Probably easier after #2362 and #2363 is done.

**Comment by winterDroid** [comment]
@samitron7 what do you think about the following very simple approach for selection / deselection?

![ezgif-7-f84566ba67a7](https://user-images.githubusercontent.com/1552225/88505602-48a9bf80-d01b-11ea-87c9-f8b5692b6fa6.gif)

**Comment by winterDroid** [comment]
Implemented the simple approach. @samitron7 do you want me to add animations?

**Comment by samitron7** [comment]
@winterDroid We just went through a new visual pass and overhauled the entire design system. In order stay consistent with the pattern we set, I would like to keep the pills always visible and use the selected states to indicate what pill you've selected. I would like to keep all the pills visible because it took me several watching to video to understand that they were hidden. Also, we should make it easy to always open the full list. In the simple approach, you need to deselect in order to see the dropdown arrow.

I built a quick [prototype](https://drive.google.com/file/d/1yJoLx7BwOgYbk1lck4wiSczt5mDRXpXx/view?usp=sharing) with the new designs to illustrate the pill behavior

**Comment by diegovar** [comment]
@samitron7 

In that video, when you tapped the Technology pill, the inner container in the categories scrolled to show that row only and the rest of the rows faded away. Is that the approach we want to take? Asking because that's pretty complex to implement.

If in that situation (when you tapped the Technology pill and we scrolled to the 3rd row while collapsing the categories section) you tap the Technology pill again, should we a) expand the categories container to show all pills, b) scroll to the first row (which is the default when the container is collapsed with no selection) or c) something else?

**Comment by diegovar** [comment]
Hi @samitron7, can you clarify the behaviour question I raised in the previous comment? It's blocking us from wrapping up the work on categories.

Thank you!

**Comment by o-fernandez** [comment]
@samitron7 put this at the top of the UX needed queue since it is blocking the Sydney pod. See Diego's question from Aug 6.

**Comment by samitron7** [comment]
@diegovar Yes let's please move to the pill design in the prototype as the system is being used elsewhere. @barklund FYI but this component should be added to our library.

For the behavior question on what to do when you have de-select Technology and it's in the collapsed state: The technology pill should now be deselected but we should not shift the rows on the users. They can open the entire category to select something else. See prototype for this [here](https://drive.google.com/file/d/1KD0JSQnAGPsq4Emr3ux5_JRM9ckPF_Qv/view?usp=sharing).

What makes this pill behavior complex to implement? I have a check-in with you guys so we can discuss there.
