### ISSUE TITLE
Snap  lines exceeding page canvas

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2414]
## Bug Description

Looks like snap lines are currently exceeding page canvas at the bototm.

## Expected Behaviour

Snap lines should not exceed page canvas, especially not just at one side.

![Screen Shot 2020-10-27 at 10.50.31 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/e95cf40f-0c1d-4775-8a62-9a9862abfa0a)

## Steps to Reproduce

1. Drag element around
1. Notice snap line exceeding page canvas at the bottom

## Screenshots

![Mask Group.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/a304ca92-0445-4cbe-97c2-b6d16f36265a)

## Additional Context

- Plugin Version: 1.0.0
- Operating System: macOS
- Browser:  Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
The snaplines are also showing fully outside of the Page as well:
![snaplines](https://user-images.githubusercontent.com/3294597/87801464-0aa8e080-c850-11ea-9071-33b0a5bc24bc.gif)

**Comment by bmattb** [comment]
@barklund  flagged that he was seeing odd snapping throughout the editor and this should be checked. @dvoytenko flagged that moved the movable higher up the dom tree and this might be a result of this change.

**Comment by miina** [comment]
@barklund @bmattb FYI Pulling this into the Sprint to see how doable it is.

**Comment by miina** [comment]
I've been looking into the possibility of fixing this issue and here are the findings:
- The snaplines' length isn't configurable from the library we're using for snapping/resizing/dragging.
- The snaplines take the length of the parent element so it seems to be doable if we box the selection area to the area that matches the size of the Page, however, ...
- currently, all the layers -- display layer, edit layer, frames layer (including selection) -- are using the same space and the logic relies on that. Refactoring and changing the size of one of the layers (or part of it) will cause shifting and other potential issues with dragging/resizing that might take more effort than anticipated.

Based on that, it might make sense to:
- Start looking into this once the Zoom feature is complete since that will need to be addressed and considered, too, when changing the layers.
- Consider that the level of effort might be higher than currently anticipated.

@o-fernandez @samitron7 Pinging you to confirm the priority of this issue considering the potential extra effort.

cc @barklund FYI

**Comment by o-fernandez** [comment]
Once we have a points estimate we can revisit. If it's large (5+ points) I'd say we punt this until later. Doesn't seem critical to me.

**Comment by miina** [comment]
It's currently estimated at 5 but could likely extend to 8.

Moving it back to Ready for Sprint, we can come back to it later once Zoom and other more priority issues have been completed.
