### ISSUE TITLE
Templates: Update Travel template to 9:16

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#2475]
Use this Figma doc to apply 9:16 updates to the existing `Travel` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT but with following issue:

@o-fernandez My bad here but I forgot to move the "No. 3" label from the top (the system nav will definitely obscure that. Don't think this is a blocker but it reflects poorly on us (mainly ux design) since we want to set a good example. So not a blocker but fix quickly.

 
![Screen Shot 2020-06-30 at 12.46.51 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/950ec1f9-02d1-4183-ab09-3bdcc7b2d072)

Should look like this instead:
![Screen Shot 2020-06-30 at 12.50.08 PM.png](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/160e1cf9-c071-4679-a134-5e8ca1a35e09)

**Comment by swissspidy** [comment]
Let's create a new issue for that then.

**Comment by o-fernandez** [comment]
Filed this issue for Sam's new update. https://github.com/google/web-stories-wp/issues/2873
