### ISSUE TITLE
Mask Orientation on Rotated Shapes

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2599]
## Feature Description

As a creator I'd like to be able to rotate masked elements, but maintain the orientation of the image.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. I am able to rotate the image independent of the masked element
2. I am able to reset the image orientation on a a masked element

See [UX Evaluation](https://docs.google.com/presentation/d/1ZiZWrmLiX40rt3n_1LMSGJxYWI-xsWFsS9bkzdbRIV8/edit?ts=5ec6a639#slide=id.g8584f781a2_0_8)

**Comment by jauyong** [comment]
@samitron7 @o-fernandez created this from the UX evaluation. Took a stab at some AC but Sam requested the UX needed label.

**Comment by samitron7** [comment]
@dvoytenko This one is tricky. So for simplicity, I remember that you and I decided early on that we shouldn't allow rotation of an image inside a mask because it can produce unexpected behaviors (ie gaps that can cause odd clipping of the image + technical reasons). But here's the issue:

1. I have an image that I set inside a triangle
2. Now I rotate the triangle. I would like the mask to rotate but the image to not rotate. This isn't possible with the setup we have. 

We can take the stance and say "yup, when y'all rotate a mask, the image rotates with you" which I don't like because I've been trying to create designs where I would like to use 2 triangles rotated by 180 degree. Some editors solve this be creating multiple rotated versions of the shape.

Can you remind me if there were technical issues here and if we can circumvent those?
