### ISSUE TITLE
Show thumbnail on canvas while full image/video is loading

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#2615]
## Feature Description

Note in attached gif that images/videos show blank on canvas. Then suddenly, about 14 seconds in, they all show up. The current hypothesis is that this is driven by a slow server issue and loading the full images (which happens when we drag media into the canvas) took a while. 

Propose that when a user drags an asset from the media panel onto canvas, we show the thumbnail on the canvas until the full image loads and replaces the thumbnail. That way we don't have an issue with blank placeholders on canvas during loading.

![intermittent state of no images](https://user-images.githubusercontent.com/13389997/85144919-d377ed00-b219-11ea-80d6-a8e16b34f25e.gif)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by diegovar** [comment]
@samitron7 There's a good chance that the thumbnail in the media gallery is tiny and would look bad in the canvas. Do we want to blur the image in the canvas until the full sized image loads?

We could accomplish this by doing sth like this: https://codepen.io/diegovar/pen/YzqwNjg

**Comment by samitron7** [comment]
@diego, this happens in the media library correct and not on the page? Can you clarify that.

**Comment by swissspidy** [comment]
@samitron7 It happens on the page / canvas. The gif at the top explains it well.

**Comment by merapi** [comment]
What we want to achieve here sounds simple: we show the thumbnail on the canvas until the full image loads and replaces the thumbnail.

If we use the same thumbnail that is already cached in the media library - we will get an instant effect. If we load any/smallest thumbnail - it will require one additional image to be downloaded. So let's try with the cached one.

Unfortunately using the same thumbnail is not trivial since it's dynamically chosen in the media library (based on the box width) and we can't just pass the chosen thumbnail to the element on canvas via something like onClick argument, but we can store that thumbnail URL along with clicked resource identifier on a temporary list, then access that list from element display and use the cached image until the full-size image is loaded.

I was also thinking that we can store the chosen thumbnail URL on the element itself (in story data) - that way we can load the thumbnail (potentially from cache) when loading the whole story from scratch. That sounds like an initial load improvement, but there is also a high chance that a full-size image is also cached, so there will be no benefit in that case.

Solution for both loading scenarios (when an element is added + when an element is initially loaded) might look like this:
- when an image is clicked in the media library, store its cached thumbnail URL on a temporary list
- in the element display layer, check if we have something on that temporary list for a given element, if yes - use that (cached image = instant effect), if not - A) first, quickly load the smallest thumbnail or B) just load the full-size image.

WDYT?

**Comment by samitron7** [comment]
I like the idea of trying the cached image. If this works it would work for images but for video, we would need to temporary gray out the play controls on the element (there is already a loading indicator so we are good there) so the users doesn't expect to be able to play it when it loads.

**Comment by csossi** [comment]
Verified in QA

**Comment by merapi** [comment]
@csossi is it a mistake? QA is done by ENG https://github.com/google/web-stories-wp/pull/3935#pullrequestreview-476199520

**Comment by o-fernandez** [comment]
This works, but if I double-click on an image added to the canvas to change the mask while the full image hasn't loaded, it shows the empty container rather than continuing to use the thumbnail. 
#4422
