### ISSUE TITLE
Update context hooks to simplify state/action selectors

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#2662]
## Task Description

Proposal: Update react context hooks such as useStory to support a simpler syntax.

As per discussion here:
https://github.com/google/web-stories-wp/pull/1705/files#diff-4c52a87be51ed328b2d8709e5705240d

Before:
```
const {
  currentPage,
  selectedElementIds,
  toggleElementInSelection,
  setSelectedElementsById,
} = useStory(
  ({
    state: { currentPage, selectedElementIds },
    actions: { toggleElementInSelection, setSelectedElementsById },	
  }) => {	
    return {	
      currentPage,	
      selectedElementIds,	
      toggleElementInSelection,	
      setSelectedElementsById,	
    };	
  }	
);
```

After:
```
const { currentPage, selectedElementIds } =
    useStoryState(['currentPage', 'selectedElementIds']);
const { toggleElementInSelection, setSelectedElementsById } =
    useStoryAction(['toggleElementInSelection', 'setSelectedElementsById']);
```

**Comment by dvoytenko** [comment]
@cvolzke4 @barklund Hmm. While the original form is pretty verbose, I still find it pretty useful and instructing. Also, substituting symbolic property access with quoted strings might hamstring us in the future. Are we sure there are strong enough reasons for this?

**Comment by cvolzke4** [comment]
> @cvolzke4 @barklund Hmm. While the original form is pretty verbose, I still find it pretty useful and instructing. Also, substituting symbolic property access with quoted strings might hamstring us in the future. Are we sure there are strong enough reasons for this?

In some places I feel this is more readable as it reduces boilerplate considerably. I'm not strongly for or against this style though, I can understand that using strings to reference the properties may cause problems if we ever moved to typescript.

**Comment by barklund** [comment]
@cvolzke4 @dvoytenko, I know that I was the one suggesting this in the first place, but the more I work with the current system (of verbose selectors), the more I like it.

The only thing that might be relevant, is if we have some single selectors, that are heavily repeated - perhaps if we see a lot of this:

```js
const { currentPage } = useStory(
  ({ state: { currentPage } }) => ({ currentPage })	
);
```

It might be nice to make a single-selecting hook such as:

```js
const currentPage = useCurrentPage();
```

It would be a shorthand *only* used for the *top X most commonly used single properties* across the application, and if you need any other properties, you'd have to go the longhand route.

Does that make sense? Or is it not worth it?

**Comment by dvoytenko** [comment]
I think the targeted hooks is good idea imho. Alternatively, we could also have a library of selectors. I think that'd be most important for state props.

E.g. 
```
const currentPage = useCurentPage();
// or
const {currentPage} = useStory(StorySelectors.currentPage);
```

both seem ok to me.

**Comment by maxyinger** [comment]
Just gonna summarize some recent conversation I had around this after doing some performance work recently.

Originally I tried out mocking what the library had:
```js
const currentPage = useStory(v => v.state.currentPage);
const selectedElementIds = useStory(v => v.state.selectedElementIds);
const toggleElementInSelection = useStory(v => v.actions.toggleElementInSelection);
const setSelectedElementsById = useStory(v => v.actions.setSelectedElementsById);
```
I liked this approach for a couple of reasons:
- less lines
- less layers of indirection around object equality to prevent unnecessary re-renders
- further leans out the number of objects to reason about, would even be of benefit to make context values flat and remove the separation of `actions` or `state`

At the time tho, I didn't realize we had written a wrapper around this library to do shallow comparison (instead of referential equality which the library defaults to). I'm curious if this was just written so we could group context value properties in our selectors return values or if there were other benefits outside of enabling api preference? Regardless, there's definitely pros and cons to having the return value from selectors shallowly compared, but if you use it right, it doesn't really matter.

At the end of the day, the current selector pattern is fine, albeit a little verbose, and a lot of this is just personal preference. The only big things that actually shoot us in the foot performance wise are:
- pulling in more state than we need into components
- pulling in state to derive a value off of it that changes less frequently than the state
- pulling in story state to derive story actions

**Pulling in more state than we need into components**
The most common pitfall I see here is pulling in `currentPage`. Rarely do components need the entire `currentPage`, but it is pulled in frequently. This causes a component to have empty re-renders on most story actions even if the property it's reading off of `currentPage` isn't updating. Example:
```js
const { currentPage } = useStory(({ state }) => ({ state.currentPage }));
const someMetaAttribute = currentPage.someMetaAttribute;
// vs
const someMetaAttribute = useStory(({ state }) => state.currentPage.someMetaAttribute);
```

**Pulling in state to derive a value off of it that changes less frequently than the state**
This is a big one with element specific components. We frequently pull in all elements to derive some value off of it. Consider getting the background element id, or deriving a boolean off of `elements.every(...)` or `elements.some(..)`. This should all be derived in the scope of the selector, not the components body, to prevent empty rerenders:
```js
const { currentPage } = useStory(({ state }) => ({ state.currentPage }));
const backgroundElementId = currentPage?.elements[0].id;
// vs
const backgroundElementId = useStory(({ state }) => state.currentPage?.elements[0].id);
```
or
```js
const { currentPage } = useStory(({ state }) => ({ state.currentPage }));
const isSelected = currentPage?.selectedElements.includes(selectedId => selectedId === id);
// vs
const isSelected = useStory(({ state }) => state.currentPage?.selectedElements.includes(selectedId => selectedId === id));
```

**Pulling in story state to derive story actions**
We shouldn't really be referencing pulled in story state to derive a story reducer action. All referenced story state in a reducer action should be referenced in the scope of the reducer, any external state should be passed in through the payload. This is great for preventing unnecessary re-renders, but also 100% ensuring you're not referencing stale data when the action is updating state
```js
const { 
  someAction,
  anotherAction, 
  currentPage 
} = useStory(({ state, actions }) => ({
  someAction: actions.someAction,
  anotherAction: actions.anotherAction, 
  currentPage: state.currentPage 
}));

const someHandler = useCallback((evt) => {
  if(evt.metaKey && currentPage.selection?.length > 0) {
    someAction(...)
  }
  anotherAction(...)
}, [  someAction, anotherAction, currentPage ]);

// vs
const combinedAction = useStory(({ actions }) => actions.combinedAction);
const someHandler = useCallback((evt) => combinedAction({ metaKey: evt.metaKey }), [  combinedAction ]);
```

**Comment by maxyinger** [comment]
In general tho, I think the nature of `use-story-selector` necessitates some knowledge of its inner workings to use it effectively and there's not really a pattern that eliminates this need.

I guess the only danger in shallow equality comparison functions by default is the scenario @cvolzke4 mentioned where you don't realize you're doing a shallow comparison on an object when you do:
```js
// this would be fine with the library as is, but not with our current wrapper around it
const currentPage = useStory(({ state }) => state.currentPage);
// this is adding unnecessary object creation so that we can have shallow equality as the default comparison fn, but
// essentially just do a referential equality check. Basically our added code around the library is making us add extra code
// to get back the original functionality of `useContextSelector`
const { currentPage } = useStory(({ state }) => ({ currentPage: state.currentPage }));
```

although it does allow for some niceties like this. Here `useContextSelector` wont force a re-render unless elements are re-ordered, added, or removed:
```js
const elementIds = useStory(({ state }) => state.currentPage?.elements.map(el => el.id));
return elementIds.map(id => <SomeMemoizedElementComponent key={id} id={id} />)
```
