### ISSUE TITLE
Selecting Media creates a new history entry

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#2664]
## Bug Description

`hasNewChanges` is `true` after I select something.
https://drive.google.com/file/d/1ZePEpYtQvUGyF0UueZgaYG9izuiyciFM/view?usp=sharing

## Expected Behaviour

Selecting the element shouldn't affect history.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Originally reported in #2547

(Don't mind me, just cross-referencing issues)

**Comment by miina** [comment]
@barklund / @bmattb FYI Pulling this into 1.2 and Sprint 41.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Just making sure I'm testing this one correctly @miina @barklund:

Here is how I QA this one:
1. Add text element on to page
2. Add media to page and resize
3. Select and change text
4. Select media
5. Select and change text
6. Undo #1: undo text edit
7. Undo #2: image is selected and text change is undone 

During undo #2, the image is selected (ie in focus). Shouldn't the text be the element that is in focus?

**Comment by miina** [comment]
@samitron7 The selection of the state before the text change is restored with undo, so the behavior is correct, there was a longer discussion on how it should work some time ago, for example in [this comment thread](https://github.com/google/web-stories-wp/pull/1065#issuecomment-611904360).

About this issue specifically -- the issue here was actually that when the user selected media, a new history entry was created. So for testing this issue just the following can be done:
1. Add Media element
2. Save and refresh the page to start with clean history
3. Select the media
4. Verify that Undo is not active since nothing was changed meanwhile.

**Comment by samitron7** [comment]
@miina Given your QA directions, this ticket passes UAT but the selection issue is a use case that wasn't addressed in the comment thread from the link you provided. If you select an image but no edits were made then go on to do something else and hit undo, we should't hilite the selection of the image since nothing was done to it. These are just additional undo steps for a user. You can test this behavior out on google slides. I'll close this ticket out and [file one](https://github.com/google/web-stories-wp/issues/5468) for the selection issue which I'll mark as a low priority since it's an enhancement (undo works but logic introduces additional undo steps for users).
