### ISSUE TITLE
Update Stories WordPress admin menu

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#2750]
## Feature Description

Ideas from the bug bash to improve the Stories Menu on the left hand side.

Stories menu (WP Left hand) could be clearer/options could be rethought. Propose having: 
1. **My Stories:** this would go to the My Stories dashboard page. 
2. **Explore templates**
3. **Add new**
4. **All Stories**
5. **Settings**

When we add other menu options (Settings, Custom Templates, etc.) we can add as appropriate. 

![image.png](https://images.zenhubusercontent.com/5e985a7aea3104e101699670/269605a9-3a8c-44b2-9317-34d3d3a86e48)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
* I don't think we need to rename "Dashboard" to "Stories Dashboard".  
  WordPress users are familiar with that term, and it's pretty clear from the title right above it that it's the dashboard for _stories_.
* Once we have a global settings page, that should also be added to the menu.

**Comment by hansschuijff** [comment]
> I don't think we need to rename "Dashboard" to "Stories Dashboard".
WordPress users are familiar with that term, and it's pretty clear from the title right above it that it's the dashboard for stories.

@swissspidy I agree on not changing the name, since the context of stories is already mentioned in the main menu level.

Having said that, my first association with the term dashboard would be something offering information mostly and this dashboard seems actually to be the whole app. 

So the plugin in some ways seems to hink on two thoughts:
1. on the one hand it follows the wordpress convention of an "Add new" and a Custom post_type list menu-item (in which other plugins might add some new features the wordpress way.
2. But on the other hand it also offers a complete app including most options of the others menu-items and having it's own internal menu (templates?) and buttons also.

Why not choose and be clear about the root you want users to follow? If you want the app-approach adding a settings button and view button would suffice to make it more complete. And if not, why not just follow the wordpress convention like other plugins?

On my install I have several dashboards, like the WooCommerce one, offering mostly analytics, and the wordpress one, offering a list of mostly informative widgets. Having a dashboard in a submenu is not that common yet, and from the plugins I've usedd and know of only woocommerce seems to have chosen that route (and it's the default route but actually the page I visit the least). Naming an app dashboard would perhaps not do it justice enough and confuse expectations.

If it is intended as the whole app, you could best just call it Stories instead of dashboard. And consider if the other options are needed at all. Or choose the normal WordPress routes instead and make them better. My wish to have templates added to the menu is mostly fuelled by the desire to remove the extra pageload of first going to the dashboard and then click the choose template etc. Pageloads are expensive and cost time and it that way going through the dashboard would not be my normal route if there are alternatives.

Hope it helps.

**Comment by ernee** [comment]
Refer to the following issue for more user feedback: https://github.com/google/web-stories-wp/issues/3650

**Comment by o-fernandez** [comment]
Updated the description to what I think is a "pretty good" proposal given the thread/conversation and what the product offers. We can tweak this further based on user feedback, but would suggest making the tweaks proposed here: 

1. Update "Dashboard" to be "My Stories" 
2. Add "Explore Templates"
3. Add "Settings"

**Comment by csossi** [comment]
Verified in QA

**Comment by o-fernandez** [comment]
One thing here, if I navigate to a dashboard page (e.g., Explore Templates) the nav menu is still highlighting "My Stories" instead of the appropriate dashboard page. 
![image.png](https://images.zenhubusercontent.com/5e98486db524b82fc96aeaf6/0b701603-edcc-4b08-8ff6-cf30efaf8cf5)

Will open a ticket to fix this.
