### ISSUE TITLE
Finish implementation of color+style presets

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#279]
As a user I want to be able to set color presets

**Acceptance Criteria**

1. The user is able to set color presets and persist between sessions
2. The user is able to collapse the color preset section
3. The editor is able to save color to the preset library
4. Contextual design panel based on selected element (shape, text)
5. Editor is able to collapse the preset menu in the design panel
6. After a text element is selected, the text color and textbox color menus are exposed in the design panel.
7. Will not differentiate between local colours from template and custom colors defined by the user
8. User is able to delete colors (currently missing from design) (edit icon missing, which triggers X's over overlays so you can delete a color)
9. A color added as preset will be added to all stories globally (will always be visible in the editor, for everyone)

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6407%3A228)**

**Comment by miina** [comment]
Starting looking into this issue, since color presets are related to the whole story and not a Page nor an element then it seems like it would make sense to save it as meta data for a Story (in terms of the WP DB). Could be just an array, e.g. `[color1, color2, color3, ...]` assuming that each color will just be a hex value, alternativelt, an array of objects (TBD elsewhere).

(Note that color presets will not influence how anything will be displayed in the FE, it's for the editor only.)

The color presets would then be fetched and updated via API.

Let me know if you have any thoughts on this that might suggest that an alternative would be better.

// @spacedmonkey @swissspidy

**Comment by jauyong** [comment]
@pbakaus and @samitron7 do discuss further. (Global vs story?)

**Comment by jauyong** [comment]
@samitron7 to add design for deleting colors

**Comment by miina** [comment]
@swissspidy @spacedmonkey Tagging you for this comment again in case it was missed among others: https://github.com/google/web-stories-wp/issues/279#issuecomment-594034547

**Comment by swissspidy** [comment]
Thanks @miina! I was thinking of just storing them in the JSON blob, but I suppose post meta is more portable. Especially once we introduce global presets. 

Or perhaps even a custom taxonomy?

**Comment by pbakaus** [comment]
Heads up: @samitron7 and I decided to make color presets global for 1.0, which means that a color added as preset will be added to all stories (will always be visible in the editor, for everyone). Sam will follow up with design for this today.

**Comment by dvoytenko** [comment]
@pbakaus @samitron7 please reassign to the team when ready for implementation.

**Comment by kmyram** [comment]
@pbakaus @samitron7 Is this ready now?

**Comment by pbakaus** [comment]
yes, it's ready. I'll let @samitron7 point to the relevant figma section.

**Comment by jauyong** [comment]
I'm guessing it's this? I updated the link in the description.
https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=6407%3A228

**Comment by miina** [comment]
@jauyong For information:

Although part of it got ready within #753 for alpha, keeping this open for finishing the issue. Will continue on it once alpha-critical issues get done.
