### ISSUE TITLE
Unable to resize shape -> make min/max values consistent between design panel and resizing.

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#2830]
UPDATE: the main bug to fix is the difference between resizing and design panel min/max values, which is the clearest bug here. Min/max values should be consistent between resizing and design panel, and follow our values in the spec spreadsheet: https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0

Steps to reproduce
1. Add a box element to the page
2. Change the width to 6px
3. Now try to drag the bottom right control down to resize height. Note the abrupt jump in height value. It's impossible to resize height using the controls.

![unableToResize.gif](https://images.zenhubusercontent.com/5e9dc6e34754fda9ccd26e86/efef8fd0-134d-475c-a9a0-550f166b9da3)

**Comment by miina** [comment]
Looks like we have a conflict due to minimum width size here:
- The design panel allows minimum width 1px.
- Resizing allows minimum width 20px.

At the same time, when resizing from a corner, the width and height are being resized in sync (locked ratio). This basically means that if the user starts resizing, the width 6px is suddenly changed to 20px (since that's the enforced minimum when resizing) which will also cause the height to increase more than 3x.

@samitron7 / @o-fernandez What is the expected behavior here? Should the design panel and resizing minimum width and height perhaps match for consistency?

**Comment by o-fernandez** [comment]
Ah, I see. It could be one of the permutations of the min/max values. 

I'd say we should at a minimum have consistency in min/max values between design panel and resizing. The latest source of truth of min/max values is in this link: https://docs.google.com/spreadsheets/d/1hdru-_p4Yk-VFQ1rEFGYHHI2A7eNZkxLA33-LblG8sE/edit#gid=0

**Comment by samitron7** [comment]
The selection box were designed based on the old values which created enough space for you to resize from the left or right if you have width = 20px. With 1px width, we need to make some modification to this. @miina Can we easily show a drag arrow to the right or left of the 1px box? And will it fluidly work if you drag. I've seen so messy implementation of this.

**Comment by miina** [comment]
This would probably need testing out to be certain, @merapi might know better since he implemented the minimum values to resizing originally, perhaps he already tried with smaller values as well.

**Comment by o-fernandez** [comment]
Per meeting, we will for now just make resizing using the box or using the design panel to match the spreadsheet (e.g., min of 1px is fine). That will eliminate the jump due to the discrepancy of selection box vs. design panel min widths.
