### ISSUE TITLE
Enable Stories Archive Page

### ISSUE THREAD

**Issue by digitalsetups** [GoogleForCreators/web-stories-wp#3063]
## Feature Description

Add a default stories archive page having latest stories displayed as in dashboard. Pagination is also important. 

## Additional Context

Currently we can access only the singular page and not archive one. As stories is also a post type, all latest stories must be available in its post archive page or example.com/stories in a stories-style layout.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* In `Story_Post_Type`, set `has_archive` to `true` so the `web-story` post type supports an archive
* Since adding archive support affects permalinks, flush rewrite rules upon upgrade, probably in the `Database_Upgrader` class.

**Comment by swissspidy** [comment]
Ha, I was just about to look for this issue / create one after replying to #3064. Thanks!

The crux here is _"in a stories-style layout"_. We still have to figure that one out.

Right now, I think we'd probably just leave the layout up to the  theme, and simply display a story player instead of the story's excerpt/content.
