### ISSUE TITLE
Automatic Bookend Expected

### ISSUE THREAD

**Issue by digitalsetups** [GoogleForCreators/web-stories-wp#3066]
Help me with clarification of bookend feature. I can see it in the code part and expect an automatic bookend of related stories or posts from the same post type (web-story). Currently, I'm unable to see any story bookend. 

Am I missing something? 
And are there any options to pick the layout of bookend?

**Comment by swissspidy** [comment]
Hi there, thanks for raising this!

The Web Stories format's bookend feature is actually going to be deprecated, see https://github.com/ampproject/amphtml/issues/26957 for details.

That's why we didn't implement any functionality to customize the bookend.

The functionality originally provided by the bookend (sharing, next stories) will now be provided by the story player. The AMP project is open to receiving feedback for this though. The feature won't be fully deprecated until alternatives are finalized.

Still, it doesn't make much sense to add support for this in the plugin if it's going to be deprecated.

**Comment by digitalsetups** [comment]
Bookend keeps the user intact after the story completion automatically. Right now, not every user will get an idea to go back and forth for the next story. Having related posts / stories shown automatically or at one place helps the reader to pick story of their choice instead of forcefully showing them either previous-only or next-only story. 

Though I'm not in favor of depreciating bookend , but I understand your point here for this plugin. 

Just let me know if the story player feature will automatically display next and previous stories?

**Comment by swissspidy** [comment]
> Just let me know if the story player feature will automatically display next and previous stories?

Yes, but it depends on the implementation. For example, a player like on Google Search can display next and previous stories automatically and.

Our Story Embed block also uses the amp-story-player, but right now only displays 1 story. It can display multiple stories too in the future. It would look a bit like this:

![amp-story-player (1)](https://user-images.githubusercontent.com/841956/87087322-2cdca600-c233-11ea-918d-5b8a51bbee8d.gif)
