### ISSUE TITLE
Allow non-http links in URL

### ISSUE THREAD

**Issue by quadcom** [GoogleForCreators/web-stories-wp#3221]
## Feature Description

Currently, links entered in the URL field are automatically appended `http://`. I am trying to add a `tel:`  link so that mobile users can initiate a phone call.

## Alternatives Considered

There are no other alternatives at the moment. 

## Additional Context

![image](https://user-images.githubusercontent.com/7085931/87585494-2627b600-c6ad-11ea-9f82-a92850cf7caf.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Great suggestion, thank you!

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #10389.

1. Added an image
2. Added a link
3. Entered phone number
4. Previewed/published story
5. Clicked on the image
6. Clicked on the hint - Skype (my default call app) was displayed
7. Repeated same steps with an email instead of a phone number - Outlook (my default mail app) was displayed
8. Entered invalid tags such as te: instead of tel: and mailt: instead of mailto: and those tags become part or a URL (after https://)


https://user-images.githubusercontent.com/96055551/151420633-07c96c9d-2db0-41cc-82c9-068f55ff3664.mp4


https://user-images.githubusercontent.com/96055551/151420639-a17a6983-9a46-4835-808e-7b9319f0e2a7.mp4

**Comment by swissspidy** [comment]
@felipebochehin87 great feedback, thanks for testing!
