### ISSUE TITLE
Cannot activate the web-stories-wp master in WordPress

### ISSUE THREAD

**Issue by injainja** [GoogleForCreators/web-stories-wp#3231]
I can install the zip-file, but when I try to activate the plugin, there will be this error-message:

Fatal error: Uncaught Error: Class 'Google\Web_Stories\Plugin' not found in /var/www/vhosts/liesenfeld.de/httpdocs/WP/wp-content/plugins/web-stories-wp/includes/namespace.php:142 Stack trace: #0 /var/www/vhosts/liesenfeld.de/httpdocs/WP/wp-content/plugins/web-stories-wp/web-stories.php(56): require() #1 /var/www/vhosts/liesenfeld.de/httpdocs/WP/wp-admin/includes/plugin.php(2255): include('/var/www/vhosts...') #2 /var/www/vhosts/liesenfeld.de/httpdocs/WP/wp-admin/plugins.php(177): plugin_sandbox_scrape('web-stories-wp/...') #3 {main} thrown in /var/www/vhosts/liesenfeld.de/httpdocs/WP/wp-content/plugins/web-stories-wp/includes/namespace.php on line 142

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report!

If you download the plugin straight from GitHub, you will only get the _source_ files, not the final _build_ that includes all JavaScript and PHP files to run the editor. That's why  you get the error about classes not being found.

To prevent this, please download the ready-to-use version from from https://google.github.io/web-stories-wp/beta/

If you want to install the latest master version instead, follow our[ Getting Started guide](https://github.com/google/web-stories-wp/blob/master/docs/getting-started.md) for contributors and the steps needed to _build_ the plugin.

In the meantime, we'll work on making the message a bit clearer for cases like yours and prevent fatal errors.

**Comment by injainja** [comment]
Ah, thank you for explaining that to me. i hope i'm not too much testing your patience if I ask if there is a simpler way to build a usable Version without having to install all those things to my computer. Like with visual studio or any other way? Thank you so much. I am already working with the public beta version (and considering that it's still beta it's already awesome) and would like to test the latest additions like animation and so on.

**Comment by swissspidy** [comment]
I'm afraid it would require installing a couple of things on your computer. But if you want to get the bleeding edge version (i.e. current master), you can download it here: [web-stories.zip](https://github.com/google/web-stories-wp/files/4933443/web-stories.zip)

There are some changes since the beta, but only small-ish ones I think. Animations are not yet finished though :-) But we might just publish another beta once that happens.

**Comment by injainja** [comment]
Thank you so much :-)
