### ISSUE TITLE
Add Unsplash attribution to the bottom of the provider tab

### ISSUE THREAD

**Issue by cvolzke4** [GoogleForCreators/web-stories-wp#3357]
## Task Description

As per UX:
https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7454%3A942

A spike of the attribution pill can be found here:
https://github.com/google/web-stories-wp/compare/try/coverr-mock#diff-dd6e2e686434fe0300a8809ad6ad354aR63

**Comment by diegovar** [comment]
@samitron7 The mocks show the attribution at the bottom left, but this will probably overlap with the "Loading..." pill that is shown when loading more pages of media. How should these 2 interact? Should the Loading be shown above the attribution indicator, or should we add padding below the "Loading..." pill so that they don't intersect?

**Comment by samitron7** [comment]
@diegovar When we need to show the loading pill, let's remove the unsplash attribution temporary. Basically you'll show one and not both at the time. This makes the ui a lot cleaner.
