### ISSUE TITLE
Add percy test for categories panel and pills

### ISSUE THREAD

**Issue by ezxyz** [GoogleForCreators/web-stories-wp#3358]

**Comment by ezxyz** [comment]
I'm a bit confused about this since I can't find information on how to run percy tests locally. I've tried setting the percy token to the one in percy.io and followed the instructions on https://docs.percy.io/docs/local-development then ran

> npm run percy
> npm run test:e2e:percy

But neither option seemed to have worked.

I've asked a question on slack and I'll just move this back to the backlog for now since I might not get a response today, and I'm taking leave starting tomorrow.

**Comment by ezxyz** [comment]
https://xwp.slack.com/archives/CCCAUAH6F/p1595899002201200 link to question.

**Comment by swissspidy** [comment]
First you'll haqve to clarify whether you want to run Percy for the Karma tests or the E2E tests. I assume the former.

In your Karma tests, call `await fixture.snapshot();` to take a snapshot of the current state. The function takes an optional parameter for the snapshot name.

Then, run `npm run test:karma:edit-story -- --headless --snapshots --viewport=1600:1000` to run the test suite as usual.

`snapshots` makes sure that snapshots are taken (otherwise they're ignored).
The `viewport` option makes sure that we're using the same viewport consistently everywhere.

Now you can run `PERCY_TOKEN=<yourtoken> npm run percy` to upload the snapshots to percy.

**Comment by ezxyz** [comment]
@swissspidy 
I'm trying to see the new generated snapshot.

Where are the snapshots stored locally when `npm run test:karma:edit-story -- --headless --snapshots --viewport=1600:1000` is run? 

When I run `PERCY_TOKEN=<yourtoken> npm run percy` does it upload it to the main percy snapshots that everyone is comparing to? Or is it just for my local branch?

**Comment by swissspidy** [comment]
Snapshots are stored in `.test_artifacts/karma_snapshots`. Not sure about the location on percy when running locally. I think it just uses your current Git branch, but would need to consult the docs.
