### ISSUE TITLE
Dashboard Template Preview Overlay

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#3390]
## Feature Description

Mirroring the preview overlay in the workspace, when you preview a template an overlay should appear that plays the complete template.

https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=7669%3A852

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Visit the templates section on the dashboard
2. Click the preview button or card
3. An overlay with a full preview playing the story should show

For now we are not showing the device or OS toggle in the preview.

**Comment by BrittanyIRL** [comment]
This work is hidden behind the feature flag called: `enableTemplatePreviews`. 

I opted to have the preview triggered by clicking the template card _outside_ of the two existing buttons. Since 'View' takes the user to the template detail view. We should probably figure out a more obvious way to have this triggered since it's not exactly intuitive? But this allows us to at least get started!

**Comment by BrittanyIRL** [comment]
Should see a preview overlay in explore templates as well as in template details -> related templates

**Comment by csossi** [comment]
Testing in PR#3447 in QA environment

Not seeing PREVIEW button and nothing happens on clicking card:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/956659a1-4d30-4ae5-9873-391a3b633e82)

**Comment by BrittanyIRL** [comment]
Same thing as the stories preview here, can you try this again and verify that the template preview flag is enabled? 
![Screen Shot 2020-08-10 at 8 32 09 AM](https://user-images.githubusercontent.com/10720454/89800726-0042d500-dae4-11ea-93b3-00fa35f70043.png)

**Comment by csossi** [comment]
Verified in QA
