### ISSUE TITLE
error on installation through Github updater 

### ISSUE THREAD

**Issue by netnaps** [GoogleForCreators/web-stories-wp#3399]
## Bug Description

Fatal error: Uncaught Error: Class 'Google\Web_Stories\Plugin' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/web-stories-wp/includes/namespace.php:142 Stack trace: #0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/web-stories-wp/web-stories.php(56): require() #1 /opt/bitnami/apps/wordpress/htdocs/wp-admin/includes/plugin.php(2255): include('/opt/bitnami/ap...') #2 /opt/bitnami/apps/wordpress/htdocs/wp-admin/plugins.php(177): plugin_sandbox_scrape('web-stories-wp/...') #3 {main} thrown in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/web-stories-wp/includes/namespace.php on line 142

## Screenshots

![Screenshot 2020-07-23 at 4 57 43 PM](https://user-images.githubusercontent.com/67054369/88281640-ac737600-cd05-11ea-9d0b-d39f2a4c87d4.png)

- Plugin Version: latest

## Implementation Brief

was installed via Github Updater Plugin for WordPress

**Comment by swissspidy** [comment]
Thanks for your report!

If you download the plugin straight from GitHub, you will only get the _source_ files, not the final _build_ that includes all JavaScript and PHP files to run the editor. That's why  you get the error about classes not being found.

To prevent this, please download the ready-to-use version from from https://google.github.io/web-stories-wp/beta/

If you want to install the latest master version instead, follow our[ Getting Started guide](https://github.com/google/web-stories-wp/blob/master/docs/getting-started.md) for contributors and the steps needed to _build_ the plugin.

Please also note that we've already updated the messaging to make this more clear.
