### ISSUE TITLE
Animation Effect: `fly-in`

### ISSUE THREAD

**Issue by mariano-formidable** [GoogleForCreators/web-stories-wp#3421]
Recreate the built-in AMP Story animation `fly-in`.

Should support, via props, the permutations of `fly-in-bottom`, `fly-in-left`, `fly-in-right`, and `fly-in-top`.

### Default Properties
`duration`: 500
`delay`: 0

### Editor Panel
<img src="https://user-images.githubusercontent.com/40646372/88425629-8a7d0080-cda4-11ea-8472-30ce8006b6f1.png" height="300">

### Desired Output
Two page AMP Story example in Storybook.  The first page implements the AMP Story `fly-in-bottom`, `fly-in-left`, `fly-in-right`, and `fly-in-top` animations and the second page implements our recreated `fly-in` animations.  Both should look the same :sunglasses:

### Helpful Sources
- [AMP Story animation docs](https://amp.dev/documentation/guides-and-tutorials/start/visual_story/animating_elements/?format=stories)
- [Animation product specs](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.m0pv6unnoqe)

**Comment by maxyinger** [comment]
I think we should wait to do any of these presets that reference the page or the elements position/size  (https://github.com/ampproject/amphtml/blob/60c34f6742e1f9aca148a2a23b9c82825e0b2833/extensions/amp-story/1.0/animation-presets.js#L104) until the PR for this ticket gets merged in since it's incorporates an architectural change that allows us to reference these values.

Going to go through and see which effects are blocked by this right now by referencing the amp story animation presets source code.

**Comment by mariano-formidable** [comment]
> I think we should wait to do any of these presets that reference the page or the elements position/size (https://github.com/ampproject/amphtml/blob/60c34f6742e1f9aca148a2a23b9c82825e0b2833/extensions/amp-story/1.0/animation-presets.js#L104) until the PR for this ticket gets merged in since it's incorporates an architectural change that allows us to reference these values.
> 
> Going to go through and see which effects are blocked by this right now by referencing the amp story animation presets source code.

I'm not sure what you mean by this... I've already got Fly-In working in this PR (https://github.com/google/web-stories-wp/pull/3545).  What values are you referring to when you say "architectural change that allows us to reference these values"?
