### ISSUE TITLE
Avoid conflicts with WordPress core's forms.css

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#349]
As mentioned by @spacedmonkey in https://github.com/google/web-stories-wp/issues/324#issuecomment-588171186:

> I had some with components becauses of [forms.css](https://github.com/WordPress/WordPress/blob/511a297fb4b89ad32e89ea0373347cf92367e1c3/wp-admin/css/forms.css). This css resets lots of the input / form fields, which is already an issue.

I am curious to learn how Gutenberg deals with that. I only found https://github.com/WordPress/gutenberg/blob/38da1313fd72a077bc0e46afcc41d33cf6def1ad/packages/edit-post/src/components/meta-boxes/meta-boxes-area/style.scss#L5-L15. We should ask about it on Slack.

**Comment by miina** [comment]
Could we perhaps just disable `forms.css` for our editor and add the needed parts (if there are any) back ourselves?

**Comment by barklund** [comment]
> I am curious to learn how Gutenberg deals with that.

From the comment it sounds like they just use higher specificity. Which is not really solving it, just working around it while making the editor perform worse.

If we, as @miina suggests, can completely circumvent the stylesheet from loading, that would be a huge benefit.

Otherwise, we could just make a copy of all the rules in forms.css but just with everything set to `initial !important`. That ought to reset things to browser defaults, I think?

**Comment by dvoytenko** [comment]
We should definitely try to disable ASAP, before we start riddling our code with `!important` that will be hard to remove later.

> Otherwise, we could just make a copy of all the rules in forms.css but just with everything set to initial !important. That ought to reset things to browser defaults, I think?

@barklund - that will help, but only slightly. We'll have to use `!important` anyway - just for a somewhat fewer reasons.

**Comment by swissspidy** [comment]
There shouldn't be any other form elements outside the editor/dashboard, apart from some buttons perhaps. We can try just disabling it for sure.
