### ISSUE TITLE
Background animations

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#3529]
Background animations will be a subset of available animations. Notably, we can't support animations applied to the bg that can cause the following issues: 

- transparency changes (bg doesn't support transparency)
- media rotation or shrinking/enlarging that causes bg gaps. 

Given this, we propose limiting the animations that can be applied to the bg, instead of the full original [built in animations list](https://docs.google.com/document/d/11xtdVNrSa16qg9tmg_ACw6vTD8z8wymhkRSgOqkVCa8/edit#heading=h.m0pv6unnoqe) to just:

- panning
- zoom in/out

For these, we must have checks and restrictions to ensure that the image will always cover the full page background. 

From comment thread below: propose that we follow this logic --
"Take some preventative measure in the animation themselves and leave the input as the user left it. i.e. someone says pan 1000px to the left, but the image can only pan 300px to the left we leave 1000px in the input but only pan 300px in the animation."

**Comment by maxyinger** [comment]
Just added a UX needed tag here for the following scenario.

What happens if the user applies a pan or zoom value that leaves empty gaps between the BG image and the canvas? because the user could zoom out to a degree that makes the image smaller than the canvas. They could also pan far enough to either direction that the image doesn't take up the full canvas.

I'm thinking we could do one of the following:

1. Take some preventative measure in the animation themselves and leave the input as the user left it. i.e. someone says pan 1000px to the left, but the image can only pan 300px to the left we leave 1000px in the input but only pan 300px in the animation.
2. Fail on the actual input so if user enters 1000px, but the image can only pan 300px, don't allow them to enter anything greater than 300px
3. Rethink what animations we allow on BG images so the animation, regardless of input, can't allow for whitespace i.e. only allow for zoom-in & not zoom-out

Option 2 would require UX and I think be the most work. 
Option 1 would still take some engineering work but I don't think it would necessitate any UX or design work.
Option 3 would definitely be the least work overall.

> transparency changes (bg doesn't support transparency)

^^ also just to make sure I'm on the same page, could someone let me know when we'd run into this scenario?

**Comment by bmattb** [comment]
@o-fernandez / @samitron7 flagging this to you for response.

**Comment by o-fernandez** [comment]
> @o-fernandez / @samitron7 flagging this to you for response.

@samitron7 and I discussed yesterday. 

In the description here I had: "For these, we must have checks and restrictions to ensure that the image will always cover the full page background." 

When it comes to @littlemilkstudio's proposals...

UPDATE: chatted with Sam and it'd be good to go for Option 2, but with a tweak. Rather than not allowing them to enter anything greater than a certain value, we can follow the same pattern we have in other input fields (like text) where if I enter a value that's too large or too small and press enter, then the value is changed to the min/max for the field. e.g., in Text if I click 1, it resets to 8. 

Understand that for animations this value would be dynamic, so if it's too much work let's discuss alternatives @littlemilkstudio

**Comment by maxyinger** [comment]
@o-fernandez I think that's manageable for next sprint, but will be a big task. (I'm starting to think after getting more clarity with sam this might be more of an 8 than a 5). 

I think there's kind of an unknown for next sprint which is how much design update work we need in the existing panels before release. If that work is small, I don't think it'll be a problem, but if that work ends up being larger we may need to make some tradeoffs here

**Comment by o-fernandez** [comment]
@littlemilkstudio great, thanks for flagging. @choumx @bmattb for awareness. 
I'm OK revising our release schedule and/or scope per release to accommodate these updates. We can discuss in sprint planning.

**Comment by samitron7** [comment]
For this particular ticket, @littlemilkstudio and I chatted offline and agreed to do the following:
1. Zoom should have 2 states: IN and OUT
2. Instead of using a start and end input field, we need a single slider. The max/min value for the element should map to the value found in the edit mode.

Once I complete the ui, I'll attach the figma file.

**Comment by dreamofabear** [comment]
+1 to @samitron7. Another idea is to always pan left/right all the way to the edge of the viewport, but allow the user to configure the timespan (configure pan velocity).

**Comment by maxyinger** [comment]
> Another idea is to always pan left/right all the way to the edge of the viewport, but allow the user to configure the timespan (configure pan velocity).

Yea I think I misspoke earlier and this is what amp story animations and our current pan effect implementation does. Right now tho I think there may be a difference between implementing this for our bg pan vs a fg object. Will give updates as I dig a little deeper

**Comment by maxyinger** [comment]
initial implementation of bg zoom here with slider input mirroring static bg scale slider:
https://github.com/google/web-stories-wp/pull/5293

**Comment by maxyinger** [comment]
Working on background pan. Assuming it will pan as much as it can given the static background zoom (and not apply any additional zoom to the bg image). 

Do we want to remove pan for foreground objects all together and make it a background only animation effect? It honestly doesn't feel very intuitive and essentially transforms the foreground object into a background object.

@samitron7 What are your thoughts here?

**Comment by samitron7** [comment]
@littlemilkstudio pan and zoom are only bg animation. See Figma design here for [fg](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1687%3A8065) and here for [bg](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2319%3A251688). Note in the animation menu that pan and zoom only appear when you've selected a bg image/video.

**Comment by o-fernandez** [comment]
Generally, this *works* but we need to file tickets to ensure the UX is revamped as part of adopting the new components.
