### ISSUE TITLE
Failed to save the story

### ISSUE THREAD

**Issue by nunomura** [GoogleForCreators/web-stories-wp#3542]
I'm trying to use the Web Stories, but after to create a content, when I'm trying to Publish, appear the message "Failed to save the story". And also, by trying to use one of the templates, appeared the messages: "Unable to Create Story From Template. You are likely be offline". Any tips?

**Comment by ernee** [comment]
Thanks for reaching out about this @nunomura ! 

1) Could you provide screenshots of the two errors and any [browser console errors](https://i.imgur.com/KyLAzgH.png) you might see for each? 

2) Is the site you're working on publicly accessible?

**Comment by nunomura** [comment]
Tks in advance for reach me, Ernee. I've found out the problem. I use a different URL for the Wordpress (farofafa.com.br) and the site (farofafa.cartacapital.com.br). To avoid my former error, I've have to change, for a bit, by keeping the same address, while I publish the stories. So, if someone else face the same situation, here the solution.
And here is my first stories: [http://farofafa.com.br/stories/cabareprive/]

**Comment by ernee** [comment]
@nunomura thanks for following up and providing a solution that worked for your site setup! 

Just to confirm, [in the settings](https://i.imgur.com/MkFLF0E.png): 

The **WordPress Address (URL)** is:  https://farofafa.com.br
The **Site Address (URL)** is: https://farofafa.cartacapital.com.br/

Thanks also for sharing your story!

**Comment by ernee** [comment]
@nunomura just a quick update the stable version of the plugin 1.0.0 has been released. I will close your issue now, but please feel free to reach out to us in our [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/) if you should have further questions.

**Comment by josealmeida-bo** [comment]
Hi @ernee. I'm having the same issue here, but my wordpress address is the same as my site address. I'm able to create and save story when I access my blog through the ip, but when I use the blog subdomain such as blog.mysite.com.br it shows the message "Failed to save the story". Can it be related to be using a subdomain?
I've been having this issue since the beta 2 version, and I've just installed the new release but it didn't solve the problem.

My console shows the following errors when saving the draft:

/wp-json/web-stories/v1/web-story/3698?_locale=user:1 Failed to load resource: the server responded with a status of 403 ()
api-fetch.min.js?ver=8773a93ea0d1278a2eaa147fdb6eb96d:2 POST https://blog.mysite.com.br/wp-json/web-stories/v1/web-story/3698?_locale=user 403

Can you help?

**Comment by ernee** [comment]
@josealmeida-bo thanks for reporting! We've moved support to the [WordPress.org forums](https://wordpress.org/support/plugin/web-stories/), but we'd be happy to investigate this further with you there. Please open [a new support topic](https://wordpress.org/support/plugin/web-stories/#new-post) with the above information and we'll continue troubleshooting with you.
