### ISSUE TITLE
Plugin Class Not Found

### ISSUE THREAD

**Issue by yashanandan** [GoogleForCreators/web-stories-wp#3619]
## Bug Description
I downloaded the plugin zip and uploaded to wordpress. The plugin got installed but when I am trying to activate the plugin it throws this error

`Fatal error: Uncaught Error: Class 'Google\Web_Stories\Plugin' not found in /var/www/html/saasworthy/blog/wp-content/plugins/web-stories/includes/namespace.php:85 Stack trace: #0 /var/www/html/saasworthy/blog/wp-content/plugins/web-stories/web-stories.php(56): require() #1 /var/www/html/saasworthy/blog/wp-admin/includes/plugin.php(2255): include('/var/www/html/s...') #2 /var/www/html/saasworthy/blog/wp-admin/plugins.php(177): plugin_sandbox_scrape('web-stories/web...') #3 {main} thrown in /var/www/html/saasworthy/blog/wp-content/plugins/web-stories/includes/namespace.php on line 85`

## Screenshots

![image](https://user-images.githubusercontent.com/32616535/89147255-be5de000-d573-11ea-84b4-d8278f0f33c3.png)

## Additional Context

- Plugin Version: 1.0.0-beta.1
- Operating System: Cent OS - Linux 3.10.0-1127.8.2.el7.x86_64 x86_64

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for your report!

If you download the plugin straight from GitHub, you will only get the _source_ files, not the final _build_ that includes all JavaScript and PHP files to run the editor. That's why  you get the error about classes not being found.

To prevent this, please download the ready-to-use version from from https://google.github.io/web-stories-wp/beta/

If you want to install the latest master version instead, follow our[ Getting Started guide](https://github.com/google/web-stories-wp/blob/master/docs/getting-started.md) for contributors and the steps needed to _build_ the plugin.

Please also note that we've already updated the messaging to make this more clear.
