### ISSUE TITLE
Recommended Image Size

### ISSUE THREAD

**Issue by axelctv** [GoogleForCreators/web-stories-wp#3624]
## Request

Hi 
my eyes hurt from a lot of information but still have no idea what are the proper  / recommended image sizes we should use .
like for the story background ?  featured image ? 
so 
please what are the recommended image sizes / proportions ? minimum required and max allowed ? 

Thanks

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
Hello @aaronmspelling! The specification for cover images can be [found here](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)). Note the following recommended minimum requirements:

Each poster image should meet the recommended minimum size:
Portrait: 640px x 853px
Landscape: 853px x 640px
Square: 640px x 640px 

Publisher logo images should be at least 96x96 pixels. 

Hope this helps!

**Comment by axelctv** [comment]
thank you 
what about the background image or the featured image for the Web Story ?

**Comment by LuckynaSan** [comment]
The recommendation is to use at least 828 x 1792 sized fullscreen/ background images as mentioned in this [best practices documentation]( https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/?format=stories#images). Cover image in Web Stories is both the poster image and featured image. Featured image sizes should be at least 1200px wide to meet [structured data requirements](https://developers.google.com/search/docs/data-types/article#article_types).

**Comment by axelctv** [comment]
thank you

**Comment by axelctv** [comment]
read all the details you sent so if i would use 828 x 1792  images as background image for my slides 
Portrait: 640px x 853px
Landscape: 853px x 640px
Square: 640px x 640px   for any image i want to use on / in the slides 

1200*728  as feature image ( this is the structured data requested size ) 

and for  publisher logo 96X96  everything should be ok ? 


one more thing ( sorry )  Gutenberg editor or classic editor would be the best to use ? ( of course using the Web Stories beta plugin )

sorry but ...

**Comment by LuckynaSan** [comment]
> read all the details you sent so if i would use 828 x 1792 images as background image for my slides
Portrait: 640px x 853px
Landscape: 853px x 640px
Square: 640px x 640px for any image i want to use on / in the slides
1200*728 as feature image ( this is the structured data requested size )
and for publisher logo 96X96 everything should be ok ?

We recently received some updates about Search Console image size guidelines for Web Stories and there are a few details we are clarifying. We will update you as soon as possible.

Gutenberg allows you to easily [embed your Web Story URL](https://jmp.sh/T5KSHiu) quickly in the same place on the interface. We are considering shortcode support for the classic editor as suggested in #3135.

**Comment by axelctv** [comment]
thank you

**Comment by LuckynaSan** [comment]
Hi @aaronmspelling Following up on your question about image sizes. You shouldn’t have to worry about the correct aspect ratio since the plugin will crop the image to the right aspect ratio, but users should follow the AMP guidelines to use a 3x4 aspect ratio for the featured image to ensure the story's appearance in search is good.  You can download the [beta 2 version](https://google.github.io/web-stories-wp/beta/) of the plugin which will automate resizing the poster-portrait-src images.

These guidelines apply to the cover image. Each poster image should meet the recommended minimium size:

- Portrait: 640px x 853px
- Landscape: 853px x 640px
- Square: 640px x 640px

The recommendation is to use at least 828 x 1792 sized fullscreen/ background images as mentioned in this [best practices documentation](https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/?format=stories#images).

Thanks again for submitting this topic!
