### ISSUE TITLE
Add Templates to the Stories Post Type Admin Dashboard Menu

### ISSUE THREAD

**Issue by ernee** [GoogleForCreators/web-stories-wp#3650]
## Feature Description

Initially requested[ in this issue](https://github.com/google/web-stories-wp/issues/3455), adding templates to the Stories Post Type Admin Dashboard Menu would improve discovery and use:

> The structure seems a bit strange to me, and I would expect templates to be part of the add new also, since that is the normal route in WordPress, or at least the templates should be part of the stories admin menu too, making it directly visible as an option. Normally with a custom post type I would expect add new to be a starting point for creating stories and the "all stories" to give access to the list. It seems that the dashboard tries to combine that in a more visual interface, but then it probably should replace the others, or add the templates too in the menu. And how am I expected to go from the dashboard to viewing stories on the frontend?
> 
> When templates is a way to add new stories based on prefabricated stories, it should in some form be part of the add new story dialogue. Something like: 1. Choose add new. 2. Get to select a template (or a blank canvas) 3. edit the content.
> 
> Anyway, except for missing an option to see stories in the frontend, the dashboard seems pretty complete, so probably most of the time the other menu-items will not be needed. On a system with long response times eliminating steps (page loading) would be helpful.

(@hansschuijff does this capture your request or were there other alternatives we should consider?)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I recommend closing this in favor of #2750, and mentioning this suggestion there.

**Comment by hansschuijff** [comment]
@ernee Yes, that is as far as I was with my suggestion. Mostly templates could be a part by itself, but should imo also be part of the add new flow, making it obvious for those of us that are not aware of the fact that templates is actually another startingpoint for adding new stories, but then based on a template. When the intention is to add a story, probably I would choose add new, expressing my intention to add a new story, and then would like to have the option to select on what template I would base that.

The other thing works too, but expects users to know the alternative workflow. Probably most users would like to start of with a template since that offers some default styling and some inspiration. So add new should respect that probable route and not assume users want to start of with a blank canvas.

I would probably just call the list of templates "Add new" in the menu and make a default empty template as first template, for people who want a blank start. In that way having a separate route without templates is not needed. That route is actually the equivalent of starting with an empty template.

And then the menu-option to templates could be a template maintenance option, offering to update and save a template instead of creating a new story based on a template. Probably mostly the same page, but with different intention.

I don't know if that would be preferable, but it would probably my approach in this. 

Thanks for picking this up.

**Comment by ernee** [comment]
@hansschuijff very valuable feedback. As @swissspidy mentions, it looks like there is an open related issue: https://github.com/google/web-stories-wp/issues/2750. I will close this one and refer to your feedback here for more perspective/ context. Thanks again for raising this!
