### ISSUE TITLE
Shortcode for classic editor

### ISSUE THREAD

**Issue by igarpoor** [GoogleForCreators/web-stories-wp#3686]
## Feature Description

Would be nice to have a simple shortcode to embed stories in posts for those that still use the classic editor and not the block editor.

**Comment by igarpoor** [comment]
Something like this:

```php
add_shortcode('story', 'shortcode_story');

function shortcode_story($atts) {

  if(!isset($atts[0])) return;

  $story_url = esc_attr($atts[0]);

  wp_register_script( 'amp-story-player', 'https://cdn.ampproject.org/amp-story-player-v0.js', [], 'v0', false );
  wp_register_style( 'amp-story-player', 'https://cdn.ampproject.org/amp-story-player-v0.css', [], 'v0' );

  wp_enqueue_style( 'amp-story-player' );
  wp_enqueue_script( 'amp-story-player' );

  $html = '<div class="wp-block-web-stories-embed alignnone"><amp-story-player style="width:360px;height:600px" data-testid="amp-story-player"><a href="'.$story_url.'" style="--story-player-poster:url(\'/wp-content/plugins/web-stories/assets/images/fallback-poster.jpg\')">Read the story</a></amp-story-player></div>';

  return $html;
}
```

**Comment by swissspidy** [comment]
Thanks for your report!

We're already tracking this suggestion in #3135, please follow that issue for any updates.

To give some context, we're currently focusing on block editor integration as that's the default editor in WordPress and offers a vastly superior user experience than shortcodes or widgets.

However, since you've already posted some proof-of-concept code above, nothing stops you from implementing this shortcode on your own site like this.

----

Duplicate of #3135
