### ISSUE TITLE
Stylesheet override when Embedding Story into a post.

### ISSUE THREAD

**Issue by trendland** [GoogleForCreators/web-stories-wp#3731]
## Bug Description

After creating a test story with the plugin, when embedding the code into post, there is some sort of stylesheet override, where my chosen font size and <a> tags are being mixed up with the stylesheet of the story. 

## Expected Behaviour

It should not interfere with current theme stylesheets.

## Screenshots

With the story embedded the fonts and links looks like : 
![Screen Shot 2020-08-07 at 8 21 53 AM](https://user-images.githubusercontent.com/7536142/89645278-70085400-d887-11ea-8754-788c64a42860.jpg)

Without the story embedded the fonts and links looks like: 
![Screen Shot 2020-08-07 at 8 22 30 AM](https://user-images.githubusercontent.com/7536142/89645351-9b8b3e80-d887-11ea-8b8e-3672377bda69.jpg)

## Additional Context

You can see it [live here](https://trendland.com/zaha-hadid-architects-roatan-prospera-residences/
) ( won't leave the story embed more than a day) 

Let me know as I'd love to start integrating the stories into our posts. 
Thank you!

- Plugin Version: 1.0.0-beta.1 
- Operating System: Mac OS 10.15.6 
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Thanks for sharing!

I see the issue on that page, however I don't see how this would be caused by embedding a story. The CSS causing the white hyperlinks is clearly coming from your theme or page builder:
<img width="1680" alt="Screenshot 2020-08-07 at 14 32 34" src="https://user-images.githubusercontent.com/841956/89646419-06566d00-d8bc-11ea-8b01-88b29bf62feb.png">

<img width="1366" alt="Screenshot 2020-08-07 at 14 34 52" src="https://user-images.githubusercontent.com/841956/89646401-00608c00-d8bc-11ea-975d-6f85745a7261.png">

It's worth noting that stories are embedded via an iframe, and iframes cannot affect the style on the rest of the page. And the only CSS we load is https://cdn.ampproject.org/amp-story-player-v0.css, which specifically targets the embedded story (`amp-story-player`) and nothing else.

**Comment by trendland** [comment]
Hi Pascal, 
Thanks for the rapid feedback! 
Just looked into it and it seemed to have fixed itself. 
Maybe it was some caching with the WP preview ? But it seems now to be embedded without any issues and fonts/links are back to normal. 

Thanks again for the plugin, it starting to look great. Will report if new bugs appear.
