### ISSUE TITLE
Navigating From Shapes To Media Shows Unsplash Display

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#4050]
Tested in #4012 - Win10/Chrome

- open/create story
- select Shapes tab
- select Media tab
- note that Unsplash info now appears

Video: https://drive.google.com/file/d/12tCWIm_O3mT_WsciZ3ADMHbsVQFBKLiO/view
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/40b9932a-d1a6-4c5a-abdb-0f0f0e5663c8)

**Comment by swissspidy** [comment]
@csossi What exactly is the issue here?

You are navigating from the "Upload" tab to "Shapes" and then to the "3P Media" (aka Unsplash) tab.
In other words, you are navigating from the 1st tab to the 4th tab and then to the 2nd one.

The Unsplash tab is visible because the feature flag is active in https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=web-stories-experiments (at the very bottom)

**Comment by swissspidy** [comment]
Note that for a true representation of the beta 2 release you'd want to disable all feature flags on https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=web-stories-experiments for testing

**Comment by csossi** [comment]
ok, thanks @swissspidy
