### ISSUE TITLE
Uploaded Video Using Cached Poster Image

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4064]
## Bug Description
A different video is loading on to the canvas even though it is not in the media library. 

## Expected Behaviour
The video uploaded on media library should be in editor media library without interference from outside video files and load on to canvas appropriately.

## Steps to Reproduce

- Upload video in media library
- Create new story
- Drag video onto canvas
- A different video that isn't in the library populates. After a few seconds the true video loads. 

Screenshot of current media library: https://jmp.sh/Q8CESem 
Recording of the issue: https://recordit.co/vSfOVbB0tA

- Plugin Version: from PR #4039 
- Operating System: macOS Mojave 13-inch v. 10.14.6 
- Browser: Safari v. 13.1.2.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@LuckynaSan is this happening with all videos or just this particular video?

**Comment by swissspidy** [comment]
Also, it's not clear to me which of the items in your media library corresponds to the video you're inserting in the editor 🤔

**Comment by LuckynaSan** [comment]
> is this happening with all videos or just this particular video?

It doesn't seem specific to the video. [Here](https://recordit.co/awCnGbVsVV) is another example. 

> Also, it's not clear to me which of the items in your media library corresponds to the video you're inserting in the editor 🤔

The video it's inserting doesn't existing in my media library. I've tried [emptying out my media library ](https://jmp.sh/f2xTUJf)so that the editor media library doesn't pull from there.

**Comment by swissspidy** [comment]
So I was debugging this together with @LuckynaSan and I think I found the issue(s).

The first, smaller issue noticed here is that the media library in the editor does not refresh when uploading media via the WordPress media modal (can be reached via the 'Upload' button). I think **#1201** covers that bug.

The main issue reported here is a bit of an edge case, but can be reproduced as follows

Prerequisites:

1. it's easiest to reproduce when the media library is completely empty.
1. two videos, `a.mp4` and `b.mp4`

First, upload `a.mp4` to the site. It does not matter how the video is uploaded. The important part is that you then head to the editor and insert the video in a new story. **This will cause the story editor to generate a poster image for the video in the background**. The poster image will be named `image.png`  and it will be added to the video in the library on the left-hand side.

Next, head to the WordPress media library at `/wp-admin/upload.php`. You should see the poster image of the video with an `a.mp4` overlay on it. Delete the video.

After that, ideally staying on `/wp-admin/upload.php`, upload `b.mp4`. Once done, head to the editor and insert the video in a new story. **This will cause the story editor to generate a poster image for the video in the background**. The poster image will be named `image.png`  and it will be added to the video in the library on the left-hand side.

Now you might see where I'm getting at...

Because in the first part the browser has already displayed the video poster (`image.png`), and the new poster has the same file name, the browser will display a cached version of that poster.

The issue goes away with a hard refresh to clear the cache.

The issue could be prevented from happening in the first place by using more unique file names for the poster.

Coincidentally, I've suggested optimizing poster image names in #3228 a while ago. While I did so more for aesthetic reasons, it could nicely fix this bug too.

So we can probably fix this issue in favor of #3228

**Comment by swissspidy** [comment]
Closing in favor of #3228
