### ISSUE TITLE
Add Access Levels - Admins, Editor, Author, Contributor, Subscriber

### ISSUE THREAD

**Issue by mechiragjain** [GoogleForCreators/web-stories-wp#4102]
## Bug Description

Create Access Levels and restrict different level of users to access this plugin. You can give a Setting section in which Admin of the WordPress Website can give access of this plugin to specific level of users. It is very important to add this level of security or access so that everyone should have the right to edit the templates.

## Expected Behaviour

One can visit the Setting Section of Web Stories Plugin in which the admin can choose the levels who can access this plugin.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@mechiragjain Hello! Thank you for submitting your topic. 
If you are an administrator you can edit user access levels in WordPress > [Users settings](https://jmp.sh/NNKot73).
Subscribers have no access to the plugin.
Contributors can create new stories and preview it, but cannot publish it. User will not be able to edit an existing story either.
Authors can create new stories, preview, and publish it. User will not be able to edit an existing story.
Editors can create new stories, preview, publish, and edit existing stories (preview and publish). 

Hope this helps.

**Comment by mechiragjain** [comment]
But it should be changeable then it will make work easy for the administrator.

**Comment by swissspidy** [comment]
I see your point, but adding such functionality is not something we are really considering. Especially since that's not really how user roles in WordPress are intended.

In the future, you can use plugins like https://wordpress.org/plugins/members/ to change which user roles can edit stories. But we're not going to add a feature like this to the Web Stories WordPress plugin in the foreseeable future.
