### ISSUE TITLE
Jittering items in media library

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4311]
## Bug Description

As mentioned on Slack, I am experiencing some jittering in the media library at certain window sizes. Happens for me when it’s around 900px tall.

## Expected Behaviour

No jittering.

## Steps to Reproduce

Resize browser to try to reproduce this

## Screenshots

https://cloudup.com/cTN7CkWDnpo

## Additional Context

- Plugin Version: beta 2 / current `main`
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by ezxyz** [comment]
Note: I wasn't able to reproduce this with only images.

I was however, able to reproduce when there was one video in the gallery, without having to resize: See gif: ![jitter.gif](https://images.zenhubusercontent.com/598a6729f8b79f8376e26cbc/f93230b7-3456-4da5-8308-16d563e2524f)

It's possible this is an issue with the cover image.

**Comment by ezxyz** [comment]
However I can't reproduce this everytime ( I refreshed the page and it went away )

**Comment by ezxyz** [comment]
After some investigation, this seems to occur because the scrollbar seems to appear and reappear very quickly when the gallery is a certain size. (Normally when there is just enough images to start overflowing). 

A proposed solution is to add a persistent scrollbar even when there is no overflow. See PR #4378 

I sent an email to @samitron7 and we'll see whether this is a acceptable solution UX wise.

**Comment by diegovar** [comment]
Another similar issue that occurs is when resizing the window horizontally. At a certain point the media gallery starts becoming smaller, and jittering occurs, because it triggers a bug in react-photo-gallery. I believe that setting min-width: 360px; in the Area component in assets/src/edit-story/app/layout/index.js fixes the issue and is the easiest short term solution for this, with the caveat that resizing the window to be very small results in the canvas sort of sliding behind the media gallery. WDYT @swissspidy ?

You can try out https://github.com/google/web-stories-wp/pull/4438 in QA to see what I mean.

**Comment by swissspidy** [comment]
@diegovar Is https://github.com/neptunian/react-photo-gallery/pull/184 the bug you are referring to? If so, we should just patch this in our repo (using `npx patch-package` that's trivial). 

I don't think this caveat is acceptable because it breaks the editor on iPad-sized screens, and we'd want the editor to work on that screen size.

Without #4438:

<img width="490" alt="Screenshot 2020-09-10 at 19 41 07" src="https://user-images.githubusercontent.com/841956/92774667-fee42100-f39d-11ea-8f9f-5a3d26a1f64b.png">


With #4438 applied:

<img width="474" alt="Screenshot 2020-09-10 at 19 41 15" src="https://user-images.githubusercontent.com/841956/92774713-073c5c00-f39e-11ea-8d2f-593915305817.png">

**Comment by diegovar** [comment]
Ah interesting, I didn't know of https://github.com/neptunian/react-photo-gallery/pull/184 and patch-package.

I've done that instead, can you take a look at https://github.com/google/web-stories-wp/pull/4438 ?

**Comment by swissspidy** [comment]
This needs QA or at least UAT before closing.
