### ISSUE TITLE
Refactor media provider to use reducers 

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#435]
## Feature Description

Current the media provider uses [5 calls](https://github.com/google/web-stories-wp/blob/aaba6414fbd23680bba7f929d7e51dc0665a8572/assets/src/edit-story/app/media/mediaProvider.js#L38-L42) to `useState`. As this media library adds more complex features, such as #23 #231 and #228 ,more data will be stored for this component. We should use reducers, add tests and design a data model here.

**Comment by merapi** [comment]
After my investigation it looks like this ticket shouldn't have the [Good First Issue] label 😉, some problems that I found:

On page load, every filter change and search, it will call `/wp-json/wp/v2/media?per_page=100&_locale=user` twice.
When you look at https://github.com/google/web-stories-wp/blob/c29f388b8135b9b20e061d036c01222f8fa10cbb/assets/src/edit-story/components/library/panes/media/mediaPane.js#L117 you might be tempted to change it to `useEffect(loadMedia, []);` so it will run only once, on mount. It will fix the initial load (just one request) but then both: filter and search will no longer work.

The second problem is race conditions when you change the filters (based on network/server/number of items to load):
https://share.getcloudapp.com/6quBQ8KL

Refactoring to `useReducer` is in progress, it's not trivial since this is the main part of the app that is dealing with async side-effects and now we need to handle them in `useReducer`, soon I will push some PoC code.

Any feedback is highly appreciated (async reducers in context), dealing with them in `redux-saga` was a breeze, here it's more complicated and harder to debug.

It might be a good place to introduce small wrapper to `useReducer` that will enable us to use any middleware (thunks, logging), something like https://github.com/shiningjason/react-enhanced-reducer-hook

**Comment by obetomuniz** [comment]
@merapi Will wait for your PoC for more insights, but did you try `useEffect(loadMedia, [!media.length, searchTerm, mediaType]);` to fix the first problem? Use `searchTerm` directly to handle http requests can be dangerous, we need to apply a throttle/debounce on typing depending on the UX proposed.

About race conditions on requests, I have some initial suggestions: 

1) cancelable request using some defer pattern (e.g. debouncing, or even better, AbortController, but it is not supported everywhere) 
2) use different objects keys to store the data based on type (image|video)

Hope that some of these tips can give you some guidance, I will check it again as soon as you push the PoC 😄 👍

**Comment by spacedmonkey** [comment]
According to the design in figma, search should not start until the user hits enter, which would massively help. 

<img width="1270" alt="Screenshot 2020-03-09 at 10 32 42" src="https://user-images.githubusercontent.com/237508/76205061-6e136980-61f1-11ea-8487-511e2bd178fc.png">

Worth noting that the current version was written in PoC stage. 

Also 
> but did you try useEffect(loadMedia, [!media.length, searchTerm, mediaType]); to fix the first problem

What if there are on files in the media library, meaning that media.length would always be 0, wouldn't the result in the loop forever?

**Comment by merapi** [comment]
> According to the design in figma, search should not start until the user hits enter,

Will add search while typing (with ~200ms debounce) harm this input? I mean, you type something and nothing happens, there is no submit/search button. In other parts of the editor, actions are triggered onChange e.g. size&position inputs. @samitron7

**Comment by merapi** [comment]
> 1. cancelable request using some defer pattern (e.g. debouncing, or even better, AbortController, but it is not supported everywhere)

Right now I compare the response with the current state and in case of type/term mismatch - discard the response. AbortController would be a nice addition but I think in practice it doesn't do much (it just discards the response, is there any byte saved here?)

Refactor made here: https://github.com/google/web-stories-wp/pull/510
