### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by haroldhillford** [GoogleForCreators/web-stories-wp#4407]
TypeError: Object.fromEntries is not a function
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in div
    in layout__Area
    in section
    in layout__Editor
    in wU
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in LL
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by swissspidy** [comment]
Hi there, which browser are you using?

**Comment by swissspidy** [comment]
(Note that browsers like Internet Explorer or Safari 11 are not supported right now)

**Comment by swissspidy** [comment]
@haroldhillford I am closing this issue since there's been no reply from you so far. Just note that we support only the latest versions of each major browser (e.g. Safari, Edge, Firefox, Chrome), but not Internet Explorer. If you still encounter this issue with one of these browsers, please let us know here and we can reopen.
