### ISSUE TITLE
a11y: template detail page - make "selected/previewed" page distinguishable from keyboard focus state

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#4418]
## Feature Description

See image - the selected page (first) and keyboard focus page (third) are too similar. 

![image](https://user-images.githubusercontent.com/13389997/92621079-62ccf380-f291-11ea-9ac0-1ff3857c6e3e.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
So since the creation of this, we've updated things a bit. Now it looks like this. 

There's no "active" indicator anymore - possibly a regression. Do we want that back? Is this visually fine? 

@o-fernandez  thoughts when you get a second - can repurpose the ticket and just reintroduce an active state - can just do the same thing that's done in the grid view on the editor (though that still won't help too much for colorblind). 
 
https://user-images.githubusercontent.com/10720454/128909052-f94a0272-b3b2-421e-9c34-b0dc0541a302.mp4

**Comment by o-fernandez** [comment]
I think this is OK for now, actually. If we get complains that people want to know the currently selected page, we can revisit this.
