### ISSUE TITLE
Right Click Menus: Add Duplicate Element Action

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4616]
## User Request

User requested an icon to duplicate elements or text like the "duplicate page" icon underneath the canvas.

## Feature Description 
- Adding a "duplicate" action into right click menus 
- Creating a new right click menu for when multiple elements are selected and giving that menu  the "duplicate" action as well as "Clear Styles" action. 

## Additional Context

>The ability to duplicate an element within the story. ie text box. Just like you duplicate the entire story slide, same icon but to duplicate an item within a slide.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

- Ability to duplicate elements via right click menu
- New right click menu for when multiple elements are selected that has the ability to duplicate elements. 

## Implementation Brief

Initially this feature request included the ability to "Clear Styles"- pulling that out to be separate and avoid scope creep.

**Comment by swissspidy** [comment]
This button does not exist yet, but it would be more easily possible thanks to the Quick Action Menu.

@o-fernandez Perhaps something to consider there?

**Comment by o-fernandez** [comment]
Agree! I think that adding duplicate element to the quick actions menu is likely very beneficial and hopefully not difficult to implement. @BrittanyIRL thoughts?

**Comment by BrittanyIRL** [comment]
I believe this is functionality for the right click (context) menus that we bumped to 1.10

**Comment by o-fernandez** [comment]
Oh got it, I'm still not sure what goes in quick actions vs. right click menu. Thanks for checking! We can track this as part of the right click menu.

**Comment by BrittanyIRL** [comment]
'Duplicate' got axed from the quick action menus in discussion with design because it seemed redundant since you can just `ctrl+c` and duplicate? We do have copy styles supported in quick menus. 
![Screen Shot 2021-10-20 at 4 49 06 PM](https://user-images.githubusercontent.com/10720454/138187788-6c8fd501-1dcf-4dee-9bc4-a8ece26e21e4.png)

Is `duplicate element` something we want to restore to the quick action menus? 🤔  

@aaskedall @agingoldseco @choumx

**Comment by BrittanyIRL** [comment]
Following up on this, thoughts on the above? @gajasinski @agingoldseco

**Comment by agingoldseco** [comment]
One of my most-used keyboard shortcuts in many design platforms is the ability to hold down Option while dragging an element to duplicate it. If people are duplicating a bunch of things, it's quicker and smoother than pressing Ctrl+C / Ctrl+V repeatedly—perhaps we can consider adding that as a keyboard shortcut? I don't think it needs to take up space on the quick actions menu, but I think it deserves a place on the right click menu if nothing else.

**Comment by BrittanyIRL** [comment]
This is probably really naive, i'm just trying to get on your level of how holding down option and dragging to duplicate is different from here where you can hold down shift? And in that how adding it to the right click menu is helping differently? 

![selective copypaste](https://user-images.githubusercontent.com/10720454/140837065-92e0fcc7-fe9a-4108-af56-63f0e8322dc1.gif)
![drag and copypaste](https://user-images.githubusercontent.com/10720454/140837067-a4962197-e2bd-4c7d-9da6-3ed04ef993fc.gif)

**Comment by BrittanyIRL** [comment]
After syncing with @agingoldseco on this today about how to move forward, our plan is to add in a right click menu option as well as a keyboard shortcut that allows for duplicating on drag. 

So if you have multiple elements selected and you right click you'd see the option to duplicate the group. This would be a new right click context menu since right now all of the menus are based on 1 element being selected and the options are done by type. This then begs the question of do we want anything else to be available on these for bulk use? 
I could see 'clear style' being applicable but haven't noticed anything else that would remain evergreen. 

In addition to a new right click option a hotkey will also get added that when `option` is pressed and the cursor is dragging all of those elements are copied - this mirrors illustrator.

@agingoldseco can you confirm the above is right? Then I'll update the ticket description and title properly so we can plan to work on it.

**Comment by gajasinski** [comment]
SG

**Comment by dreamofabear** [comment]
IMO let's start with adding "duplicate" to the right-click menu. 

> One of my most-used keyboard shortcuts in many design platforms is the ability to hold down Option while dragging an element to duplicate it.

I can see how this would be a common workflow in Figma but having trouble imagining the same in our plugin. 

More broadly, I'd be very wary about importing UX patterns from Figma/Photoshop. That was one of our original design mistakes (as attested to by Paul/Sam) which we're still paying for today -- our target users are not visual designers and we've seen consistent feedback and UXR that affirms that.

**Comment by gajasinski** [comment]
+1 - i might center us on interactions similar to something like WIX or Squarespace and less on Figma/Photoshop

**Comment by agingoldseco** [comment]
@BrittanyIRL Yes, that was all correct! 

But everyone is also making sense here, I'm good with starting with adding it to the right click menu so there's a button for anyone confused by keyboard shortcuts. Option + drag I just find to be a very smooth interaction I use like crazy in designing anything, but maybe I am just used to it. It would be more for power-users.

**Comment by csossi** [comment]
Verified in QA
