### ISSUE TITLE
Library: Avoid rendering inactive tabs

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4634]
## Bug Description

When opening the editor, we already load all text sets and templates (page layouts) despite those tabs not being open by default. That's **6MB** of data.

As per #4433, same goes for inactive media tabs. There's not much detail there but seems like a good performance win.

This also causes issues with tests. See #5945

## Expected Behaviour

Text sets and page layout chunks should only be loaded the first time they're being opened.

## Steps to Reproduce

1. Open Network tab in dev tools
1. Open the editor
2. Notice that all text sets and all templates are being loaded

## Additional Context

- Plugin Version: 1.3.0
- WordPress Version: 5.6
- Operating System: macOS Catalina
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
Bumping to P4. It's not obvious that mutating the DOM to remove hidden media tabs is a performance win.

**Comment by swissspidy** [comment]
> Bumping to P4. It's not obvious that mutating the DOM to remove hidden media tabs is a performance win.

It's not about mutating the DOM.

It's about not actually rendering (= executing) React components that are not really active in the first place.

**Comment by swissspidy** [comment]
@zachhale @BrittanyIRL bumping the prio on this one a bit, hope it's OK

**Comment by BrittanyIRL** [comment]
@swissspidy thanks, I agree! given how much time Zach had to spend battling issues that stem from rendering inactive tabs I totally agree. If we can spend the time addressing this now it'll save us time down the road. 

@barklund with your refactor of panels, is there anything that we should know about before addressing this issue or is the general structure kept the same?

**Comment by barklund** [comment]
I'm all for this in terms of performance. The only reason that we're doing, what we're currently doing, is because of a11y. WCAG strongly recommends [rendering inactive tabs in the DOM](https://www.w3.org/TR/wai-aria-practices/#kbd_selection_follows_focus) unless there's a page load or heavy performance penalties associated. And in that case, they also recommend switching tab selection from _selection-follows-focus_ to _manual activation_ (so arrow keys to move focus, <kbd>enter</kbd> or <kbd>space</kbd> to activate)

However, I think we're in a unique opportunity, where we'd diverge from these recommendations and mix them as follows:

1. Remove inactive tab content, but keep the `role="tabpanel"` wrapper, so the tab `aria-controls` something valid.
2. Keep _selection-follows-focus_, as tabs are rendered very quickly when selected and there's no noticeable delay nor any penalty for quickly switching between numerous tabs-

We can however only do 2) above as long as we can promise it. If we start to notice that switching from the media library to the shape library comes with a performance penalty when switching "over" the text library (because of text sets) – or any similar delay penalty – we must switch to _manual activation_.

**Comment by barklund** [comment]
Actually implementing this is super easy and very straight-forward - it's not a technical concern, only a UX/a11y one.

**Comment by BrittanyIRL** [comment]
> Actually implementing this is super easy and very straight-forward - it's not a technical concern, only a UX/a11y one.

Totally, thanks for the detailed a11y guidelines too on this set up! I probably over-estimated this but the focusing of the panels can be a little tricky so I thought I'd err on the side of extra time allocated.

**Comment by csossi** [comment]
Verified in QA
