### ISSUE TITLE
Stories permalink redirect wrong

### ISSUE THREAD

**Issue by Bernietorras** [GoogleForCreators/web-stories-wp#4645]
## Bug Description

In the last update made the URLs of the stories are broken. 

It used to be this URL:

https://mesasescritorio.com/stories/la-mesa-de-joan-boluda/

With the last update, the plugin redirected me to this URL for that story:

https://mesasescritorio.com/stories/la-mesa-de-joan-boluda/la-mesa-de-joan-boluda/

I've gone back to the previous version and made a redirection to work with the new slug /web-stories/

Once I have recovered the previous plugin and the 301 redirect in the created stories, it now works for me:
https://mesasescritorio.com/web-stories/la-mesa-de-joan-boluda/

For SEO it's not good to change the slug /stories/ for /web-stories/ 

Is better to let the user decide which slug he wants to put.

The Editor Settings section has also disappeared.

## Expected Behaviour

The plugin should not redirect old stories from /stories/story/ to /stories/story/story/

The plugin should redirect the old stories from /stories/story/ to /web-stories/story/

## Steps to Reproduce

Update the plugin and try to access the URL of the stories created. It makes you that strange redirection and results in a 404 error.

## Additional Context

- Plugin Version: 1.0.0 - Release Date: September 22nd, 2020. ""Initial stable release.""
- Operating System: Win 10
- Browser: Chrome 85

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi @Bernietorras 

Thanks for your report!

For our initial stable release, we indeed changed the URLs from `/stories/<storyname>` to `/web-stories/<storyname>`. We _did_ include redirects for this, so that `/stories/<storyname>` will automatically point to `/web-stories/<storyname>`.

Now, I am very curious to know why this redirect was broken for you. Could you perhaps send us your Site Health info (Tools -> Site Health -> Info -> Copy to clipboard) so we can try to reproduce this?

> Once I have recovered the previous plugin and the 301 redirect in the created stories, it now works for me

I highly recommend not going back to the previous plugin, and instead stay on 1.0.0.

To fix redirects manually for now you could add them in `.htaccess` or use a plugin like [Redirection](https://wordpress.org/plugins/redirection/).

> Is better to let the user decide which slug he wants to put.

We are considering this in #4459, please follow that ticket for any update on this enhancement.

> The Editor Settings section has also disappeared.

I cannot reproduce this. Mind sharing a screenshot of your Stories Dashboard?

**Comment by Bernietorras** [comment]
Sorry I could fix the problem, I deleted and reinstalled the plugin.
