### ISSUE TITLE
TypeError: Cannot read property 'r' of undefined

### ISSUE THREAD

**Issue by JOHNTHEFRU** [GoogleForCreators/web-stories-wp#4647]
TypeError: Cannot read property 'r' of undefined
    in PresetPanel
    in ColorPresetPanel
    in Unknown
    in form
    in designPanel__Form
    in DesignPanel
    in DesignPanels
    in div
    in designInspector__TopPanels
    in div
    in designInspector__Wrapper
    in DesignInspector
    in div
    in inspectorContent__InspectorPane
    in section
    in inspectorContent__InspectorPanes
    in Inspector
    in div
    in inspectorLayout__InspectorContainer
    in section
    in inspectorLayout__Layout
    in InspectorLayout
    in div
    in dropTarget__Content
    in Unknown
    in div
    in dropTarget__DropTargetComponent
    in UploadDropTarget
    in Unknown
    in InspectorProvider
    in ZG
    in hH
    in div
    in layout__InspectorArea
    in Unknown
    in RichTextProvider
    in Unknown
    in UnitsProvider
    in Unknown
    in CanvasProvider
    in Workspace
    in section
    in layout__Editor
    in sZ
    in Unknown
    in DropTargetsProvider
    in Unknown
    in TransformProvider
    in Unknown
    in MediaProvider
    in Unknown
    in FontProvider
    in Unknown
    in StoryProvider
    in Unknown
    in SnackbarProvider
    in Unknown
    in HistoryProvider
    in Unknown
    in Media3pApiProvider
    in Unknown
    in APIProvider
    in Unknown
    in ConfigProvider
    in hH
    in ThemeProvider
    in StyleSheetManager
    in App
    in FlagsProvider

**Comment by ernee** [comment]
@JOHNTHEFRU thanks for reporting! We're moving support for the Web Stories plugin to the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/).

Could you open [a new topic there](https://wordpress.org/support/plugin/web-stories/#new-post) and share the error and what was the last action taken before the error displayed? I will close your issue here, but we'd be happy to assist you in the forums.
