### ISSUE TITLE
Landscape / Fullscreen / Desktop Support

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#4652]
## Feature Description

User requested:

1. Support full bleed view for desktop or landscape format when mobile device is rotated. If it will be enabled, it means we can also upload image in landscape format into editor dashboard.
Reference: https://amp.dev/documentation/examples/style-layout/desktop_and_landscape_mode_support/

2. Support full screen in pop up view to create full immersive experience, both in desktop and mobile.
Example: https://notesfromaleppo.today/
Please click to one of episodes to see the pop up full screen view.

6. Another examples:
https://www.nytimes.com/interactive/2017/12/21/world/asia/how-the-rohingya-escaped.html
https://www.washingtonpost.com/graphics/world/2020/04/11/meet-health-care-workers-spearheading-philippiness-fight-against-coronavirus/

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by jonnyvpc** [comment]
Any updates on who is working on this issue? Also, is the wordpress plugin going to support this feature?

**Comment by swissspidy** [comment]
@joncreative Excellent question. Let me try to provide a thorough answer to give some context on this ticket.

This ticket here is to track this possible enhancement to the Web Stories for WordPress plugin to support landscape/fullscreen/desktop-sized story creation. Now, our immediate/current focus is on making the creation of smartphone-targeted stories as great as possible. As such, this ticket here is _not_ a priority at the moment and I cannot give you any update for it. This does _not_ mean we'll _never_ implement it, though.

With that said, we'd love to hear more about your goals / use case with such a feature, so we can better understand our users' needs and re-prioritize issues if needed.

**Comment by jonnyvpc** [comment]
Swiss that is a very clear answer and thank you as well! I hope this is not too long-winded but here goes team:

**Responsive including Desktop**
What we'd like to do is use one creation tool in producing web stories, that is going to flex (adapt) to both desktop, mobile and hopefully tablet viewports. This would help with users whom also are on desktop when viewing our work,  The web stories style is an engaging new way to immerse people into our stories (portfolio pieces). 

**Responsive Examples**
I really admire your teams work. Paul Bakaus has been making a most excellent presentation on web stories power, roi and web uses for various businesses. Enjoying it. A company, which is a great use-case for the device-agnostic approach (responsive) is Input magazine

Link to input magazine:
[https://www.inputmag.com/design/people-are-going-wild-with-custom-ios-14-homescreens](https://www.inputmag.com/design/people-are-going-wild-with-custom-ios-14-homescreens)

**Currently satisfied**
Current wp plugin is great! In fact can already do things like Vice on it from what I am reading:

vice example:
(https://www.vice.com/stories/how-to-deal-with-nighttime-anxiety/)

Doubt my use-case is very popular at the moment. But it could be a really big feature for brands like Vogue, or Gucci or others that are using 3rd party platforms like Instagram to give story-like immersive experiences for their customers.  Web stories are going to be huge in 2021, no doubt.

Well, that is the use-case not at all in a sentence or two. But wanted to fully illustrate the need in case there are any other folks like me whom may have users that are device-agnostic. 

Thanks in advance for your insight Swiss, Lucky, O-Fernand and Team😎

**Comment by pawelslabiak** [comment]
@swissspidy, we'd love to see this enhancement bumped up in priority. 

Web stories are a format with great potential. And the Web Stories for WordPress plugin makes this format available to individual creators and organizations that may have shoestring communications operations. I'd like to advocate a little for bringing full-screen support to this neat plugin.

In our case, half the audience views our site on desktop. Anecdotally, it seems that what device our visitors are on has some generational and occupational correlates, although we have not studied this so we cannot say for sure. Still, having web stories be as immersive for desktop visitors as it is for mobile visitors would create a more inclusive experience.

If similar conditions are true for major publishers then the fact that such publishers create stories with full-screen support makes more than just aesthetic sense—doing otherwise would risk offering a downgraded experience to important segments of their audience.

The same is likely true for myriad smaller organizations, including non-profits, public institutions, and research centers whose key audiences may be divided between well established people and up-and-coming digital natives. In all such cases, landscape support would mean that creators can produce better experiences for the entirety of their audiences, regardless of device.

Many thanks for all the great work already done to make this rich format available without the price tags demanded by proprietary media services. Looking forward to see how this product matures and improves.

**Comment by brianpetro** [comment]
Hi, to hopefully add some priority to this, I'd like to share that the [best practices documentation](https://developers.google.com/search/docs/advanced/appearance/web-stories-creation-best-practices#seo) suggests "Add support for landscape displays" under the SEO section. The plugin feels incomplete, seemingly by Google's own standards, without this feature.

**Comment by ShaneSheppard** [comment]
Is this still being worked on?
As I would like to give the full desktop experience as well as mobile via the WordPress Plugin...

**Comment by mxbclang** [comment]
@ShaneSheppard Thanks for getting in touch. At the moment, a desktop experience for Web Stories is not a priority, though that does not mean that it will never happen. We'll of course update this issue if things change.

**Comment by mattkeys** [comment]
I will add that we are also looking for this desktop experience. We've evaluated a number of tools and none seem to support it. Our users are consuming content from a mix of devices and resolutions and we want to provide the right experience to each device. We've seen beautiful full bleed desktop web stories, we just need a way to create them without having to go with a full custom development solution.

**Comment by swissspidy** [comment]
No, it's no such indicator. As you can see from our latest releases and our roadmap we're still maintaining this plugin and adding lots of new features every month.

I am simply cleaning up the backlog a bit right now because we have a lot of older tickets without traction cluttering it.

This ticket here is not a priority at the moment, since our focus is still on mobile experiences.

When we get to it, we can simply reopen it again.

**Comment by mohsinr** [comment]
I just wanted to add a comment that reason for closing this issue is that focus is on Mobile Story experience but does not landscape on Mobile part of the Mobile experience? As if we have stories with images which look good on Landscape, it will be great if we can view our web story on Mobile in landscape mode.

**Comment by swissspidy** [comment]
To clarify, the current focus is on mobile consumption _in portrait mode_

**Comment by ConchiGil** [comment]
Hi! First of all, thank you so much for the great WP plugging. It is awesome! It opens wide opportunities for storytelling. 
I understand for sure your priorities for cell, but I just wanted to second the implementation of this Desktop/landscape mode feature. 

2 REASONS: 

1. In our case, 51% of our visits are desktops, 49% mobiles, and 1 laptop. 
Since our mobile audience is growing, I thought it is an incredible chance for us to implement Google Web Stories, but we still cannot forget our 51% desktop users, and we want to give all of them the same "immersive experience feeling." So far the immersive experience for desktop,  even though you can open it, is kind of lost. 
Some people might want to cover all. Otherwise, they forget about it. 

2. Even though we could program it in AMP (html*css) to get the desktop version, some companies give up the idea because of a lack of human resources, lack of developers, and lack of time. Not all companies have re resources to create a professional content daily programming from scratch.
Plugins like yours make everything so much easier for content creators to build stories and news with such a great experience. 


1. QUESTION 
I assume these examples are done from scratch in HTML, CSS, and AMP frame code?

https://www.washingtonpost.com/world/interactive/2022/ukraine-occupied-life-photos/
https://www.washingtonpost.com/graphics/2019/world/amp-stories/notre-dame-fire/

I understand that this request requires a lot of effort for developers to achieve and might not be a priority, but it is worthy to rethink about the idea.
