### ISSUE TITLE
Inconsistent canonical URL and other URL metadata

### ISSUE THREAD

**Issue by cramforce** [GoogleForCreators/web-stories-wp#4679]
See 
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwp.stories.google%2Fstories%2Fintro-to-web-stories-storytime%2F

All URLs should be the same and avoid redirects.

**Comment by swissspidy** [comment]
[Intro to Web Stories](https://wp.stories.google/stories/intro-to-web-stories-storytime/)

<img width="547" alt="Screenshot 2020-09-24 at 23 09 51" src="https://user-images.githubusercontent.com/841956/94200664-0ede2380-febb-11ea-85be-12359dcc9b85.png">
<img width="539" alt="Screenshot 2020-09-24 at 23 10 01" src="https://user-images.githubusercontent.com/841956/94200682-143b6e00-febb-11ea-8f47-5cde528cb69e.png">

[Creating a Web Story in less than 5 Minutes](https://wp.stories.google/stories/creating-a-web-story-in-less-than-5-minutes-storytime/)

<img width="546" alt="Screenshot 2020-09-24 at 23 11 01" src="https://user-images.githubusercontent.com/841956/94200776-4056ef00-febb-11ea-8bff-69e16fd8fa4d.png">
<img width="530" alt="Screenshot 2020-09-24 at 23 11 59" src="https://user-images.githubusercontent.com/841956/94200824-5b296380-febb-11ea-8523-de99c04c8dc0.png">

[10 Web Stories & What's Great About Them](https://wp.stories.google/stories/10-web-stories-and-whats-great-about-them-storytime/)

<img width="555" alt="Screenshot 2020-09-24 at 23 12 27" src="https://user-images.githubusercontent.com/841956/94200856-6c727000-febb-11ea-9255-239903820be4.png">
<img width="538" alt="Screenshot 2020-09-24 at 23 12 40" src="https://user-images.githubusercontent.com/841956/94200880-72685100-febb-11ea-819f-cfefaceaf51f.png">

---

Rich Results Test looks good for all stories too.

**Comment by cramforce** [comment]
I think @pbakaus might have fixed this manually. Do you have a more vanilla Story published from the plugin?

**Comment by swissspidy** [comment]
Ah, your issue was not about these stories but the plugin's output in general.

Correct, _I_ just fixed the above stories manually, as these are sort of special and copied from their actual location and modified using a script. That script broke the URLs and metadata.

The actual story as published from the plugin live e.g. here: https://stories-labs.dev/webcreators/web-stories/intro-to-web-stories-storytime/

That's all default output, no manual fixes:

<img width="538" alt="Screenshot 2020-09-24 at 23 54 32" src="https://user-images.githubusercontent.com/841956/94204302-4c45af80-fec1-11ea-8321-3ae6437dac49.png">

<img width="1033" alt="Screenshot 2020-09-24 at 23 54 50" src="https://user-images.githubusercontent.com/841956/94204325-57004480-fec1-11ea-93f0-930943241f80.png">

<img width="811" alt="Screenshot 2020-09-24 at 23 55 32" src="https://user-images.githubusercontent.com/841956/94204383-6f705f00-fec1-11ea-8a1e-80eadb6c8a3b.png">


If you find any issues there please let me know.

**Comment by cramforce** [comment]
Amaze

**Comment by pbakaus** [comment]
thank you for looking into this Pascal! Looks like a false alarm for the plugin then!
