### ISSUE TITLE
1px Minimum Height & Width when Rendering Stories in Editor

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#4722]
## Bug Description
Right now if you have a shape with 1px height or width in story space, it becomes < 1px when interpreted into screen space. This causes the browser to paint it inconsistently.

## Expected Behaviour
1px height or width lines should render consistently on the editor canvas

## Steps to Reproduce
Create a 1px by 300px square in the editor. Copy and paste it several times. you'll see that not all the squares render consistently

## Screenshots

![Screen Shot 2020-09-28 at 10.59.07 AM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/1cb73a7c-1fd5-499e-8085-2e9c6cbbd2dd)

## Additional Context
NA

- Plugin Version: 1.0.0
- Operating System: macOS Mojave
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1px height or width rectangles render consistently in editor.

## Implementation Brief

Maintain a minimum of 1px height or width when interpreting story space into screen space.

**Comment by barklund** [comment]
@swissspidy (CC @dvoytenko) how about this:

If a rectangular shape is ever 1px in either dimension, instead of converting the value to some percentage on rendering output, we keep it as 1px in the AMP output in that particular dimension?

It doesn't solve the problem for 2px or 3px lines, which we probably also have in other places, but do solve this particular case and a few more like it.

**Comment by dvoytenko** [comment]
Do you think we could export a minimal repro case into a jsbin/codepen. I'd like to consult with some of the rendering folk.

However, I think fractional pixels should be ok. My guess, however, is that this issue is with using "fill" vs "stoke". Subpixel rectangle filling will certainly not be as consistent as a subpixel stroke. In this particular case, the shape used as a line and not a rectangle. I understand if we don't want to introduce a new shape. But perhaps, on the rendering layer, we could replace subpixel fill with border?

E.g. instead of:

```
<div style="height: 0.5px; width: 100%; background: black"></div>
```

it could be:

```
<div style="height: 0.5px; width: 100%; box-sizing: border-box; border-top: 0.5px solid black"></div>
```

**Comment by maxyinger** [comment]
Here's a codepen with subpixel line rendering. You can see there's a difference in line height between chrome, safari & firefox but regardless there's no variation between lines on all three:
https://codepen.io/littlemilk/pen/PoNvzEG

This is using a fill and each line renders visually the same. 

My best guess as to why they appear different based on position in the editor is from some rounding error using a clipping mask at such a small size? I'll see if I can reproduce by applying a clipping mask

**Comment by maxyinger** [comment]
Looks like some issue with rounding and clipping paths. can see that here:
https://codepen.io/littlemilk/pen/gOMPJNb

**Comment by dvoytenko** [comment]
Why do we need a clip mask at all in these cases? That's just a basic rectangle, isn't it? I thought we considered it an "empty" mask and ignored it for rendering? At least I think we do so with output [here](https://github.com/google/web-stories-wp/blob/7fb398962d4a08c540ebb32735a36b69a66eb39f/assets/src/edit-story/masks/output.js#L63). In the editor the story might be more complex since we might use masking mechanism for DnD. But maybe we can _only_ activate rendering of an empty mask in DnD mode? Or only for non-subpixel sizes? It's very unlikely a user can actually drag-n-drop inside a sub-pixel shape anyway, right?

**Comment by maxyinger** [comment]
Yea I think there are a couple shapes the user will never use to frame a picture including sub-pixel rectangles.

I think we could add some escaping behavior in the code to try and infer these cases where a user will never use the shape as a mask and that may be the quickest solution for now.

Ultimately I think it could be beneficial to expose shapes to users that don't allow for masking behavior at all and include a rectangle in there that we can make lines out of. (or build some notion of lines themselves that are a subset of shapes and resize more like actual lines)

**Comment by dvoytenko** [comment]
Just realized that all DnD features are built on frames, which wouldn't cause us rendering problems for the display layer. It still likely a very good idea to ignore very "thin" shapes for DnD. But I think we can just always remove the default mask from the display layer.

**Comment by bmattb** [comment]
implementation brief needed to address

**Comment by bmattb** [comment]
during backlog grooming we discussed that this ticket needs more research and discussion , and as such is not ready for sprint, so, moving it back to the backlog
