### ISSUE TITLE
Author Dropdown: huge performance issue with many users

### ISSUE THREAD

**Issue by kakashigr** [GoogleForCreators/web-stories-wp#4749]
## Bug Description

The author box seems to try to populate all the users, not just authors/editors/admins. In a site with ~200k subscribers it either times out because of cloudflare or takes a very very long time to load.

## Expected Behaviour

The author selection box should only include authors/editors/admins

## Steps to Reproduce

Try to create a new story on a site with many subscribers.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Backend
- [ ] Allow frontend to filter for only relevant users (editors and up?)

### Frontend
- [ ] Generalize font picker to generic enhanced dropdown component with the following props:
  - `selectedId` - currently selected option id.
  - `options` - full list of all options to display - must have an id property each.
  - `hasSearch` - boolean prop toggling whether search input is present.
  - `getOptionsByQuery`- if `hasSearch` and `primaryOptions` are available, `options` can be `null`, but if not given, then `getOptionsByQuery` must be given and can be an async function returning matching options.
  - `primaryOptions` - list prop of (fewer) primary options to display when not searching (if searching, all options are possible). Requires `hasSearch=true`.
  - `primaryLabel` - the label to display above the primary options. Requires `primaryOptions` to be non-empty.
  - `priorityOptions` - a short list (max 5) of options to display at the top of the dropdown before main options or primary options. Must function both with and without `hasSearch`. (to be used for "recent fonts" and similar).
  - `priorityLabel` - the label to display above the priority options. Requires `priorityOptions` to be non-empty.
  - `renderer` - component prop to use as custom option renderer. Receives whole option as `<renderer option={option} />`. If empty, use `option.label` as simple text child.
- [ ] Use this new generalized component to display the font picker (with all features enabled)
- [ ] Use this new generalized component to display the author list (with only `hasSearch` enabled)
- [ ] Load only the relevant users from the WP backend

**Comment by swissspidy** [comment]
Yup, definitely something we need to improve!

Should be able to re-use parts of the existing fonts dropdown for that.

**Comment by barklund** [comment]
@swissspidy, I'm guessing this partially applies to loading users too? If we also load all subscribers, and you can have (hundreds of) thousands of those, then the loading should be optimized too? And search should then be async hitting the backend rather than be frontend-only?

Unless we load the data a lot more compactly with just a single string with all user nicknames with a separator - that's not too heavy (but could technically still be a few megabytes for a large subscriber base).

**Comment by swissspidy** [comment]
We should not be loading subscribers. Instead, we should pass `?who=authors` to the REST API query to only load authors and above (like Gutenberg does). That's an easy fix and a good quick win.

But one can still have hundreds of authors, so yes, search should ideally hit the backend.

We can pre-populate the dropdown with the first X users (e.g. X = 100) when loading the document panel. This query can be preloaded in WordPress on page load, so will be very fast.

When typing in the dropdown's search field, we search for users as one types.

Does that make sense?

**Comment by barklund** [comment]
@swissspidy, @spacedmonkey, can one of you create the relevant ticket for backend effort required here - if any? And then update this ticket with API for relevant backend functionality. Thanks!

**Comment by swissspidy** [comment]
@barklund No backend changes needed AFAIK.

Endpoint reference: https://developer.wordpress.org/rest-api/reference/users/#list-users

Get initial list of users to populate dropdown: `/wp-json/wp/v2/users?who=authors&context=edit&_locale=user`

Search for users for autocomplete: `/wp-json/wp/v2/users?who=authors&search=<searchterm>&context=edit&_locale=user`

You can use the `per_page` param to tweak the number of results per page, but do not use `per_page=-1`, as that will otherwise load ALL users again.

---

For a reference implementation of this (as inspiration), install the Gutenberg plugin and make sure you have lots of users (`wp user generate --role=author --count=100`). Then you'll get a similar autocomplete dropdown that uses the aforementioned API endpoints.

**Comment by csossi** [comment]
Verified in QA

**Comment by samitron7** [comment]
Verified in UAT and closing this ticket out but I filed a [ticket](https://github.com/google/web-stories-wp/issues/5509) to address the fact that this dropdown has 3 scrollbar:

<img width="261" alt="Screen Shot 2020-11-30 at 11 23 59 PM" src="https://user-images.githubusercontent.com/10889431/100709567-35a95200-3363-11eb-925c-cb220caba024.png">
