### ISSUE TITLE
Background Audio Support

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#48]
## Feature description

Element for adding audio to a page. Also need to build support for global background audio.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by swissspidy** [comment]
@o-fernandez This just came up in testing:

> I was able to set a story level audio track and a page level one. It should be one or the other. So if a story one is set, the page is hidden / disabled. And should work the other way around. In my testing, both tracks played at the same time and it was a mess.

Thoughts?

Should we make this an either/or thing? I feel like some users might deliberately want to add both to get some nice effects. Otherwise one will quickly realize that it doesn't work well and remove one audio. So I don't think we need to make this complicated.

**Comment by o-fernandez** [comment]
I think that the user should be able to add both, same as they should be able to have audio track for the story and have some video audio also play. The trick may be that we'd need to expose knobs that allow a user to mix the audio in a way that makes sense (e.g., give more weight to one audio track vs. the other). 

Since we don't have UX support, I'd go ahead and ship with what you have for now and then add a UX item to the roadmap and tweak/refine later. WDYT?

**Comment by swissspidy** [comment]
SGTM!

> The trick may be that we'd need to expose knobs that allow a user to mix the audio in a way that makes sense (e.g., give more weight to one audio track vs. the other).

Note that the current solution just relies on AMP's `background-audio` feature for pages/stories, so most likely any improvements in this area would need to be done in the format itself.

**Comment by dreamofabear** [comment]
We had a similar discussion for another stories product recently.

To start, using `background-audio` for incidental audio like music sounds fine. 

For voice overs, we'd want to render as `video` to support captions (with an additional file input field to select a VTT file): https://iandevlin.com/blog/2015/12/html5/webvtt-and-audio/

**Comment by swissspidy** [comment]
Good point & interesting suggestion with the captions 👍  There's at least 1 user who has asked for this. Created #8821 to follow-up with captions support for background audio.

**Comment by csossi** [comment]
Verified in QA
