### ISSUE TITLE
Protocol error on dashboard

### ISSUE THREAD

**Issue by tassawarr** [GoogleForCreators/web-stories-wp#4800]
## Bug Description
![Screenshot_20](https://user-images.githubusercontent.com/16195416/94999024-ba7c2780-05cf-11eb-9676-dc883264ccc5.png)

error on following page. 

i moved a client wordpress website to godaddy which has php7.3 with all the latest stuff. but the dashboard is not working on web stories. i've tried every kind of solution but nothing is working. Please help me for this. 

## Additional Context

- Plugin Version: 1.00
- Operating System: windows
- Browser: google chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi there,

Thanks for your report! Since you just did a migration, I suggest you to reach out to GoDaddy and ask them for assistance in this case, helping with things like checking log files.

The error message comes from your browser, not WordPress, and indicates that you have a misconfigured HTTPS setup. I recommend bringing this up with GoDaddy as well.

If that turns out not to be fruitful, we‘re happy to also take a look. Please note that we‘ve moved support to the WordPress.org forums though.

**Comment by LuckynaSan** [comment]
@tassawarr As we haven’t received a response, this issue will be closed. Please feel free to open a new support topic on the [WordPress.org support forum](https://wordpress.org/support/plugin/web-stories/#new-post) if you continue to experience any issues with the plugin. Thank you!
