### ISSUE TITLE
AdSense and Ad Manager Support

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4803]
## Feature Description

There have been some requests for AdSense Auto Ads integration in Web Stories (e.g. https://wordpress.org/support/topic/do-adsense-auto-ads-dont-show-on-google-web-stories/).

It's something we intend to implement (standalone and/or via Site Kit) once AdSense adds support.

[**Product Brief**](https://docs.google.com/document/d/1Xs4uOZ3KCNlTMdjDT6q7cvTUpA1xk-kzrnVLQALltQk/edit#heading=h.tuoynqlc00)
**Implementation and UI screenshots in #5611**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by robin-scott** [comment]
Site Kit would be a good place for it in medium term.

We've built some Web Stories custom templates, so very likely will be able to PR some of it together for the WP plugin. Really just looking to see what / if the roadmap is for it. (apologies for vague statement - some of this is hidden in a private client project atm )

Also got another request coming at me for the Web Stories editor (don't shoot me for mixing issues) which is related to embed of YouTube videos. Is there an issue for this on radar, or should I create a new one? Also maybe able to pitch in with a PR in due course.

**Comment by swissspidy** [comment]
The Web Stories format doesn't currently support embedding YouTube videos. Follow https://github.com/ampproject/amphtml/issues/15847 for any updates in that regard.

**Comment by robin-scott** [comment]
Thanks - I thought I'd seen that somewhere... was never going to find it though :) following that one. Have done a bit of `<amp-youtube>` and wasn't sure re web stories; now armed with a specific answer. Thanks very much.

**Comment by swissspidy** [comment]
There's a proof-of-concept for AdSense support: #5611

**Comment by o-fernandez** [comment]
Flagging as high priority since we want this in 1.3 @samitron7 
It should be a simple affordance in the Dashboard settings where the user can select an ad network (AdSense or Ad Manager) and then enter their publisher ID and ad slot ID. 

@swissspidy has a proof of concept ([screenshot](https://user-images.githubusercontent.com/841956/101644990-25196b80-3a36-11eb-90e1-b7115be86191.png)) 

The UX refinements needed:

1. User should choose an Ad network first (AdSense or Ad Manager) and then enter the appropriate information. 
2. For Ad Manager, the user should only need to enter a slot ID
3. For AdSense, the user will probably need to enter their Publisher ID and their Story Ad slot ID. 
4. We should link to the appropriate help center articles in Google Support on how to set up a Story Ad. (below)

Ad Manager links 
- [Enable programmatic demand in Web Stories](https://support.google.com/admanager/answer/9416436)

AdSense links
- [Monetize your Web Stories](https://support.google.com/adsense/answer/10175505) <- includes how to set up the ad unit and get the right codes
- [Find your AdSense publisher ID](https://support.google.com/adsense/answer/105516)

**Comment by o-fernandez** [comment]
@samitron7 flagging this ticket as a priority item for this sprint, since it's core to the 1.3 release.

**Comment by bmattb** [comment]
During grooming Infra pod discussed implementing this with the UX indicated by Omar above, and that we could potentially update this UX after the fact if necessary. Based on this we will proceed on implementation.

**Comment by o-fernandez** [comment]
> During grooming Infra pod discussed implementing this with the UX indicated by Omar above, and that we could potentially update this UX after the fact if necessary. Based on this we will proceed on implementation.

Makes sense. @samitron7 FYI

**Comment by swissspidy** [comment]
@o-fernandez @samitron7 We have an initial implementation ready (see #5611 for screenshots). Would you like us to proceed with this and merge it?

**Comment by o-fernandez** [comment]
> @o-fernandez @samitron7 We have an initial implementation ready (see #5611 for screenshots). Would you like us to proceed with this and merge it?

Yeah, that looks really good to me! I'd merge and we can always fix UI/UX things in a subsequent merge.

**Comment by samitron7** [comment]
This looks good as is.
