### ISSUE TITLE
Text Sets are taking too long time to load

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#4815]
## Bug Description
Currently, when the text sets feature is turned on, the editor takes a long time to become active, there are also tests failing due to timing out (see also https://github.com/google/web-stories-wp/pull/4613#issuecomment-703718564)

## Expected Behaviour
- It should be possible to use the editor right away, instead of it becoming responsive once all the text sets are loaded.

## Steps to Reproduce
- Enable the text sets feature from Experiments
- Reload the editor, try to do something right away, e.g. adding a text element.

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
cc @carlos-kelly / @littlemilkstudio FYI created this issue to track the performance of loading the Text Sets.

@barklund I'm adding this to Ready for Sprint since this is blocking enabling the Text Sets feature, however, feel free to move it around / label it as you see fit.

**Comment by swissspidy** [comment]
Looks like all text sets are loaded upon loading the editor. I presume they should rather load when switching to that panel for the first time?

**Comment by carloskelly13** [comment]
@swissspidy Yup, we are going to make that adjustment plus a way to progressively render them. We looked into a virtualized list, but it was too buggy because of all the provider logic required. I do think at some point we might need to rethink our preview components for both text sets and dashboard because loading so many on a single page is getting really expensive.
