### ISSUE TITLE
Story Embeds Project: Gutenberg Blocks, Customizer, Shortcodes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4863]
## Task Description

Tracking ticket for the ongoing work to expand the capabilities of the plugin for developers and site owners.

* Richer functionality for Gutenberg block(s)
* Customizer API
* Shortcodes
* TinyMCE button for Classic Editor
* Widget

**Comment by 4jassikingg** [comment]
Hi, I am also looking to create carasouel of web Stories ?
Can you please let me know if this block is developed...

**Comment by swissspidy** [comment]
@4jassikingg A carousel block is currently in development, stay tuned!

**Comment by 4jassikingg** [comment]
Sure @swissspidy Many thanks. Can you pl let me know when we might expect it to be released.
I am just looking to show a slider for all stories on my blog. If there is any turaround solution, please help me otherwise I will wait until the release of carousel block.

Kudos for the hard work you people have been doing with this new plugin.!!!

**Comment by swissspidy** [comment]
Thanks for the kind words. Early in the new year / Q1 we should have this ready :) Nothing to share just yet unfortunately.
