### ISSUE TITLE
Add system - dialogue box to design system

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#4956]
Add new dialog component to design system. 
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040

**Comment by BrittanyIRL** [comment]
@samitron7 
two small questions when you have a second 
1) In figma looking at the sample dialog box, the "secondary" action button is using the tertiary button style - just making sure you want the tertiary button style here not secondary. 
2) What color do you want the background overlay? It used to be `rgba(26, 29, 31, 0.96)` in the dashboard and `rgba(27, 29, 28, 0.96)` in the editor - which the theme value there is bg.workspace. I set it to be bg.workspace tied to the theme so that's `1B1D1C` in the editor and `FCFCFC` for the dashboard + the same 0.96 opacity.

**Comment by samitron7** [comment]
@BrittanyIRL - Answers below:
1) In figma looking at the sample dialog box, the "secondary" action button is using the tertiary button style - just making sure you want the tertiary button style here not secondary.
Yes, we are in fact using the tertiary button to de-emphasis it from the primary button

2) What color do you want the background overlay? It used to be rgba(26, 29, 31, 0.96) in the dashboard and rgba(27, 29, 28, 0.96) in the editor - which the theme value there is bg.workspace. I set it to be bg.workspace tied to the theme so that's 1B1D1C in the editor and FCFCFC for the dashboard + the same 0.96 opacity.

Just a note that we had to make changes to the color palette (ie expand them for accessibility). Hoping to lock those down by Monday. Meanwhile, for both scrims on Dashboard and Editor, please use #1E1F1F, 0.5 opacity. If there are any further changes, I'll let you know.
