### ISSUE TITLE
Workspace - Video Preview 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#496]
## Feature Description

See #26 #50 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. Videos can be played within the workspace
2. Gifs are treated as images EVERYWHERE (for now)
3. When a user selects the video element a transparent play button appears on the video element
4. When user clicks on play icon video will play

**Comment by jauyong** [comment]
Flagging @samitron7 for designs needed

**Comment by merapi** [comment]
I did the implementation in https://github.com/google/web-stories-wp/pull/720 (it is done via `isPlaying` property on the element) but @barklund pointed out the issue with history, which brings me back to the square one.

How should we solve it, anybody has use cases for B)?

Possible solutions:

A) Just make it work in the simplest possible way, which means accessing the video Display elements directly from Frame elements:

A1) Via something like `videosById`, set the nodes in Display and access them in Frame. 
Cons: this cannot be on `CanvasProvider` level because we need to use it higher, in Media (trigger play after insert). So another Provider just for that purpose?

A2) Even #video-ID.play() could work, also for play after insert (with setTimeout 0).
Cons?

---

B) A mechanism for storing element(/page) metadata that shouldn't pollute history stack - is there any other use-case for this? here we can store `isPlaying, currentTime` and so on.

B1) Store it under one property `element.meta`? on the element and "just" exclude those changes from history stack. 
Cons? it can get messy with filtering out the updates.
`updateElementById({ elementId, properties: { meta: { isPlaying: true } } });` or `updateElementMetaById({ elementId, meta: { isPlaying: true } });` etc.

B2) Store it separately from pages key (which is using history), we can store elements array or elementsById and their metadata.

**Comment by dvoytenko** [comment]
Overall `isPlaying` as a property is not convenient. Playback is inherently an imperative feature. As the first step we could use `useTransformHandler()` for this. It's also not a 100% match, and it might require too many changes, but could be easy enough to start with. However, the closest model to this I can think of is the React's `useImperativeHandle()` style hook that the display component can export and the frame can call.

With transforms it could look like this:

```
function Frame() {
  const {
    actions: { pushTransform },
  } = useTransform();
  const onClick = () => {
    pushTransform(element.idm {action: 'togglePlay'});
  };
  ...
}

function Display() {
  useTransformHandler(elementId, ({action}) => {
    if (action === 'togglePlay') {
      togglePlay();
    }
  });
}
```

This will get us there, but I don't like it for two reasons:
 1. This is also not imperative API
 2. The format of transform callback is very specific for transformation/update tasks. It's used throughout. We may need to update lots of code, at least so it doesn't fail.

With imperative export:
```
function Frame() {
  const elementApiRef = useElementApiRef(element.id);
  const onClick = () => {
    if (elementApiRef.current) {
      elementApiRef.current.togglePlay();
    }
  };
  ...
}

function Display() {
  // This is 
  useRegisterElementApi(element.id, () => ({
    togglePlay() {
      ...
    },
  } ), [depsIfAny]);
}
```

Here,
 * The whole system is close in nature to `forwardRef`
 * `useRegisterElementApi` is a cross between `useImperativeHandle` and `useMemo`

**Comment by dvoytenko** [comment]
Also, as the very first step, imho, it's fine to do `#video<elementId>.play()/pause()`.

**Comment by merapi** [comment]
So how about just simple API to get the DOM node of the Display element?
What is the benefit of `togglePlay(){}` part defined in Display (`useImperativeHandle` style)?
In this particular case, I don't see any (all play/pause logic will be in Frame, synced with UI and we just need play/pause/currentTime on video node, also play() returns Promise so it's just easier to have the node ref in Frame and act on it), maybe somewhere else that would be useful (useImperativeHandle style)? We can also mix it and provide some API methods on element + direct node access.

```jsx
<(Element)NodeProvider>
  <Canvas /> // Will set nodes and use them for imperative API
  <MediaPane /> // Can also use them for "play after insert"
</(Element)NodeProvider>
```

I'm fine width #ID method for v0, we just need to exclude elements from Carousel thumbnails from double setting this #ID.

**Comment by dvoytenko** [comment]
The `(Element)NodeProvider` is not significantly different from `ElementApiProvider` of some sort. Both element and API exporting would work via exactly the same mechanism - via ref forwarding of some sort.The main issue with a DOM element is that a `Display` component is likely to output wrappers and other UI features needed for display. So, then you might have to dig inside the internal DOM structure to find video. Also, a `Display` component might prefer to delay video creation until playback is requested or it could do a significant UI reshuffling to show controls, etc. With all this said, I think we should just go ahead and create a provider and export API. Looking for element, via provider or `getElementById`, is full of problems and likely will need redo very soon. Thus I think the provider will still likely look like a cross between `TransformProvider` and React's `useImperativeHandle`/`useMemo`.

**Comment by dvoytenko** [comment]
Also, `ElementApiProvider` is essentially equal to `ElementNodeProvider` when we use the actual element (instead of a memoized generated API) as the payload. Thus, I think, both approaches are essentially the same.

**Comment by merapi** [comment]
> Also, as the very first step, imho, it's fine to do `#video<elementId>.play()/pause()`.

Going with this solution for Alpha. Updated https://github.com/google/web-stories-wp/pull/720.
