### ISSUE TITLE
"Not an AMP page" after updating the plugin to the latest version.

### ISSUE THREAD

**Issue by dmitry-christie** [GoogleForCreators/web-stories-wp#4975]
## Bug Description

Hello, I've updated the plugin to the latest version (Version 1.0.0) after having used it since alpha. Now, the new stories that we're creating are not valid. We've run the test on the old stories and they're fine.

The latest story: https://www.globalcitizensolutions.com/web-stories/the-best-and-easiest-countries-to-get-a-second-citizenship/

The valid story created before the update: https://www.globalcitizensolutions.com/web-stories/why-retire-in-spain/

## Expected Behaviour

New stories should be valid.

## Steps to Reproduce

Create a new story with the latest plugin version.

## Additional Context

- Plugin Version: 1.0.0
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by LuckynaSan** [comment]
@dmitry-christie Hi there! We've moved support for the Web Stories plugin to the [WordPress.org support forums.](https://wordpress.org/support/plugin/web-stories/)

Could you open a [new topic](https://wordpress.org/support/plugin/web-stories/#new-post) there and share the same details there? I will close your issue here, but we'd be happy to assist you in the forums.
