### ISSUE TITLE
Video poster failing to generate, produces invalid AMP story

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5119]
## Bug Description

Sometimes, our editor fails to generate a video poster, which may result in a story that's invalid if the user doesn't upload a separate video poster image. We should make this process more robust. 

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
The original idea, was to have a check before you publish and highlight videos without poster. Then ask the user to upload a poster.

**Comment by swissspidy** [comment]
Hmm I thought `poster=""` would work. If we could fall back to that for now it would at least not be invalid anymore. Then we have more time fixing this correctly.

> Then ask the user to upload a poster.

Even better to just auto-generate it :)

**Comment by spacedmonkey** [comment]
Maybe we should retry a couple of times to generate the poster, say 3? 

We may need some state to track the number of retries. 

There is already a TODO in the code to surface the error to the user. 

https://github.com/google/web-stories-wp/blob/7cf07181c4a39995df3552a4f50b86036c2b43af/assets/src/edit-story/app/media/utils/useUploadVideoFrame.js#L96

**Comment by spacedmonkey** [comment]
I also think this ticket is related and useful here https://github.com/google/web-stories-wp/issues/969

**Comment by swissspidy** [comment]
FWIW, supplying an empty string as the poster (`poster=""`) is totally fine if there is no poster (e.g. if poster generation failed) and won't cause AMP validation issues.

So I would split this up into two tickets:

1. Make video poster generation more robust (retries, etc.)  
  Larger task, takes some time, P2 or P3 item.
1. If there is no poster, ensure that an empty string is passed instead of omitting the `poster` attribute.
  1 line change (I have a fix ready), P0 item that could go into 1.1.1

FYI @o-fernandez

**Comment by swissspidy** [comment]
Opened #5190 for 1) above.

Opened #5189 for 2) above.

**Comment by bmattb** [comment]
@swissspidy - can we tag this for v1.2 ?

**Comment by swissspidy** [comment]
@bmattb Sure... but not sure why this was assigned to the WP pod. What's the reasoning? (cc @barklund )

**Comment by swissspidy** [comment]
There's actually #5190 for improving robustness which is assigned to Zidian, so closing as duplicate
