### ISSUE TITLE
Elements with duplicate masks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5137]
## Bug Description

In stories like https://wp.stories.google/stories/10-web-stories-and-whats-great-about-them-storytime/ there are multiple elements or element masks with the same `ID` attribute.

## Expected Behaviour

That shouldn't happen. IDs should be unique.

## Steps to Reproduce

?

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
I haven't been able to reproduce this so far, tried the cases where this could logically happen:
- Using the same text sets multiple times
- Using the same page templates multiple times
- Duplicating elements
- Duplicating pages
- Duplicating background media (shapes with masks essentially)
- Duplicating pages with bg media.
- Copying and pasting elements 

I think I remember one case where the ID was used from the pages templates directly but that got fixed when implementing Custom Page Templates.

I'll try to testing this some more.

**Comment by miina** [comment]
Still haven't been able to reproduce this. Took a closer look at the story in the description to see if using similar shapes would somehow be helpful to reproduce this (e.g. background video), however, no luck so far.

Also checked some already existing stories in local / QA (some of them including 37 pages of various media / shapes, etc.) and all seems correct.

@swissspidy Do you know of a more recent occasion of this bug?
Otherwise, I'd recommend moving it to the backlog since perhaps it has been fixed since it was last reported around 6 months ago.

**Comment by swissspidy** [comment]
I don't have a recent example, no. Sounds like we can close this for now and re-open if it appears again.
