### ISSUE TITLE
Improve story preview performance on the dashboard

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5147]
## Bug Description

Improve story preview performance on the dashboard. There are multiple images of a story being loaded on page load.

## Related topic

https://wordpress.org/support/topic/loading-images-all-the-time-in-the-dashboard/#post-13622589

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #7987, #8117

**Comment by BrittanyIRL** [comment]
@csossi to test this, I just want more eyes on the dashboard making sure there's no weird regression happening - there shouldn't be, it's unlikely, but still. 

So just make sure that the dashboard's 'my stories' view story items have working context menus and do a sanity check that templates are working as expected. No changes to the explore templates view are being made here. 

And hopefully, it's a little speedier of a load for ya.

Things that are different: 
- Images are shown instead of stories on the grid, these are the poster image attached to each story. If there's no story to see it'll just be a gradient marking the placeholder. 
- Keyboard nav of the my stories grid is improved! now you can tab to the grid, use the arrows to key through the grid, 1 arrow with get you to each context menu, everything the user needs is in the menu so there's no need to go through anything else. 

lemme know if i can clarify anything else, the PR that is attached to this has a lot more context.

**Comment by csossi** [comment]
Verified in QA
