### ISSUE TITLE
Improve carousel drag indicators / separators

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#517]
## Bug Description

While looking at #380 / #411 I noticed that the blue bars indicating the drop location while reordering are not appearing in the center anymore. Instead, they are attached to either the left or the right item. Sometimes they are not appearing at all.

This is a regression.

## Expected Behaviour

Indicators/Separators are always appearing in the middle of two items.

## Steps to Reproduce

Drag & drop pages in the carousel using the mouse.

## Screenshots

<img width="257" alt="Screenshot 2020-03-10 at 13 30 49" src="https://user-images.githubusercontent.com/841956/76312472-6fb55e00-62d3-11ea-8ae7-2c90ecbf66ef.png">

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dvoytenko** [comment]
Related issue that we may want to dedup here is: https://github.com/google/web-stories-wp/issues/332. There are all kinds of other nuances here. For instance, the ghost image often blocks the marker from view and makes it really hard to figure out where the page is moving to.

The bottom line: we most likely will want to switch from native DND to the pointer events, like it's done in the layers.

/cc @barklund

**Comment by wassgha** [comment]
Let's refactor the carousel to use the same drag/drop reordering component as the layers panel (see `useLayerReordering.js` and `separator.js`), I like the API for it.
Tasks:
- [ ] Expose and rename `useLayerReordering.js` to `useReordering.js` (or maybe turn it into an HOC `<Reorderable/>`
- [ ] Address any discrepancies (`horizontal` vs `vertical` reordering differences for example) and UI differences
- [ ] Use it in the layer panel, the thumbnail carousel and the grid view (stretch goal)

Since @barklund made layer reordering, probably would be easiest to take on this work? /cc @barklund

**Comment by dvoytenko** [comment]
IMHO, whatever we do for page carousel should work for page grid. The uniformity and code use between carousel and grid is more important than layer/carousel reuse. If it's generalizable easily though, that's of course great.

**Comment by barklund** [comment]
We might be able to leverage the work done in the layer panel, but I agree with @dvoytenko in that it's more important to be able to use the same component for grid view **and** carousel.

I think the approach in layer panel can be reused, but not 100% on what is gained by generalizing to arbitrary direction rather than making it anew specific for carousel/grid.

**Comment by wassgha** [comment]
@barklund  you obviously have more knowledge on this but from a quick inspection of the code yesterday it didn't look to me like it needed a generalization for direction at all since it depends on the separator element position so it seems like simply changing styles of the separator element should be sufficient to get it to work in every direction.

**Comment by barklund** [comment]
@wassgha, hm that is technically true now that I think about it. It's only based on mouseover on the physical size of separators hard-linking them to a potential drop position. It might actually be pretty easy to reuse.
