### ISSUE TITLE
Switching text set categories changes scroll position in text panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5220]
## Bug Description

When switching between Text Set categories, the text panel scroll position resets.

## Expected Behaviour

Switching categories should not impact the scroll position.

## Steps to Reproduce

1. Scroll text panel to bottom
2. Switch to “Header” category
3. Notice that the scroll position of the panel changes

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by dreamofabear** [comment]
I think this is just because text set categories may have different heights due to more/fewer text sets. The scroll position only "jumps" insofar as the text set panel's height changes.

**Comment by BrittanyIRL** [comment]
Same issue is happening in page layouts - which is shared code, so when fixing this make sure it takes there as well.

**Comment by maxyinger** [comment]
**Text Sets**
Appears this issue was mitigated in the text sets with an update to the pills not being sticky.

**Page Layouts**
As for page layouts, it seems like the only time there's a jump is if you're on a category that has a lot of page layouts, say 48 layouts, and you're scrolled past the 38th one, then you switch to a category that has say 12 layouts, you'd then be scrolled to the bottom of the new category on first render. 

Happy to alter the behavior here, but that's the only time I'm seeing any jump. Behavior seems pretty standard tho. Any thoughts?

**Only way I could reproduce (but seems like expected behavior):**
-> go to page layouts and make sure `all` is selected
-> scroll about halfway down through the page layouts
-> click on `cover` category
-> cover category should render scrolled to bottom (This is the only jump I see)
-> click back to `all` there is no jump because `all` is larger than `cover` so the scroll offset can be directly applied

**Synopsis**
Let me know if I'm missing a certain case here, or we'd like to alter the behavior to deviate from the standard behavior. However, to me this works as expected as it is right now.

**Comment by dreamofabear** [comment]
Yea, just tried again and it seems quite minor now. Closing as obsolete. Thanks for investigating.
