### ISSUE TITLE
AMP Sanitization: Include metadata fallback file

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#5235]
## Bug Description

Reports were submitted about this validation error: The attribute ‘i-amphtml-version’ in tag ‘style[amp-runtime]’ is set to the invalid value ‘0’.

## Expected Behaviour

No validation errors on the story URL

## Steps to Reproduce

1. Create a story.
2. Preview story and check for validation errors. 

## Screenshots
Source code of site with issue: https://jmp.sh/9fKStGQ
Source code site without the issue: https://jmp.sh/6F7VnWj

## Additional context
Sites are not able to access https://cdn.ampproject.org/rtv/metadata.

## Related topics
https://wordpress.org/support/topic/erro-ao-visualizar-imagens/
https://wordpress.org/support/topic/google-search-console-errors-for-web-stories/

- Plugin Version: 1.1.0
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* In `scoper.inc.php`, make sure `vendor/ampproject/amp-wp/lib/optimizer/resources/local_fallback/` is copied over.

**Comment by swissspidy** [comment]
This is caused by the `AmpRuntimeCss` transformer which attempts to add the runtime version to the `style[amp-runtime]` element. It either uses the given version (if one is passed) or otherwise queries `https://cdn.ampproject.org/rtv/metadata` for the latest AMP runtime version and then gets the actual  CSS styles from there as well. If the former request fails for some reason, this will result in `0` being set. Either way, the result is cached in a `amp_remote_request_` prefixed transient for a week.

So one way to solve this is probably by removing that transient.

**Comment by swissspidy** [comment]
@westonruter Curious, is this issue here sometimes reported in the AMP plugin as well?

**Comment by westonruter** [comment]
No, this is the first time I've ever heard of this being an issue. The AMP plugin bundles a copy of that `metadata` in case the HTTP request fails: https://github.com/ampproject/amp-wp/blob/2.0.5-built/vendor/ampproject/optimizer/resources/local_fallback/rtv/metadata

Perhaps Web Stories isn't including that fallback file?

**Comment by swissspidy** [comment]
Nope, we're indeed not including that! I'll definitely sneakily copy that from you 😈
