### ISSUE TITLE
Search Console shows soft 404 error for Web Stories

### ISSUE THREAD

**Issue by JamesVincet** [GoogleForCreators/web-stories-wp#5287]
## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

As Google launched Web Stories Plugin for WordPress. I have created web stories for [best espresso beans](https://procoffeeguide.com/).  Now the issue is that Web Master Tool shows Soft 404 Error. Please guide me on how to solve this issue.

Here are my web stories: [best espresso beans](https://procoffeeguide.com/web-stories)

**Comment by swissspidy** [comment]
Hi there

Please note that we're only providing support via the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/). Please open a new topic there for any future inquiries.

Also, for any indexing questions it's usually recommend to go through [Google Search Central Help Community](https://support.google.com/webmasters/community?hl=en), as it's a bit out of scope of this plugin.

It would be good to know which URL is exactly reported to be a soft 404. In any case.

As per https://support.google.com/webmasters/answer/181708?hl=en, "a soft 404 is a URL that returns a page telling the user that the page does not exist and also a 200-level (success) code. In some cases, it might be a page with little or no content—**for example, a sparsely populated or empty page**".

If you think that your page is incorrectly flagged as a soft 404, use the [URL Inspection tool](https://support.google.com/webmasters/answer/9012289) to examine the rendered content and the returned HTTP code.

Looking at https://procoffeeguide.com/web-stories, it indeed seems like a sparsely populated page. Since this archive page's layout comes from the theme, perhaps you can add some content there through your theme, or set it to noindex until you've added some more stories.

----

**Aside:** I see that you haven't yet added a publisher logo to your stories. I recommend doing so in order for your content to pass the [Web Stories Test Tool](https://search.google.com/test/amp).
