### ISSUE TITLE
Prepublish checklist is showing "Low image resolution" errors inconsistently 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5376]
## Bug Description

from @o-fernandez 
Low image resolution” error shows up sometimes and not consistent if I resize the same image on canvas multiple times (e.g., expand it and then shrink it and it’s not consistent)

## Screenshots

![Screen Shot 2020-11-20 at 3 47 48 PM](https://user-images.githubusercontent.com/58738530/99848626-1bdc6380-2b48-11eb-9a3c-8c4423536e23.png)
*NB - I am not sure if this screenshot is accurately reflecting the noted error.*

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zachhale** [comment]
I think this may be related to full screen images requiring different logic. I'm going to tackle this in #5377

**Comment by zachhale** [comment]
@bmattb while fixing #5377 I realized that these errors in the screenshot here are actually two checks almost exactly the same message. I was pulling my hair out trying to debug because of it!

1. Accessibility warning if < 1:1 pixel density
2. Media guidance if < 1:2 pixel density

So this photo is probably picking up issues from before the latest round of bugfixes checking for the full asset dimensions, but the issue still remains with the two messages being exactly the same that would show up together if the more strict check is met.

I see the reasoning behind them both, but think that either the messages should be updated to be unique or we should update the logic to only return one at a time.

**Comment by dreamofabear** [comment]
IMO let's just keep the more strict warning (media guidance) since the user-facing text is basically the same.
