### ISSUE TITLE
Unable to properly select text in panels

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5407]
## Bug Description

When a creator tries to select the text in the prepublish checklist, something prevents this from happening. Selecting from the bottom captures a different set of text than selecting from the top

![Screen Shot 2020-11-23 at 2 52 46 PM](https://user-images.githubusercontent.com/58738530/100008735-d3b57f00-2d9b-11eb-8a7a-dbdca47b51c1.png)

![Screen Shot 2020-11-23 at 2 53 10 PM](https://user-images.githubusercontent.com/58738530/100008760-db752380-2d9b-11eb-8789-78d22caeda8b.png)

## Steps to Reproduce
1.  open an existing story with some recommendations
2. use the standard click drag to select text from the Prepublish checklist recommendations
3. note the inability to select all text as expected

![Screen Shot 2020-11-23 at 2 53 10 PM](https://user-images.githubusercontent.com/58738530/100008899-09f2fe80-2d9c-11eb-9418-cafb2c3b36b4.png)

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by zidianlyu** [comment]
Looked at this issue. Here are what I found:

1. Go the `Checklist` panel
2. Select some text (not the entire paragraph), **stop for 1~2 seconds**
3. Keep select the remaining text, the cursor will be blocked for selecting text.

**Comment by zidianlyu** [comment]
It seems like this issue is happening in the entire right side bar.

**Comment by csossi** [comment]
Should user be able to click-and-drag to select a portion of test? At present, this only seems to be working if user begins their click-and-drag at the start of copy

Also, shouldn't clicking elsewhere deselect selected text?

**Comment by swissspidy** [comment]
> Should user be able to click-and-drag to select a portion of test? At present, this only seems to be working if user begins their click-and-drag at the start of copy

It depends on where you are trying to select text.

For example, partial selection works fine in the **Page Advancement** panel in the Document tab.

But it won't work in the Pre-Publish tab because those checklist items are actually clickable buttons. And you can't select text in a button. The browser won't let you do that :-)

> Also, shouldn't clicking elsewhere deselect selected text?

Not necessarily. The browser will only clear selection depending on where you click next.

For example, it will clear selection when you click in search input field afterwards, but not when you click on a button (or the canvas, for that matter)

**Comment by csossi** [comment]
Verified in QA
