### ISSUE TITLE
Editor interface scrolls in window revealing blank space at bottom

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5458]
## Bug Description

Web Stories editor interface is scrolling in the browser, creating a white area at the bottom if the user scrolls up/down within the design area:

## Expected Behaviour

This shouldn't happen.

## Screenshots

![image8](https://user-images.githubusercontent.com/58738530/100260439-64649a00-2f17-11eb-8068-ab8789531c8a.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
@swissspidy, any idea what this comes from? I can see it with a long menu in the left side (if the menu is longer than the window), but it the above gif the menu is clearly shorter. I haven't been able to recreate.

**Comment by swissspidy** [comment]
Not off the top of my head.

@ernee @jamesozzie @LuckynaSan perhaps you are able to reproduce this?

Also reported in #6004:

> * When I scroll this large white space appears at the bottom of the screen which is weird and unnecessary

**Comment by ernee** [comment]
Seeing this on a test site at WP.com: 

<img width="1279" alt="Screen Shot 2021-01-22 at 7 30 55 PM" src="https://user-images.githubusercontent.com/8108643/105567914-86498580-5cea-11eb-89e3-6a4175290b93.png">

But the left admin menu is kind of long.

**Comment by dadarkman** [comment]
I came to write about this issue and found that it was already here!
It gets really frustrating when scrolling inside the Design area though because once the Web Stories interface moves, it displaces the mouse position relative to where the click was supposed to happen. When the Layers panel is open, it covers a portion of the bottom where the Animation functions can be seen. Therefore it always forces me to scroll to reveal the Animation part, and almost 99% of the time I'd forget not to scroll too fast. 

In my opinion, when inside of Web Stories, the WP menu should be either static or make the interface full height. I'm saying this cause the Make Stories plugin, which I also have installed, does exactly that! When using it, the WP menu stays in place. So, I guess that's something the team at Google Web Stories can pull too. 

Once again, I'm hoping for a fix in near future.

Thanks

**Comment by swissspidy** [comment]
@dadarkman Do you have many plugins installed and thus a long admin menu? Just so we can better test any possible scenarios.
