### ISSUE TITLE
Autosaving not working when not idle

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5459]
## Bug Description

Both Sam and I verified that autosaving is not working as expected.

When i make some changes, and wait for 60 seconds, an autosave will happen. (as expected)

However, when I constantly make changes for a period of time, no autosave happens - _**until I am idle again for 60s**_

## Expected Behaviour

Autosave should kick in even when I am editing.

## Steps to Reproduce

Make some changes, and observe autosaving

## Additional Context

- Plugin Version: 1.1.1
- WordPress Version: 5.5
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
Opened a text field. Slowly just started typing a repeating "a". After approx one minute, the autosave kicked in, as expected:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/bc418030-f786-4def-b949-73b7f6271499)

I then resumed typing in the text field that I was typing in (didn't click away - stayed in field after autosave). Expected that as I typed additional letters, the "Save Draft" would become enabled:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/05aee000-e348-4ec0-8ad3-631d097232ca)

**Comment by barklund** [comment]
@csossi, edit-modes are a special case here. When you enter edit-mode, the changes aren't persisted until you exit edit-mode. That's why you can undo all changes done in edit-mode by pressing undo just once.

This however means, that all the changes done while in edit-mode aren't even considered changes until you exit edit-mode. Thus there is nothing to save - while in edit-mode, you haven't actually changed anything yet.

It can be considered similar to dragging an item around - it's only when you drop it somewhere, you actually make an edit. While dragging, nothing is considered a change and there is nothing to save.

So, the above is by design. Only actual changes, that can be undone by pressing the "undo" icon, can be saved.

**Comment by csossi** [comment]
Ok, thanks for that @barklund - verified in QA then
