### ISSUE TITLE
Discovery: Story Data Format for Templates

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#546]
## Feature Description

This issue will be used to track the discovery work regarding the currently story data format and how that translates to templates

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Gain an understanding of the data format
2. Suggest a solution / next steps for templates

**Comment by mariano-formidable** [comment]
@pbakaus  I've written up my findings in a google doc.  Here's the link:
https://docs.google.com/document/d/1cWOVLhwilUwxpcksZGIg-o3PHq2hCapMHxnA74rF_9c/edit?usp=sharing

The gist of it is that the existing data structure should work just fine for our templates, and animations will just be another property in the metadata bucket.

**Comment by dvoytenko** [comment]
This sounds good. We can clarify the exact details in reviews for the actual format. For the output, we need to explore if we can use `<style amp-keyframes>` (https://amp.dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations/) at the bottom of the doc: they are a significantly more allowed size since they are not render-blocking CSS declarations.

The one detail that usually worries me with animations is setting up for the initial state. E.g. an editor would typically place an element into its final place/state and then request animation that offsets it and moves into the final place/state. Setting to the pre-animation state (time=0) is tricky and could result in the FOUC.
