### ISSUE TITLE
Discovery: Performance 

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#548]
## Feature Description

Aim for implementing performant patterns and high code quality to increase the load time for users.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1.

**Comment by BrittanyIRL** [comment]
This ticket was created out of the initial ask for discovery re implementing SSR to help with performance. Discovery based on that: 

**Should we use SSR?**
Implementing SSR in our existing wordpress/php + react ecosystem would mean an extra layer of infrastructure (likely Next.js) and a node server. This is a lot extra to maintain for a questionable benefit as there's a lot of hoops to jump through to have SSR mean the site's more performant and has a perceived faster load time for users.
Instead of adding this extra layer and spending time away from feature work to meet our May deadline, I would suggest the following in the existing CSR if these are the gains desired when SSR was mentioned:

**For performance gains:** Aim for implementing performant patterns and high code quality to increase the load time for users.

These are things that will happen organically as we flesh out the dashboard. After that point, if performance is an issue we can reopen this issue or make a new one.
