### ISSUE TITLE
Discovery: SEO

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#549]
## Feature Description

Look into something such as prerender.io to help with crawling the site or see if helmet can meet our needs.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria
1. A suggestion for next steps for SEO is uncovered

**Comment by BrittanyIRL** [comment]
This ticket was created out of the initial ask for discovery re implementing SSR to help with performance. Discovery based on that: 

**Should we use SSR?**
Implementing SSR in our existing wordpress/php + react ecosystem would mean an extra layer of infrastructure (likely Next.js) and a node server. This is a lot extra to maintain for a questionable benefit as there's a lot of hoops to jump through to have SSR mean the site's more performant and has a perceived faster load time for users.
Instead of adding this extra layer and spending time away from feature work to meet our May deadline, I would suggest the following in the existing CSR if these are the gains desired when SSR was mentioned:

**Regarding SEO**
Given this is an internal dashboard to allow stories users access to their stories we do not need to consider SEO in the dashboard. 

![Screen Shot 2020-03-18 at 10 34 05 AM](https://user-images.githubusercontent.com/10720454/76989707-030a1700-6904-11ea-9eba-d14c702b606f.png)
