### ISSUE TITLE
FTUE for Story Embeddings

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5493]
## Feature Description

@swissspidy is working on a project to improve embedding options in WP websites. This ticket is to explore the appropriate user education options that we'd want to pursue as we release that feature. Things to consider: 
- where and how to show creators the ways they can use embeddings
- documentation of shortcode for non-Gutenberg sites
- other? 

@samitron7 would love your thoughts on how we approach this. Creating a ticket specific to FTUE for embeddings to ensure we don't miss it. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samitron7** [comment]
Thanks @o-fernandez. FYI  @Cecil921 @angelapgUX Let's add this to the FTUE exploration.

**Comment by BrittanyIRL** [comment]
@samitron7 - trying to prep for 1.7 a bit and am curious if there's any more details on this that you can provide?

**Comment by aaecheverria** [comment]
Hi @BrittanyIRL  @o-fernandez ,

In the Figma link below (First Time User Experience > Green Section), you can start taking a look to our proposal for the FTUE for Story Embeddings. It's pretty straightforward since it is just adding an extra tip in the companion helper.

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=2%3A91941

**Note:**  The only pending piece for this deliverable would be the animation for the tip. 
Brittany: Please let us know what your initial thoughts are and if you think it is necessary  to do a quick hand-off call for this.
![Captura de Pantalla 2021-03-25 a la(s) 6.15.54 p. m..png](https://images.zenhubusercontent.com/5ff5d96a0a28f36af0e4bf01/cf5c499b-93b7-4278-9325-59bc78229edb)

**Comment by BrittanyIRL** [comment]
> In the Figma link below (First Time User Experience > Green Section), you can start taking a look to our proposal for the FTUE for Story Embeddings. It's pretty straightforward since it is just adding an extra tip in the companion helper.
> 

Thanks for the details, @aaecheverria ! So this is just adding another tip that users can read in the help center, it's not needing a trigger of its own like the safe zone?

**Comment by BrittanyIRL** [comment]
@samitron7 any update on when you'll have the animation done for this? Currently planning out next 2 sprints.

**Comment by o-fernandez** [comment]
@angelapgUX wondering if you have an update for @BrittanyIRL here?

**Comment by aaecheverria** [comment]
@o-fernandez @BrittanyIRL 

Hi guys, we currently don't have a motion designer staffed in our team (we will soon), so @samitron7 is helping out with this animation. I can follow up with her today during our sync and get back to you.

Thank you!

**Comment by BrittanyIRL** [comment]
We're going to use a static asset for the time being, can be found here: https://drive.google.com/corp/drive/folders/154E-LPdf5K0I2Pqx10bI6BYCOkSiSBeC 

Waiting for confirmation from @ivayloklissarov but it's probably the first png.

**Comment by BrittanyIRL** [comment]
It is indeed. this one: `"illustration_storyembed_00.png`
