### ISSUE TITLE
Animations - Switching between animation types has inconsistent behaviour

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5523]
## Bug Description

If I select pan-left from dropdown (on BG media), select 3000ms duration, and then change the pan direction to right using the arrows, the duration is kept at 3000ms. But if I go back to the dropdown and select “pan-right”, the duration is reset to 1000ms.

## Expected Behaviour

The presentation & value in the duration field should be consistent whatever method the user decides to select a direction in the pan animation

## Steps to Reproduce

1. Select an object which can have the pan left animation applied to it
2. Edit the duration to anything other than the 1000ms default
3. Using the arrow indicator, switch to another direction - note that there is no change in the duration value
4. Using the animation drop down, select another available pan direction - note that the duration value has now been reset to the 1000ms default value

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
Right now we have different default durations between effect. for instance `drop` has a default duration of `1600ms` whereas `fly-in` has a default duration of `600ms` .

Is there any worry that this scenario happens with the proposed expected behavior?
-> user opens effect chooser to select effect
-> user clicks drop first -> animation duration set to 1600ms
-> user doesn't exit out of effect panel and decides to click through other anims for something different
-> all the effects look too slow when previewing now cus they're retaining that 1600ms duration

Can extrapolate this to other combinations of picking effects, but I think it could cause some weird behavior for the user. Any thoughts?

**Comment by samitron7** [comment]
@littlemilkstudio I'm not really understanding the question here. Everything animation option should come with it's own set of defaults. When you switch from one animation to the next, those default values should also change to ensure that the animation always look good.

**Comment by littlemilkstudio** [comment]
## Steps to Reproduce

1. Select an object which can have the fly in animation applied to it
2. Edit the duration to anything other than the 600ms default
3. Using the arrow indicator, switch to another direction - note that there is no change in the duration value
4. Using the animation drop down, select another available pan direction - note that the duration value has now been reset to the 1600ms default value

> I'm not really understanding the question here. Everything animation option should come with it's own set of defaults. When you switch from one animation to the next, those default values should also change to ensure that the animation always look good.

sorry, having a tough time following. Which steps in this `Steps to Reproduce` here are unexpected behavior?

Is it that the duration should reset to the default duration when you switch directions with the direction selector? That seems a little weird to me from a user perspective. Not sure if I'm grokking this request entirely

**Comment by maxyinger** [comment]
@samitron7 I just reread through the ticket. Think I misread it initially, my bad. So when you select the same effect with a different direction from the effect chooser we don't want the defaults to reset the inputs.

ie
1. open effect chooser and select fly in left
2. update duration to 200ms
3. open effect chooser and select fly in right
4. close effect chooser, duration should still be 200ms

I think I'm reading the ticket correctly now and that's what it's asking for. Sorry for the confusion. I'll proceed with this interpretation unless told otherwise

**Comment by maxyinger** [comment]
@bmattb Made a PR for the behavior I mentioned above which I think this ticket is describing. If we can get the behavior made in that PR signed off, I think we can get this change through QA before Wednesday.

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
This is behaving according to the expected behavior now, closing it. @samitron7 @ivayloklissarov @aaecheverria
