### ISSUE TITLE
Discovery - Explore a simple border for non-rectangular shapes 

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5536]
## Feature Description

Explore: Simple border for non-rectangular shapes (e.g., circles, triangles, blobs, stars, etc.) 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund: Here is the conclusion for a possible solution after looking into this, let me know your thoughts.
 This is for adding a simple border that accepts (single value) border-width and color, supports opacity, and is an outer border, as in case of the rest of the elements.

For adding border to the shape, we could use an additional svg with stroke and stroke-width, in a similar way that the drop-targeting blue line is currently implemented when hovering over a shape / starting dropping into a shape:
```
      <svg
        viewBox={`0 0 1 ${1 / mask.ratio}`}
        width="100%"
        height="100%"
        preserveAspectRatio="none"
      >
        <path
          vectorEffect="non-scaling-stroke"
          stroke="yellow"
          strokeWidth="5"
          fill="none"
          d={mask?.path}
        />
      </svg>
```

If we add this `svg` border directly to the existing element then it would cover part of the element content since this adds an inner border, however, if we would add a new svg but into the same existing clip-path, it would be cut off since nothing is visible outside of the clip-path.

What we would need to do is add a new wrapper with exactly the same clip-path around the current mask, and increase and position this new wrapper based on the border width (e.g. if border-width is 5px, increase it by 10px and move it to maintain visually the same position, too). We can then add the border svg (described above) into the wrapper with increased size. The currently existing mask would also be inside the new wrapper element, as a sibling to the border svg.

The structure would be something like this:
```
<IncreasedSizeWrapper clipPath=... width="calc(100% + 10px)" height="...">
	<svg .... ><path stroke="yellow" strokeWidth="5px" .... /></svg>
	<CurrentlyExistingMaskElement .... />
</IncreasedSizeWrapper />
```

This needs to be done in the `DisplayLayer`, note that we are already doing similar positioning for the outer border with the rest of the elements as well.

**Alternatives considered:**
- Thought about just increasing the mask size directly instead of having to create a separate wrapper with a separate svg for the border, however, this would still cover part of the content in the case of media for example.
- Thoughts about using just background color for the wrapper increased in size, but that would not work if the element itself has any opacity -- the background-color would be visible.
- Using `filter: drop-shadow` as an outline. This still requires an extra wrapper, the option described above seems simpler.

**Comment by barklund** [comment]
Hm, that seems like a reasonable solution. The border SVG could also go completely outside the mask, as it doesn't need to be inside it at all, no?

```html
<svg .... ><path stroke="yellow" strokeWidth="5px" .... /></svg>
<NotIncreasedSizeWrapper clipPath="...">
	<CurrentlyExistingMaskElement ... />
</NotIncreasedSizeWrapper />
```

But that's almost to be considered an implementation detail.

Also, have you considered the generated AMP story output - would it just follow the same HTML structure?

**Comment by miina** [comment]
> Hm, that seems like a reasonable solution. The border SVG could also go completely outside the mask, as it doesn't need to be inside it at all, no?

It could be separated as well, yes, just needs to have the same shape, be increased and the position adjusted.

> Also, have you considered the generated AMP story output - would it just follow the same HTML structure?

It should work the same way in the output as well.

**Comment by barklund** [comment]
Alright, let's create a ticket for this and ask @o-fernandez about priority. Feel free to close here.

**Comment by miina** [comment]
Closing the discovery issue, new issue created for implementation: https://github.com/google/web-stories-wp/issues/6171
