### ISSUE TITLE
Prepublish Checklist - Cover image aspect ratio check is incorrect

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5588]
## Bug Description

Currently the check on the cover image aspect ration is too strict, as per discussions:

"Just as long as the cover image has a vertical based ratio it doesn’t need to be 3:4 but 3:4 is ok". 3:4 is recommended to minimize cropping across different stories but I think we can relax this a bit. @o-fernandez  WDYT?

Metadata guidance on cover image:
https://docs.google.com/presentation/d/1WVaS52rned-ZOem_gsGXkPCu48U2tR0osGbQ-P5GxQg/edit#slide=id.g83ffc12890_0_313

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
There's also a [report](https://github.com/google/web-stories-wp/issues/5677#issuecomment-747114360) saying that using the recommended 640x853px size does not work / causes the error to appear.

**Comment by dreamofabear** [comment]
Echoing another report from a partner that a 640x853px cover incorrectly triggers the "Story cover image wrong aspect ratio" error. I just reproduced this on staging with [this cover](https://www.denofgeek.com/wp-content/uploads/2020/12/webstory-soul-cover-image.jpg?resize=640%2C853) from [this story](https://www.denofgeek.com/web-stories/soul-pixar-storytelling-tradition/).

**Comment by dreamofabear** [comment]
@zidianlyu In case you have spare cycles. :)

**Comment by o-fernandez** [comment]
Two options: 

1. Drop this check. I think we just trigger the checklist errors if there's no poster image or the image resolution is too small. In those instances we keep the help text that tells them we want 3:4 aspect ratio. But, no separate check for 3:4. 
2. Alternatively, we loosen up the check to just see that the ratio is portrait and not a landscape image, so 1:1 or anything taller is OK? 

@choumx @samitron7 any preferences?

**Comment by dreamofabear** [comment]
Let's definitely fix the 640x853 bug first, which I suspect is due to simple rounding error.

> Just as long as the cover image has a vertical based ratio it doesn’t need to be 3:4 but 3:4 is ok". 3:4 is recommended to minimize cropping across different stories but I think we can relax this a bit.

I think I'm missing context here -- is this Google guidance? Just requested access to the doc.

**Comment by swissspidy** [comment]
> Let's definitely fix the 640x853 bug first, which I suspect is due to simple rounding error.

Sort of.

The check is is a bit too strict, since but 640x853 is not exactly a 3:4 aspect ratio. 640x853.3333333 would be.

Code is here:

https://github.com/google/web-stories-wp/blob/ed95fb387de1921cd6906980f3c9dd5b7dc9a850/assets/src/edit-story/app/prepublish/error/metadata.js#L122-L133

https://github.com/google/web-stories-wp/blob/ed95fb387de1921cd6906980f3c9dd5b7dc9a850/assets/src/edit-story/utils/greatestCommonDivisor.js#L25

Since 640 and 853 don't actually have a common divisor > 1, it's easy to see how this won't work as expected. There's also no test for `storyCoverAspectRatio()` that operates with these numbers, which explains why this wasn't caught.

Should be able to do something simple like this instead:

```js
const hasCorrectAspectRatio = Math.abs((width/height) - (ASPECT_RATIO_LEFT/ASPECT_RATIO_RIGHT)) <= 0.001;
```

> I think I'm missing context here -- is this Google guidance? Just requested access to the doc.

Indeed looks like it's not that strict.

"We recommend designing the cover image in a 3x4 aspect ratio."

"portrait based ratio (recommended 3x4)"

FWIW, that works okay-ish for us, since WP can easily crop it to 640x853 if it has a portrait based ratio.

**Comment by csossi** [comment]
Verified in QA
