### ISSUE TITLE
Update "My Stories" on Admin menu to align with presentation of All Stories

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5646]
## Feature Description

As a WordPress user, I would expect the “My Stories” link to show only the stories that I have authored. This is how the Mine is interpreted in WordPress Classic view of posts/pages, where clicking Mine causes the view to filter by author.

## Expected Behaviour
Perhaps the label should be “All Stories” instead of “My Stories”. Current “All Stories” takes users to the Classic WP List View, and should be labelled such.

## Steps to Reproduce
1. Select "My Stories" from the main menu
2. It lists all stories, not just ones authored by me

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria (Updated Aug 11, 2021 per comments below)

Everywhere in the dashboard that is labeled as "My Stories" is to be updated to "Dashboard". This includes the WordPress side nav item that reads "My Stories" as well. 
Tests will also need to be updated.

**Comment by BrittanyIRL** [comment]
Looking a little closer at this and I'm not clear what the solution is here. 

We can't really update "my stories" to be "all stories" because "all stories is the classic view (see screen shots). I propose "Stories Dashboard" as a more descriptive title? Thoughts? 
<img width="502" alt="Screen Shot 2021-01-15 at 1 25 57 PM" src="https://user-images.githubusercontent.com/10720454/104775234-40fae600-5735-11eb-80e1-ad426fb139be.png">
<img width="179" alt="Screen Shot 2021-01-15 at 1 25 47 PM" src="https://user-images.githubusercontent.com/10720454/104775239-41937c80-5735-11eb-8f97-94e5d4f11ee5.png">


@o-fernandez @bmattb

**Comment by o-fernandez** [comment]
Yeah, we discussed the "My Stories" terminology in the past. I don't recall the reason we stuck with it, but for now, agree that switching it to "All Stories" wouldn't work given the clash with the classic view. I'd say, let's keep this in the backlog and address if we hear more user feedback, so far it hasn't been an issue - despite the confusing name. 

If we do end up changing it, I think that we could simply call it "Dashboard".

**Comment by swissspidy** [comment]
> Yeah, we discussed the "My Stories" terminology in the past. I don't recall the reason we stuck with it

I think the idea was that most sites are 1-person shops, so "My Stories" would work for them.

> I'd say, let's keep this in the backlog and address if we hear more user feedback, so far it hasn't been an issue - despite the confusing name.

IIRC it has come up before in the forums, so it's definitely something that confuses users.

> If we do end up changing it, I think that we could simply call it "Dashboard".

Strong +1

**Comment by o-fernandez** [comment]
@samitron7 @choumx any opposition to changing the name to "Dashboard" where it currently says "My Stories"? 
It would align with other WP plugins, and I think it makes sense in general.

**Comment by swissspidy** [comment]
@BrittanyIRL Any chance we could get this prioritized accordingly? There's agreement on changing the title etc.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Any chance we could get this prioritized accordingly? There's agreement on changing the title etc.

Sure! hadn't realized this was something that was wanted still since it's been quiet since Jan. Thanks for the tag. 

So, we're doing this: 
![Screen Shot 2021-08-11 at 7 59 34 AM](https://user-images.githubusercontent.com/10720454/129053469-12e2af26-c2a8-4bd7-8368-0213fa6fd556.png)

Where in the WordPress menu it says "My Stories" it's going to say "Dashboard". 


If that's it then I'll go ahead and just move this into the sprint backlog.

**Comment by swissspidy** [comment]
Well, there are more places where it would need to be updated. Example:

![Screenshot 2021-08-11 at 17 04 33](https://user-images.githubusercontent.com/841956/129054135-bc3f680e-cb8d-4f11-9de7-f5fb9058e1d8.png)

Perhaps more.

The string is also referenced a few times in various tests etc., so those need to be updated as welll

**Comment by BrittanyIRL** [comment]
> Well, there are more places where it would need to be updated. 

Thanks, so i guess that's what i'm trying to understand what exactly we're renaming here. 

We're renaming everywhere that says "My Stories" to be "Dashboard", yes?  Sorry if this seems redundant, it's just always small semantic updates that end up causing issues due to assumptions so I'd rather be sure.

**Comment by swissspidy** [comment]
Yep!

**Comment by BrittanyIRL** [comment]
Aces, then yeah we'll get this done. :) thanks, @swissspidy

**Comment by csossi** [comment]
Verified in QA
