### ISSUE TITLE
Code Quality: Refactor Database_Upgrader class

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5668]
## Task Description

Since the class is getting quite complex.

* Introduce new `Migrations` namespace
* Add new `Migration` interface
* Split up upgrade routines into their own classes, implementing said interface

Inspiration: https://github.com/Yoast/wordpress-seo/tree/f997e15c296eea16f55ea242346365b446a8c993/src/config/migrations

**Comment by spacedmonkey** [comment]
I was just about to recommend making this into a series of classes. It is going to take a lot of refactor of the tests...

I don't see the logic in the `Database_Upgrader` class to change that much. This list 
https://github.com/google/web-stories-wp/blob/f5a580f6fad09aac6181b0fb50a229c8723c03a2/includes/Database_Upgrader.php#L60-L74

Would just be a list of class names instead of method names.

**Comment by spacedmonkey** [comment]
This would also follow the pattern we created in Javascript. 

https://github.com/google/web-stories-wp/tree/main/packages/migration/src/migrations

**Comment by schlessera** [comment]
> Would just be a list of class names instead of method names.

I'd also recommend turning it into a class constant array. This will avoid allocating an array in memory to initialize that `$routines` variable every time, even if it is not being used.

**Comment by spacedmonkey** [comment]
> I'd also recommend turning it into a class constant array. 

Good idea!

I think the format of the array could look like this. 

```
 $routines = [ 
 	'1.0.0' => Migration\upgrade_1::class, 
 	'2.0.0' => Migration\replace_conic_style_presets::class, 
 	'2.0.1' => Migration\add_term::class, 
]
```

We can then use the injector / service model, to spin up all the classes with dependencies.

**Comment by schlessera** [comment]
This is not what I meant by "class constant array", but you can combine both approaches.

What I meant was to use a class constant for providing the array, instead of initializing a new array dynamically on each request:
```php
final class Database_Upgrader {

	const ROUTINES = [
	 	'1.0.0' => Migration\upgrade_1::class, 
	 	'2.0.0' => Migration\replace_conic_style_presets::class, 
	 	'2.0.1' => Migration\add_term::class, 
	];
}
```

This way, the array is parsed as source code and encoded into PHP byte code at compile time and automatically provided via the Opcache on each request.

Otherwise, if you do `$routines = [ ... ]`, you're creating a new array, allocating memory and populating the allocated memory with the individual values on each request dynamically at runtime, which is a huge performance hit for what is effectively static data.
