### ISSUE TITLE
Cover Image Issues

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#5677]
Hi,

I am trying to update a cover image but every time I do I seem to add the wrong size or it is a bug. Can someone check this and tell me what the correct size is in pixels so I can get rid of the attached error message.
![Edit Story ‹ Bitcoin Casino No Deposit Bonus — WordPress (13)](https://user-images.githubusercontent.com/45933242/102188929-80d96e00-3ee8-11eb-8a1a-2e7166eea173.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Heya :)

The poster should be at least 640x853px in size. Could also be 1440x1920px or so, as long as it has a 3:4 aspect ratio.

If that still doesn't work, please open a new thread in the [support forums](https://wordpress.org/support/plugin/web-stories/) and provide the links to your story and the image you're trying to add, so that we can better assist you.

**Comment by leem2209** [comment]
Having the same issue. Uploaded an image resized in photoshop to 3:4 ratio and it's wider that the Google stories appears. My image is exactly 640 px x 853 px and it still says it's the wrong ratio.
<img width="1031" alt="Screenshot 2020-12-17 at 00 02 38" src="https://user-images.githubusercontent.com/59296688/102421074-7065e800-3ffb-11eb-9d25-ed664638ffb8.png">

**Comment by DanielCryptoK** [comment]
You are correct that size does not work. I managed to fix mine by uploading an image 1440 x 1920.

**Comment by swissspidy** [comment]
@leem2209 Heya, thanks for letting us know. We will be fixing this in #5588.

Closing for now since the original question has been answered.

**Comment by JOHNTHEFRU** [comment]
The error comes up everytime I click the T for text options. 
![image](https://user-images.githubusercontent.com/69379221/102607562-6558a800-4120-11eb-956f-0d6ae0c2846e.png)

I then get the following error message
![image](https://user-images.githubusercontent.com/69379221/102607700-9df88180-4120-11eb-8667-0506a88455e6.png)

**Comment by DanielCryptoK** [comment]
@swissspidy 

When I try to save an existing story it says failed to update?? Does the below mean anything

Uncaught (in promise) DOMException: Quota exceeded.
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
/wp-admin/post.php?action=edit&post=26193#page=%25226f3e4dc8-e6fa-4a33-b4cc-a91deb4eb06e%2522:1 [DOM] Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"ce920d9e9a">​ <input type=​"hidden" id=​"_wpnonce" name=​"_wpnonce" value=​"c2d47ad995">​
query-monitor.js:366 PHP Errors in Ajax Response
query-monitor.js:379 Object
(anonymous) @ query-monitor.js:379
?v=2.0:6 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
g @ ?v=2.0:6
/wp-json/web-stories/v1/web-story/26193/?_locale=user:1 Failed to load resource: the server responded with a status of 403 ()
?v=2.0:6 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by swissspidy** [comment]
@DanielCryptoK Heya, that could be because of lots of things. There are quite a few errors in that log, reported by Jetpack, Query Monitor, and Web Stories.

> query-monitor.js:366 PHP Errors in Ajax Response
> Failed to load resource: the server responded with a status of 403

In your browser's dev tools (press F12 to open), you should see a few 403 requests in the Network tab. Check the response tab for each request to see some detailed errors.

Also, I highly recommend installing the [Health Check & Troubleshooting plugin](https://wordpress.org/plugins/health-check/) and follow the instructions at https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/#troubleshooting-with-a-specific-plugin to troubleshoot the Web Stories plugin. This will _simulate_ a scenario with all other plugins disabled except for Web Stories. If it works fine in that scenario, we'll know there's a conflict. Note: this does _not_ affect your users or anything, and does _not_ actually disable those plugins. It's safe to use.
