### ISSUE TITLE
Text: Add Corner Radius Support to Highlight Fill for Text

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5715]
## Feature Description

Add support for a user facing corner radius for text highlight fill and set the default value to 2px.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

1. Create or open a new story
2. Add a text box and select highlight fill
3. See that the user can add a corner radius for the highlight fill
4. See that the default value is 2px.

**Comment by maxyinger** [comment]
I'm assuming this is just using the existing corner radius input and just making sure it gets applied to the highlighted text. Just want to verify that here

**Comment by samitron7** [comment]
Yes, use the corner radius.

**Comment by maxyinger** [comment]
@samitron7 for the default corner radius of 2px, we have two options for this behavior:
1) user adds a text element (regardless of text bg mode) it comes in with a 2 px border radius
2) User applies fill/highlight to a text element and the border radius gets updated to 2

I went with approach 1 on for this for the following reasons:
- Once user changes border radius, it doesn't get overwritten by the default value
- More backwards compatible for users with existing stories that have set an explicit border radius on an element
- Having a border radius when there is no highlight or fill has no negative implications or side effects

Was mainly worried about option 2 for the following user flow:
-> User updates corner radius
-> user toggles between highlight/fill/none
-> border radius gets overwritten on every toggle and user has to manually reset it

Let me know which approach you'd prefer. I think theres a general question that keeps coming up which is when we introduce default behavior, should it effect previously created stories/elements?

My personal opinion is it shouldn't because a user could have edited their story to their liking and altering that could cause regressions that they'd need to go back in and fix. I think any default behavior should only be applied to newly added or edited elements to protect users against this scenario.

Curious to get your thoughts on the matter

**Comment by csossi** [comment]
Verified in QA
