### ISSUE TITLE
Media: Reconsider hiding poster images in more places

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5761]
## Feature Description

This is a follow-up to #5546 / #5636.

I keep getting confused by the poster images being hidden in the editor, but visible in the media modal when clicking "Upload".

While I still think the original filter was too board, I think there is room for improvement to find some middle ground for this. Got inspired by VideoPress:

https://github.com/Automattic/jetpack/blob/4c8c953074363f7bec0b0af5bfba3aab1c76a6af/modules/videopress/editor-media-view.php#L88-L141

We should filter the queries in these places:

* `web-stories/v1/media` REST request
* Media grid view
* Media list view

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
FYI @wpprodigy

**Comment by WPprodigy** [comment]
I agree, this makes sense.

`ajax_query_attachments_args` is quite specific for grid view, and as long as `pre_get_posts` targets list view / the uploads page specifically then we'll avoid the earlier problems.

The one downside is that this does make it hard to "manage" these poster images if somebody ever wanted to clean up later though. So that might be worth some consideration.

**Comment by csossi** [comment]
Verified in QA
