### ISSUE TITLE
Telemetry: Transition to GA4

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5767]
## Feature Description

Let's update the opt-in usage tracking to use GA4.

See https://support.google.com/analytics/answer/9744165?hl=en

_For GA4 support in the dashboard settings screen, see #5808_

## Additional Context

Some perhaps useful links:

https://developers.google.com/gtagjs/reference/ga4-events
https://developers.google.com/analytics/devguides/collection/ga4/exceptions

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by blogtutor** [comment]
Hi @swissspidy!  

I see that you gave this a try awhile back, and [had to revert the change](https://github.com/GoogleForCreators/web-stories-wp/pull/6562) because GA4 and AMP didn't play nicely together at the time.

Now that Google has announced that [Universal Analytics will be going away](https://support.google.com/analytics/answer/11583528) next year, are there any plans to get GA4 working with the Web Stories plugin?

Especially since Google will be deleting the historical UA data (which is unbelievable, but that's another conversation), it's now important to get sites switched over to GA4 as soon as possible. 

Thanks!

**Comment by swissspidy** [comment]
@blogtutor Web Stories are powered by AMP. As per https://github.com/ampproject/amphtml/issues/24621, the Google Analytics team still needs to add AMP support to GA4. Once GA4 and AMP work together, there's nothing preventing it from working for stories. At that point we would ensure that it works flawlessly with this plugin. I recommend you to follow https://github.com/ampproject/amphtml/issues/24621 for any updates in this regard.

**Comment by blogtutor** [comment]
Thanks @swissspidy. Appreciate the quick reply.

(It sure would be nice if Google's GA and AMP teams actually talked to each other and coordinated on things like this, especially since UA is being shut down and all the data is deleted next year... sigh. But again, that's another conversation. 😉)
