### ISSUE TITLE
Page Layouts: Use Grid-base Placeholder Images instead of Original Artwork

### ISSUE THREAD

**Issue by carloskelly13** [GoogleForCreators/web-stories-wp#5833]
## Feature Description

Figma designs suggest applying page layouts will replace images with a grid asset.

**[Designs here](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=3187%3A2110)**

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

All images are replaced with grid placeholder assets on page layouts in browsing and applying/saving/publishing.

Note that there is currently parallel work being done (#5899) to convert some image assets to shapes so they won't get replaced to match the figma designs more directly.

**Comment by BrittanyIRL** [comment]
Updated designs here: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=3187%3A2110 

placeholder images should update the existing ones for pages in preview of panel as well as on use of a story.

**Comment by BrittanyIRL** [comment]
Summarizing slack conversation about implementation for 1.3: 

We are going to start with this by swapping out images for a shared grid placeholder as this is the quickest approach for our deadline as we can automate this process. This will need to be OK'd by design once it's demoable.  
This work is contingent on  https://github.com/google/web-stories-wp/issues/5873 but not blocked.

**Comment by BrittanyIRL** [comment]
@zachhale doe this image work? 

![grid](https://user-images.githubusercontent.com/10720454/104474011-cf773800-557a-11eb-8cd2-e044974cecfd.png)

**Comment by swissspidy** [comment]
Optimized version of the above image:

![104474011-cf773800-557a-11eb-8cd2-e044974cecfd](https://user-images.githubusercontent.com/841956/104476194-41be3b80-55c0-11eb-874f-e711f552bd97.png)

**Comment by zachhale** [comment]
Looks fine. Can this get hosted properly for the replaceme domains? Where
does it need to go for that?

**Comment by BrittanyIRL** [comment]
> Looks fine. Can this get hosted properly for the replaceme domains? Where
does it need to go for that?

https://github.com/google/web-stories-wp/pull/5917#discussion_r556422463 

This should answer that! 

I also showed Tad a quick screencast of the grid layout, he's going to update the asset (same dimensions) to have a better contrast, we can do that separately to not hold this process up since he's not free until this afternoon, just a heads up.

**Comment by zachhale** [comment]
> I also showed Tad a quick screencast of the grid layout, he's going to update the asset (same dimensions) to have a better contrast, we can do that separately to not hold this process up since he's not free until this afternoon, just a heads up.

I was also concerned about this. Thank you for passing that along!

**Comment by zachhale** [comment]
While updating the asset to the latest 4x version, I added a small amount of additional logic to calculate the scale on each image to keep the grid consistent on every placeholder image ala the figma.

**Comment by BrittanyIRL** [comment]
> While updating the asset to the latest 4x version, I added a small amount of additional logic to calculate the scale on each image to keep the grid consistent on every placeholder image ala the figma.

Awesome!! I just pulled the PR again and looked, it's gorgeous. Well done.
![Screen Shot 2021-01-13 at 3 40 23 PM](https://user-images.githubusercontent.com/10720454/104519547-d754cd80-55b6-11eb-8482-4b5329fd63bf.png)
![Screen Shot 2021-01-13 at 3 40 12 PM](https://user-images.githubusercontent.com/10720454/104519554-d7ed6400-55b6-11eb-833d-ab2ace0b2be5.png)

**Comment by csossi** [comment]
Verified in QA
