### ISSUE TITLE
Dropdown menu should open upward if its located a near the edge of the design panel

### ISSUE THREAD

**Issue by samitron7** [GoogleForCreators/web-stories-wp#5835]
## Feature Description

The menu in the dropdown should open upward if its located near the bottom edge of the design panel. The menu should not cover the dropdown textfield so that users have context at all time.

This ticket was created based on the temporary solution for #5453. Once this work is complete, we don't need the additional Select animation' text.

This work can be done after Morten’s big panel update is complete. 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
@samitron7  thanks for making this! 

The animation dropdown right now is a custom thing built on parts of existing dropdown functionality in the editor, this issue should clear up when we are able to start using the new design system. We should absolutely be building in tests (when this update happens) for every dropdown in the panel to always expand in the direction it has room for (since the font family one could run into this same issue (as we discussed offline)). 

Having this documented here will be a great way to make sure that this is indeed the case moving forward.

**Comment by BrittanyIRL** [comment]
Foreground animation menu opens up now. This issue should be resolved. Moving to UAT for confirmation. 

![Screen Shot 2021-04-05 at 1 55 27 PM](https://user-images.githubusercontent.com/10720454/113626104-98af3c00-9616-11eb-9a04-a110dbbf832f.png)
![Screen Shot 2021-04-05 at 1 55 20 PM](https://user-images.githubusercontent.com/10720454/113626106-9947d280-9616-11eb-9343-7067073332fe.png)
