### ISSUE TITLE
Can't find a way to set assistive text for a background GIF

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#5842]
## Bug Description

I've added GIF from our gif integration onto a page as background and have no way to set assistive text/accessibility text.

## Expected Behaviour

Should be able to

## Steps to Reproduce

1. Drag gif onto page as background
2. Try to find in the design panel the a11y text field. 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@zidianlyu Perhaps one for you to pick up if you have availability? :)

**Comment by csossi** [comment]
Verified in QA

**Comment by tmagalhaes-huge** [comment]
@swissspidy @o-fernandez Confirming this works. Only thing is, all the panels under "design" were collapsed when I first selected the background image to add assistive text, so it took me a bit of time to understand why it wasn't showing. In the future, is there any way to ensure those panels are expanded? Unless perhaps I had collapsed them manually and it had just saved my preferences.

I'll close this ticket for now since the user can add assistive text to background GIFs.

**Comment by swissspidy** [comment]
> In the future, is there any way to ensure those panels are expanded? Unless perhaps I had collapsed them manually and it had just saved my preferences.

@tmagalhaes-huge Good point. By default all panels are collapsed, with the exception of the layer panels, and all panels in the Document tab. As soon as you interact with them, your preference is saved. So next time you open the editor the state will be preserved.

Since this is unrelated to this ticket (which just added a new panel), please create a new ticket if this default behavior should be rethought.
