### ISSUE TITLE
QA - Upload to Workspace

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#587]
This issue is for testing the Upload to Workspace functionality. Below are steps intended to aid with testing. These are the features covered in this issue:

image drag and upload
Video drag and upload
Multi upload
keyboard shortcut

**[UX](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=3642%3A0)**

**QA Steps**
For each of the upload tests the media files should be added to the active workspace (page) If the media is not uploaded immediately, show the uploading UI.
1. Drag an image from your local file system onto the workspace (page)
2. Ensure the Image is added to the page as background image (follow rule for first image added to Page will be set as a bg image) and the media library.
3. Drag multiple images from your local file system onto the workspace (page)
4. Ensure the images are staggered on the page
2. Drag a video from your local file system into the workspace (page)
1. Copy & Paste an image via keyboard shortcut from your local file system 
2. Copy & Paste a video via keyboard shortcut from your local file system

**Comment by csossi** [comment]
@jauyong 
- "Uploading" UI isn't appearing for longer uploads
- Dragged and dropped a 1.02 MB jpg. Appeared on page rotated and stretched:
![image](https://user-images.githubusercontent.com/16945664/77233342-4a4f0c80-6b7d-11ea-9d6c-714e1eeaab62.png)

- Dragged a video from Win Explorer onto page as background. Video appears like this, rather than taking up the entire background:
![image](https://user-images.githubusercontent.com/16945664/77254852-feae6880-6c39-11ea-8e7e-1e0b83fce43c.png)

**Comment by jauyong** [comment]
Waiting on #231 to file an issue for
> "Uploading" UI isn't appearing for longer uploads

**Comment by jauyong** [comment]
@csossi I'm not able to replicate this. Was this happening consistently for you?
> Dragged and dropped a 1.02 MB jpg. Appeared on page rotated and stretched:

**Comment by jauyong** [comment]
closing this as CUJ testing will cover any required tests
