### ISSUE TITLE
Page Layouts : Text in Page Layouts isn't RTL compatible

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5910]
## Bug Description

Originally reported by @spacedmonkey 

When switching to RTL the page layouts and their associated text aren't transformed to be RTL, so anyone reading those would see the text inverted

## Expected Behaviour

Switching to RTL mode would present all assets, including page layouts, with text reading RTL.

## Screenshots

<img width="214" alt="image6" src="https://user-images.githubusercontent.com/58738530/104375929-2d137200-54f2-11eb-9def-29b02821f651.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
> When switching to RTL the page layouts and their associated text aren't transformed to be RTL, so anyone reading those would see the text inverted

I think this is to be expected, really.

Our templates were designed in the editor, and cannot be simply transformed/flipped to RTL on the fly. Especially since they cannot be translated either. As long was we don't have any localization plans for templates I think this is not possible to fix.

**In other words:** Templates are designed in English, and are meant for usage in English, not in any other language, including right-to-left ones.

Related discussion about translating templates: #4137

**Comment by BrittanyIRL** [comment]
Yeah I think if anything, there should just be some RTL templates designed and if `isRTL` is true then we show those? This doesn't really feel like a bug to me. 

Can we close?
