### ISSUE TITLE
Page Layouts - Prepublish checklist warning presented incorrectly

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#5912]
## Bug Description

Originally reported by @embarks 

Some fonts have some background contrast built-in but still trigger the low contrast warning 
![image2](https://user-images.githubusercontent.com/58738530/104378278-be381800-54f5-11eb-8131-2fba68079777.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by embarks** [comment]
@BrittanyIRL Not sure about this one. I would say it's not really a bug.

The contrast check is showing up here because there's two fonts in use on this page layout. The white one indeed does not meet w3 contrast standards even at its font size, but the contrast is created by the "shade" version of the font layered on top of it. I could potentially add specific checks for fonts based on their names, but very that's maintenance heavy. Every time we add a font we have to check to see if it's "bold" or has some special case associated with this. Obviously, this doesn't scale with user-uploaded fonts, either. 

I think this is an example of the checklist working as intended but giving less than intuitive result. Because of the complex nature of the editor's visual state, it is hard to codify exactly if contrast standards are being broken or not.

It's not ideal to ignore because it might cause some dissatisfaction on the user's side. They can see that there's contrast created by multiple fonts but the recommendation won't go away. Personally, I think that's acceptable because it's still pointing out the w3 standard _correctly_. The white font does indeed not have enough color contrast with its background.

I don't think it's valuable to spend time making the contrast checker more complex by giving it more context to work with and making assumptions about what the user is trying to accomplsih. We won't be able to account for every possible font/bg combo in a creative space where users can arrange things in infinite ways, so I'd recommend framing a discussion around allowing users to clear checklist items in a satisfying way that empowers them rather than it feeling like they are being chastised. For example, we could allow users to manually clear or hide items. I'm interested in knowing what others think about that, or if I'm missing an approach we could take to have more intuitive results on contrast checking with cases like this one.

**Comment by BrittanyIRL** [comment]
Thanks for the detailed explanation here! I'm caught by these two points: 

> They can see that there's contrast created by multiple fonts but the recommendation won't go away. Personally, I think that's acceptable because it's still pointing out the w3 standard correctly. 

I agree with this.

>  I'd recommend framing a discussion around allowing users to clear checklist items in a satisfying way that empowers them rather than it feeling like they are being chastised. For example, we could allow users to manually clear or hide items. 

And I really like this idea. Because you're right that there's just going to be so many possibilities to check against that are mostly just maintenance heavy or don't scale well. 

@o-fernandez Thoughts on this?

**Comment by embarks** [comment]
One thing I was thinking while interpreting the [w3 success standards](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) was the standard makes an exception for "decorative" text, such as images of text, or perhaps this scenario here. We could probably mirror the w3 standard exceptions for our own standards in the prepublish checklist items that deal with accessibility.

**Comment by BrittanyIRL** [comment]
That's a good idea. I'm kind of thinking about how axe handles their text for deviating for decorative text. 
![Screen Shot 2021-02-10 at 3 18 00 PM](https://user-images.githubusercontent.com/10720454/107580014-322c1580-6bb3-11eb-8dc6-1ad0d76dcebd.png)

**Comment by BrittanyIRL** [comment]
![Screen Shot 2021-07-06 at 11 09 17 AM](https://user-images.githubusercontent.com/10720454/124647320-a7da9b80-de4a-11eb-9e4c-2d5a3fffca71.png)


closing because this is no longer relevant.
