### ISSUE TITLE
Change the main background colour of the web stories (HEX#202125)

### ISSUE THREAD

**Issue by Bernietorras** [GoogleForCreators/web-stories-wp#5947]
Would it be possible to modify the main background of the stories? The one that is currently with this code `#202125` and that loads with the following style: `amp-story[standalone]{background-color:#202125!important;position:relative!important}`

Example: https://www.caraibi-shop.com/web-stories/reviews-yoga-mats/

It would be very beneficial to be able to change the background color to be able to offer an image according to the brand that uses the stories. It would even be better if a background image could be set.

I tried to get it to load my corporate color by modifying the `amp-story[standalone]` background-color that appears in the file: /wp-content/plugins/web-stories/third-party/vendor/ampproject/amp-wp/lib/optimizer/resources/local_fallback/v0.css 

...but it seems that the web stories don't use this style sheet.

It would be very interesting to be able to offer the brand's corporate background color.

**Comment by swissspidy** [comment]
Hi there,

The background color of the whole story is defined by the AMP runtime and is not configurable for user experience and accessibility reasons. See https://github.com/ampproject/amphtml/issues/21380 for details.

Since this is a feature request for the AMP format, I'd suggest to comment on that issue or create a new one there if you disagree with that.
