### ISSUE TITLE
Video Optimization: Allow optimizing existing videos

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5984]
## Feature Description

Users should be able to optimize (= compress and eventually also crop) existing videos in the library/story from within the pre-publish checklist.

This ticket is about laying the technical foundation to make this possible.

**Note:** the actual checklist integration is done in #6241

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Any visual UI changes should be behind a feature flag
* There should be a way for QA  to trigger this video optimization for testing, so needs _some_ debug UI
* Implement functionality to process existing videos in a story
* Existing video in story is replaced with optimized video
* Original & optimized video are linked to eventually allow for a "Restore original" functionality
* Media source is added to optimized video to avoid processing already optimized videos
* No file type changes: webm videos stay webm, mp4s stay mp4s

## Implementation Brief

* Add feature flag for pre-publish video optimization (separate from pre-upload video optimization)
* Add baseline functionality to allow processing existing videos
* Upload optimized video to WordPress media library **but leave original untouched**
* In the story, the original video file is replaced with the optimized version
* The attachment metadata or post meta of the optimized video references the original video
  * This allows restoring original video in the future

## Non-Goals

* Any usage of a video in _other_ stories is not affected by this

## Considerations

* A video can be used multiple times in the same story in different ways (e.g. once as background, once partially off-canvas). Can't perform the same cropping on both elements. However, compression could be done for both.

**Comment by spacedmonkey** [comment]
Two things. 

Firstly we could have a button similar to reset poster for regenerate the video. Is this is user opt in feature correct?

<img width="280" alt="Screenshot 2021-01-20 at 16 17 37" src="https://user-images.githubusercontent.com/237508/105203564-2cef2400-5b3b-11eb-8d6c-67d10ce4334b.png">


We will need a bit of post meta attached the video attachment object, so we can discern videos that have and not been already processed. We may also need, a processing state. 

Would be replace the existing file or create a new attachment file?

**Comment by spacedmonkey** [comment]
Seems like it was already thought of - https://github.com/google/web-stories-wp/issues/5983

**Comment by spacedmonkey** [comment]
I have a number of questions on the IB here. 

> Add pre-publish checklist warning for non-optimized videos

I think this should be it's own ticket and handed off to the team working on the pre-publish checklist

> Upload optimized video to WordPress media library but keep original around (could be hidden or something)

Why don't we flip this on it's head. Need the original around, to maintain the attachment id and any references outside of our editor, like the use in a post / page or in a video widget. When we create the optimized version, create this as a hidden child attachment of original attachment but it hidden. 

Another reason we can just replace existing video with a new one with the same name / file location is because of file type, is file type. If the file was called, example.webm and new file is called example.mp4, we would need to run a migration to change the file path, see migration notes below. 

> The original video file is replaced with the optimized version

So if I am editing a story and I optimize a video, it will update all references in the current stories pages to point to the new file location? Is this correct? What if I optimized a video and it appears in multiple stories? Would that migration happen in browser if I open that other story to edit it or what that happen at server level? If it happen at the browser level, then it would need a migration script to run when the editor is bootstrapping. If it is a server level ( PHP ), there is no easy way to find when video is referenced, so we would need to get every story in the database and loop around all of them to find the video attachment url / id to update it. A migration like this, either way is not a small task and should also be it's own ticket, IMO.

**Comment by swissspidy** [comment]
> I think this should be it's own ticket and handed off to the team working on the pre-publish checklist

The whole point of this ticket is to add a pre-publish checklist item to allow users to optimize existing videos.

It's a P3 right now because it won't be a goal for 1.5, but the release after.

> Another reason we can just replace existing video with a new one with the same name / file location is because of file type, is file type.

Good point, but here we would likely not change file type (no transcoding), just compress the video.

However, one thing I forgot here is that we'll want to do cropping as well. See #5985. So that would be a reason not to replace the file.

> So if I am editing a story and I optimize a video, it will update all references in the current stories pages to point to the new file location? Is this correct?

Corect

> What if I optimized a video and it appears in multiple stories?

Other stories are not affected and are not a concern (out of scope)

A big reason here is cropping. Every story will use a video differently, so we can't replace it everywhere.

**Comment by spacedmonkey** [comment]
> The whole point of this ticket is to add a pre-publish checklist item to allow users to optimize existing videos.

Sorry to clean here, I think that adding the pre-publish checklist item and the logic to generate the optimization are two different tasks, meaning we should break this ticket up. This ticket would remain pre-publish checklist ticket ( with a ticket change ) and a new ticket for creating the new optionmation version of the file.

> Good point, but here we would likely not change file type (no transcoding), just compress the video.

I feel like this need to expanded a little in the IB and how that will work. 

> However, one thing I forgot here is that we'll want to do cropping as well. See #5985. So that would be a reason not to replace the file.

So a cropped image would remain the file name of the original file? 

This is not how WordPress core works. When a cropped image is created, then it is given a new file name. A just tested it locally and got this file name
`Screenshot-2021-01-25-at-15.44.09-e1612357713694.png`

> Other stories are not affected and are not a concern (out of scope)

Will this ever be in scope or something we are never going to worry about?

**Comment by swissspidy** [comment]
I'll clean up the ACs and split up tickets if that makes things easier 👍 

> So a cropped image would remain the file name of the original file?

No, the opposite. Quote: _So that would be a reason not to replace the file._

> Will this ever be in scope or something we are never going to worry about?

No, I don't think so.

**Comment by spacedmonkey** [comment]
So cropped videos would get a new file name. That is what I am saying.

**Comment by swissspidy** [comment]
Closing in favor of #6943
