### ISSUE TITLE
Update dashboard context menus

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6102]
Let's use the shared context menu from the design system where our current story menus are. This is ticket #6101 

## Acceptance Criteria 
This will include: publisher logo menus on settings, stories on grid and list view.

Should mean we can remove the contextMenu component from the dashboard entirely.

**Comment by samwhale** [comment]
This issue has been taking longer than we estimated to complete. There was a missing piece that I didn't account for: the animation of the context menu. It was a quick fix, but that delayed this issue from being finished for a couple days.

I should have done the animation work in the creation of the context menu: https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/6410 rather than doing it for this issue. That extra work probably pushed this issue to a `3` or `5`.

This will still be finished by release, but next time I will make sure all work is ready to be worked on before I start the issue. Sorry about that, team.

**Comment by samwhale** [comment]
There's two prs here:
- Settings page context menus: https://github.com/google/web-stories-wp/pull/6439
- Stories page context menus: https://github.com/google/web-stories-wp/pull/6516

**Comment by csossi** [comment]
Verified in QA
