### ISSUE TITLE
Tooltips on button hover

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6104]
The buttons in the design system were created ahead of the tool tip. 
We need to go back and add in a tooltip as a label for the hover/focus styles. 
https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3438%3A125786 

## Acceptance Criteria 
- buttons have a tooltip that appears on hover for square button and icon button types 
- label text matches what screen reader reaches

**Comment by samwhale** [comment]
After working on this I believe that we should not do this ticket at all. Here's the reasons for why I think this should be done outside of the button component.

1. Having a tooltip displayed on `Icon` buttons or buttons without text would be very useful. However, it would be redundant for button's tooltip to display the text that is already displayed in the button.

2. This is not straight-forward implement for every edge case. This hints that we should not add the `<Tooltip />` to the button itself as default behavior.
    a. Buttons may have children which aren't just text (like icons). We'd need to find the aria-label instead of the text content
    b. This gets more complicated if the button has an abstract number of nested children. Although unlikely that it would have more than one nested span, we still would have to traverse those children to grab any/all text that is displayed or aria-labels to display to the user.

3. If we still wanted to do this but not have the button infer the text to display from its children, we could pass in a separate tooltip label as a prop to the button. This API feels clunky though since we could just use the `<Tooltip />` component and keep the `<Button />` API simpler.

4. It's easier to apply a tooltip to a button on a case-by-case basis. Not all buttons need tooltips, and in the events that they do it would be easier to wrap the button with the `<Tooltip />` component that can be styled for any use case. This should be "opt-in" behavior rather than having every button display this redundant behavior.

@barklund what do you think? IMO we should not add this to the `Button` component at the design-system level.

**Comment by barklund** [comment]
I definitely agree with all that. We can just use the tooltip component where applicable. We'd need to control placement anyway, as it will vary with the button. No need to make the button API more complex when wrapping in another component is so straightforward.

**Comment by samwhale** [comment]
Okay cool! @BrittanyIRL should we close this ticket?

**Comment by BrittanyIRL** [comment]
yup! thanks for the discovery here!
