### ISSUE TITLE
Simple border for non-rectangular shapes

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#6171]
## Feature Description
Enable the border panel for non-rectangular shapes with the possibility to add a simple border that supports:
- One border-width value only. If different border values exist before and the user changes that element to a shape, the left border value is used.
- Allows choosing color, including opacity.
- Supports outside border only (as the rest of the elements).

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief
For adding border to the shape, we could use an additional svg with stroke and stroke-width, in a similar way that the drop-targeting blue line is currently implemented when hovering over a shape / starting dropping into a shape:
```
      <svg
        viewBox={`0 0 1 ${1 / mask.ratio}`}
        width="100%"
        height="100%"
        preserveAspectRatio="none"
      >
        <path
          vectorEffect="non-scaling-stroke"
          stroke="yellow"
          strokeWidth="5"
          fill="none"
          d={mask?.path}
        />
      </svg>
```

Since adding a border directly to the existing element would create an inner border instead, we should add a separate element for the border.

We can add a new wrapper (or separate element) with the same clip-path, and increase and position this new element based on the border width (e.g. if border-width is 5px, increase it by 10px and move it to maintain visually the same position, too). We can then add the border svg (described above) into the wrapper with increased size. The currently existing mask could also be inside the new wrapper element, or could be separately as well.

This needs to be done in the `DisplayLayer`, note that we are already doing similar positioning for the outer border with the rest of the elements as well.

The structure could be something like this:
```
<IncreasedSizeWrapper clipPath=... width="calc(100% + 10px)" height="...">
	<svg .... ><path stroke="yellow" strokeWidth="5px" .... /></svg>
	<CurrentlyExistingMaskElement .... />
</IncreasedSizeWrapper />
```

or this:
```html
<svg .... ><path stroke="yellow" strokeWidth="5px" .... /></svg>
<NotIncreasedSizeWrapper clipPath="...">
	<CurrentlyExistingMaskElement ... />
</NotIncreasedSizeWrapper />
```

See the conversation and considered alternatives in more detail [here](https://github.com/google/web-stories-wp/issues/5536#issuecomment-771542974).

**Comment by miina** [comment]
cc @o-fernandez Pinging you here for prioritization and reviewing the feature description.

**Comment by o-fernandez** [comment]
@miina the description looks good. w.r.t. prioritization, I'll mark it as a P2 for now, something we should try to do but not urgent if there are other P1s/roadmap items.

**Comment by miina** [comment]
Tagging @gajasinski just in case to confirm moving forward with the feature and to review the feature description, since this issue has been stale for quite some time.

**Comment by gajasinski** [comment]
IMO this can be prioritized as a P1 now - leads to consistency within the editor. @miina is this currently prioritized in any sprint?

**Comment by miina** [comment]
@gajasinski It's currently not on the Roadmap at all and also not planned for any Sprint. If you can place it somewhere in the Roadmap then we can properly plan it for the sprints of that release

**Comment by miina** [comment]
Moving this to Ready for Sprint but likely won't add it to a Sprint until we have clarity on the Roadmap/release. cc @gajasinski

**Comment by Trapsta** [comment]
@choumx @gajasinski For implementing the border for non-rectangular shapes, I have tried some different solutions all which work to a certain degree but with some shortcomings. Since I have exhausted all of the ideas that I had about implementing this feature without finding a suitable solution, wanted to know if you have any thoughts about how to proceed or if you have any other alternative solutions that I might have missed. Here is a summary of my findings:


|   | Solution  | Features  | Issues  |   |
|---|---|---|---|---|
| 1  | Current solution: separate border SVG element with `stroke`  | - supports transparent border <br /> - simplest solution of the three options   | - Supports only for non-transparent shapes, otherwise the following issues would appear: <br />  1. Leaves some spaces between  the border and element in some shapes <br /> 2. Border and the element overlap making elements with transparency have some 'ghost borders'  |   |
|  2 |  SVG-stroke on the element, needs testing out | - support border for all shapes including shapes with transparency   | - This would require changing the implementation of the shapes from using clipping to using a mask <br /> - The element would not be cut off/clipped and would be clickable outside of the visible shape <br /> - Needs more time to replace using clip-paths with masks <br /> - SVG draws the stroke at the center of the element's boundary with half the stroke width "inside" the shape and no option to specify the stroke position. This will need some "hacks" to get around.  |   |
|  3. | CSS Paint API  | - Most robust and supports most/all shapes & transparency   | - Experimental and low browser support ([caniuse](https://caniuse.com/css-paint-api)) <br /> - Uses more performance and resources  |   |
|   |   |   |   |   |

cc. @miina @barklund

**Comment by gajasinski** [comment]
@Trapsta thanks for laying this out. Can you show me an examples of what #1 would look like?

**Comment by Trapsta** [comment]
@gajasinski `#1` is basically whats implemented in [#9851](https://github.com/google/web-stories-wp/pull/9851 ). Note the spaces between the heart shape and the blob as well as the border showing through the triangle  shape with opacity.
<img width="544" alt="shapes-borders" src="https://user-images.githubusercontent.com/276316/144791982-40f45d20-21cb-4a0d-9a4c-89fd783dfead.png">
<img width="173" alt="shapes-border-opacity" src="https://user-images.githubusercontent.com/276316/144791998-29fad6cc-a2f6-4165-8bd6-a9a7d85ca907.png">

**Comment by gajasinski** [comment]
@choumx @Trapsta thoughts of how much effort it would be to implement #2? The above experience looks unprofessional.

**Comment by Trapsta** [comment]
@gajasinski @choumx this will obviously need more testing out as noted in the table and might have some overlap with #5325  but I believe around 5-8 points give or take. Also might  need to first try it out on a small scale as a PoC to see if any unexpected issues come up from changing the shape's implementation from clipping to masking.

**Comment by miina** [comment]
@Trapsta Let's try it out as a quick proof of concept to see what kind of issues come up that might require extra effort / bring new blockers. No need to make it work perfectly for the proof of concept, just need to confirm it works well for the shape border, and which issues need to get addressed (e.g. clicking "through" the empty area of the shape might be tricky).

**Comment by Trapsta** [comment]
Okay, noted @miina , I will look into that

**Comment by Trapsta** [comment]
@miina @gajasinski from testing out `#2`, my conclusion is largely negative after encountering a potential show-stopper. Issue is  that  SVG considers the stroke which we want to use as the border as part of the mask. Basically how masking works is you have an element and a mask placed on top of it. The mask hides, shows or partially shows the underlying element based on the pixels (color) of the mask. If the pixels at a particular point are say white, it displays the element , if black it hides and if some other color - allows the elements pixel to be visible, but with a certain level of transparency. The deal breaker is that if the border is considered part of the mask , it will be impossible to have some borders in a particular color and also the color of the border won't be always accurate due to interference from the mask.  

This is demonstrated below where if we have a green border(stroke), it is visible albeit with some transparency but if we have a white border, it doesn't show since the mask reveals the underlying element where the pixels are white.

| Green Border | White Border |
|--------|-------|
|   ![Screenshot 2021-12-09 at 17 00 34](https://user-images.githubusercontent.com/276316/145423917-50ebe7b0-a734-417d-8a81-24e584b26796.png)  |  ![Screenshot 2021-12-09 at 17 00 52](https://user-images.githubusercontent.com/276316/145424005-d1bb1627-e7f3-4ffc-8e0c-f23c6eb9b407.png) |

A more interactive example is this codepen https://codepen.io/sdras/pen/d2a9315e310901a3d43ba3bdf8413c65 . Changing the `stroke="#888"` attribute inside the polygon in the mask element to `stroke="#fff"` and might help to remove the `stroke-dasharray="10, 5"` but not necessary. This doesn't result in a white border because the mask reveals the pixels underneath the stroke. 

With that said , we are left with  either `#3` or  going with `#1` but  without transparency unless someone has some alternative ideas we could try out.  @gajasinski , do you think allowing non-transparent shapes to have border and otherwise not is an option?

cc. @barklund @choumx  @bmattb

**Comment by gajasinski** [comment]
adding @agingoldseco and @aaskedall for feedback

**Comment by andrew-askedall** [comment]
Hi miina,

Was trying to comprehend all of the above. It seems like the current way we have paths or .svgs implemented is limiting to what we can do with the stroke. 

Are we only talking about using these strokes for the 12 "Shapes" or any SVG added to the work area? 
I know it's a completely different stack but any ideas on how Figma is able to render these on the fly in the browser? Do we need to think of our shapes differently? 

![image](https://user-images.githubusercontent.com/6991691/146799094-af32e5fb-eaa0-499b-9e4e-c803c99cee1c.png)

**Comment by barklund** [comment]
Two new approaches to try out (in prioritized order):

4. Add the border layer on top of the element (as originally implemented in this PR), but rather than increase the shape size and render a bordered path on both sides of that, instead render a border at the original shape size but at double the width, and then use the original shape as a mask to "punch out" the inside of the border leaving only the outside border (at _half double-width_, thus correct width)
5. Define the border as a path defined by the original shape on the inside and a separately defined shape on the outside and simply render this using `<path fill />` without a stroke. Because this requires extra work (defining the outside shape of the border), this is a secondary option.

**Comment by miina** [comment]
~@barklund I'm temporarily assigning this issue to you since as far as I understand we're currently waiting for Codepen with an example of the suggested approach nr 4.~

Edit: just got the information that the Codepen already exists with that, waiting for Jasper to provide the links.

@Trapsta I know you were trying out something different as well so please leave your final notes and findings here as well.

**Comment by Trapsta** [comment]
Sure @miina.  I haven't yet extensively looked into these pens that Morten was very gracious to spin from the suggestions above but I was able to loosely validate that they  fit into the general solution that we were looking for which is support transparency for both border and shape as well as support for image masks. 

Here are the codepens; (beware of creepy Nicholas Cage placeholders courtesy of Morten 😉)

1. https://codepen.io/barklund/pen/BawPpZw - Renders shape and border in a single svg. Works but not very ideal since incase of an image mask for the shape, image will be an svg element and this might have some side effects.

2. https://codepen.io/barklund/pen/MWEBpxj - This is no. 4 in the suggested options. Border is added as a separate svg. Uses a mix of both clipping and svg mask to implement shape and border.  More ideal and least disruptive since it's accommodates how we currently implement the shape and image masks.

3. https://codepen.io/Trapsta/pen/ZEXjEew  - Also tried using the `Zero Width Tunnel` technique more as an experiment but found it a bit too complex and tasking for the application since it would involve updating the path commands every time the border was updated and also didn't fit very well with some shapes (non-regular polygons).

In conclusion I think we can proceed working with #2. This is what it looks like after a quick test:

| Basic Shape | Shape transparency | Border transparency |
|-------------|--------------------|---------------------|
|   ![Screenshot 2022-01-10 at 16 21 47](https://user-images.githubusercontent.com/276316/148773915-682035d8-54d8-4870-abf6-085401553222.png)          |          ![Screenshot 2022-01-10 at 16 23 13](https://user-images.githubusercontent.com/276316/148773924-7073314e-67bd-4e6f-b481-2077b59ed4ad.png)          |![Screenshot 2022-01-10 at 16 25 06](https://user-images.githubusercontent.com/276316/148773927-96d370d2-8a1f-4a98-80fb-49374e136202.png)                     |

I did find a few minor issues here and there that I shared with Morten e.g. Some shapes had their vertices cut off but I got them to display correctly after playing around with the scaling. This might be because we haven't factored in the mask path transform ratio which is what we currently use to get the viewbox when rendering the svg but I haven't tested this out so it's only speculation. 

![Screenshot 2022-01-10 at 16 37 24](https://user-images.githubusercontent.com/276316/148775213-373413a2-b33f-4e15-b247-ce76f0eed878.png)

**Comment by felipebochehin87** [comment]
Tested against https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/, using PR #9851.

1. Added a heart shape
2. Increased border width value
3. Decrease border width value
4. Updated layer opacity

![image](https://user-images.githubusercontent.com/96055551/150866779-50674ca6-91d4-48a4-a3f8-08c593178861.png)
