### ISSUE TITLE
FTUE: remove version label from workspace

### ISSUE THREAD

**Issue by maxyinger** [GoogleForCreators/web-stories-wp#6191]
**UPDATE: we will remove the version number altogether per chat on 2/4/2021** 

Sam updated the designs since completion of the original ticket. Requested to be updated to look like this:
![Screen Shot 2021-01-26 at 4.03.51 PM.png](https://images.zenhubusercontent.com/5ea0a3e2f739259b2b0b092a/fc75f4e0-0e72-4ace-8d57-0aaf248de6e5)

**Comment by maxyinger** [comment]
@BrittanyIRL just temporarily assigning to you for now so you can prioritize

**Comment by BrittanyIRL** [comment]
Per slack conversation at EOD 2/4/2021 we're going to just use this ticket to completely remove the version number from the canvas instead of fixing the style. 

![Screen Shot 2021-02-04 at 6 04 53 PM](https://user-images.githubusercontent.com/10720454/106975338-982c1f00-6713-11eb-9997-367feb61b5ab.png)
