### ISSUE TITLE
Redesign: Canvas page selection

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6203]
## Feature Description

Update design for page selection rectangle based on [Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=1009%3A4323).

**Note**: This is about what happens when you click on the background element, be it a solid shape or a media element.

- [ ] Update selection shape, thickness, size and corner radius

| Current design | New design |
|-|-|
| ![Screen Shot 2021-02-04 at 22 33 39](https://user-images.githubusercontent.com/637548/106986316-1bac3700-6739-11eb-9fa4-60115e71373c.png) | ![Screen Shot 2021-02-04 at 22 33 34](https://user-images.githubusercontent.com/637548/106986319-1cdd6400-6739-11eb-9e7e-563af14475b4.png) |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
This might be more than 2 points. Currently, Moveable seems to be used for the background, however, it shouldn't really be since rotating, dragging, resizing aren't enabled for the background anyway as for the other elements.

Replacing using Moveable in this case would fix the issue of displaying resize indicators for background even though it can't be resized:
![resizing](https://user-images.githubusercontent.com/3294597/107010531-bf780000-6796-11eb-97ca-f91b6481f4e8.gif)

This issue would then include removing using Moveable for the background element and adding a custom selection indicator instead.

**Comment by csossi** [comment]
Verified in QA
