### ISSUE TITLE
Help Center: Update motion graphics

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6255]
Update to use transparent motion graphics that were recently added to project.

**Comment by maxyinger** [comment]
Mind adding the `Done` tip graphic while we're at this?
https://drive.google.com/corp/drive/folders/1Iabww-Bs6p6kycqeQ0DxYLKkKI5AYjG6

**Comment by embarks** [comment]
@littlemilkstudio since that's just a png icon, I'll use the checkmark SVG icon we already have in design system and update the screens to have the checkmark on a different PR. The file uploads are to `static-site` and changing the `figure` for the `Done` tip needs some code changes pushed to `main`.

**Comment by maxyinger** [comment]
Oh right on. My bad, thought it was a video. (I still don't have access to that google drive folder).

I'll go request access rn
