### ISSUE TITLE
Save page as a custom page template

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#6415]
## Feature Description

As a user I can save the page I'm currently working on, including all elements on the page and their arrangement, as a "Custom page template" which I can apply to new pages. The page template will work just like any other page templates, but should be easily findable and distinguishable. 

Custom page templates are managed globally, similar to Global Color presets, so that all users in the same team/site will be able to use them. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by bmattb** [comment]
- [x] Create the epic (this ticket)
- [x] Confirm the UX
- [ ] Confirm data requirements
- [ ] Identify the changes to the APIs & architect data model appror
- [ ] Infra to build out APIs
- [ ] PROM build out the front end (TBD)

**Comment by aaecheverria** [comment]
Hi @bmattb / @o-fernandez / @barklund 

I'm sharing the Figma file with the MVP proposal we presented today during the hand-off call for the "Save page as a custom layout" feature.
The deliverable includes 4 main items:

**1.** Saving a page as a Custom Layout flows and states. 
**Note:** One of the flows includes the Right Click Menu option, however, we understand this should be implemented once the Right Click Menu ticket is prioritized.
**2.**  Updating the tooltip when hovering on the Template Menu (from Layouts to Templates) and applying the proposed behavior in the Figma File (see states section, annotation # 4).
**3.**  Update the current behavior when applying a custom layout so it instead of **replacing** the page content, it will **add** a new page with the selected layout.
**4.**  Update the Dropdown type in the Uploads panel to the one we are proposing for this ticket (simplified dropdown). 

Figma link: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=7082%3A531386
Please let us know if there are additional comments/questions.
