### ISSUE TITLE
Redesign: Generic radio button component

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6501]
## Feature Description

[See Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [x] Single
- [ ] Grouping

## Additional Context

![Screen Shot 2021-02-23 at 2 33 20 PM](https://user-images.githubusercontent.com/58738530/108897487-27767500-75e4-11eb-956d-d683c41094e9.png)
![Screen Shot 2021-02-23 at 2 33 27 PM](https://user-images.githubusercontent.com/58738530/108897497-2a716580-75e4-11eb-8869-5fe37e674587.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by samwhale** [comment]
Radio group won't be added to the design system. We will keep using the one in the editor for now: https://github.com/google/web-stories-wp/pull/6730#discussion_r592823656. Moving this to done since there will be no radio group added to the design system.

No code that was merged is visible in the app. It is only visible in the design system
