### ISSUE TITLE
Redesign: Update prepublish panel

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6520]
## Feature Description

see [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=1533%3A260040)

- [ ] Make sure it still looks the same

## Additional Context
![Screen Shot 2021-02-24 at 1 43 41 PM](https://user-images.githubusercontent.com/58738530/109049561-7389ee00-76a6-11eb-9bcd-fed55d8bdb6a.png)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
#6730 has an update to the panel title that I need before I can finish styling the headings of the pre publish panel

**Comment by BrittanyIRL** [comment]
@csossi  for testing, we want the same functionality in the pre publish panel as before (clicking on various warnings in the panel will send the user to the offending element). only now instead of the whole chunk of text being clickable it's the title area and the new arrow next to it. If there's no arrow next to a header there is no item to have the user sent to.  

Otherwise following specs in figma: https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=25%3A1312 

This panel isn't actually done in figma 🙃  so for a sanity check, it should look like the below - cleared this with the Huge team.

![Screen Shot 2021-03-26 at 11 25 08 AM](https://user-images.githubusercontent.com/10720454/112681187-93d6d500-8e2b-11eb-81e7-d4c205286c4e.png)
![Screen Shot 2021-03-26 at 11 25 27 AM](https://user-images.githubusercontent.com/10720454/112681188-946f6b80-8e2b-11eb-85ad-06a0ab9150d6.png)

**Comment by csossi** [comment]
For the the items with no arrow (i.e. "Make story longer", "Increase amount of total text"), the text still appears as clickable (hand cursor). It doesn't take the user anywhere, but they could interpret as "broken"

**Comment by BrittanyIRL** [comment]
![fix cursor](https://user-images.githubusercontent.com/10720454/112887172-afd6b280-9087-11eb-9ab5-fa06fa7b6239.gif)

Thanks for the catch, @csossi - update is pushed, should be fixed

**Comment by csossi** [comment]
Verified in QA
