### ISSUE TITLE
WordPress menu overlay new tooltip

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#6581]
## Bug Description

Found here https://github.com/google/web-stories-wp/pull/6566#issuecomment-788133378 . Tooltip should not be overlay by the WordPress menu like this. See screenshot. 

## Expected Behaviour

Tooltip should not be hidden behind menu. 

## Screenshots

![image](https://user-images.githubusercontent.com/237508/109672720-3376af80-7b6d-11eb-974c-3f37d7fd6a94.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by barklund** [comment]
It's actually not because it's hidden behind the menu, it's because we hide all overflow from the editor itself (to avoid other issues).

The simplest fix here would be to simply left-aligned the tooltip, so it stays within the bounds of the editor.

We do the same thing with the tooltip for the local WordPress media tab above - simply left-aligned to avoid this hidden overflow issue:

![Screen Shot 2021-05-10 at 13 43 52](https://user-images.githubusercontent.com/637548/117701911-ccd9c780-b195-11eb-9c85-18383c97e586.png)

Would that be an acceptable solution?

**Comment by swissspidy** [comment]
Sounds acceptable to me. Just need to make sure the alignment is flipped for RTL.

**Comment by spacedmonkey** [comment]
I think this a simple and workable solution.

**Comment by BrittanyIRL** [comment]
I think  #9668 fixes this issue.

<img width="265" alt="Screen Shot 2021-11-09 at 1 58 04 PM" src="https://user-images.githubusercontent.com/10720454/141004631-cd53e82f-adec-4b48-a563-52fd94196ed3.png">
<img width="279" alt="Screen Shot 2021-11-09 at 2 06 28 PM" src="https://user-images.githubusercontent.com/10720454/141004695-5558a83a-1b1c-4ff0-8208-50aa69296d4e.png">

**Comment by miina** [comment]
Closing as this seems to be fixed.
