### ISSUE TITLE
Dashboard: Opening the context menu with keyboard should focus the first focusable item

### ISSUE THREAD

**Issue by samwhale** [GoogleForCreators/web-stories-wp#6679]
## Feature Description

Opening the context menu should focus the first 'focusable' item in the context menu (button or link). Currently a user needs to tab into the menu to focus an item.

## Alternatives Considered

n/a

## Additional Context

This used to happen via `useEffect`, however the effect was interfering with the `useFocusOut` hook in the `StoryGridView`, `StoryListView`, and the `Settings` view (publisher logo context menu). 

It was removed here: https://github.com/google/web-stories-wp/pull/6670/files#diff-4e64e6be1f54bcbbded9bc4053ade1162fd6fb817b8f6c3427f1aa07f888058bL166-L193.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
This is good to fix ahead of context menus in the editor

**Comment by csossi** [comment]
testing the 2nd part:
To test bug that was fixed: MAKE SURE TO CHECK IN FIREFOX, THAT'S WHERE THE BUG WAS BEFORE
1. Go to dashboard
2. Click the context menu button to open the context menu for a story
3. Press Tab to focus an element in the menu
4. Click the Delete story button. A modal should show.

Clicked the context menu. Menu appears:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/90102ce9-0228-425c-b8e9-fa90de8b0814)

From here, if I use arrow key or tab key, I'm taken to the 2nd option "Open In New Tab" - user has to "arrow back" or "arrow up" to get to "Open in editor"

**Comment by samwhale** [comment]
> From here, if I use arrow key or tab key, I'm taken to the 2nd option "Open In New Tab" - user has to "arrow back" or "arrow up" to get to "Open in editor"

So when you open the menu the first item is 'focused' but the focus border doesn't show up since you aren't using keyboard. I updated it so that the focus border shows even when it's not interacted with keyboard initially.

**Comment by csossi** [comment]
Verified in QA
