### ISSUE TITLE
Redesign: Update the buttons based on Figma updates

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6714]
## Bug Description

- The Publish button should have 32px height
- The icons now use quaternary variant.

## Steps to Reproduce

Hover over either the Preview or Save Draft icons at the top right of the editor to enable the mouseover state

## Screenshots

![Screen Shot 2021-03-10 at 1 45 01 PM](https://user-images.githubusercontent.com/58738530/110680806-13677180-81a7-11eb-97b6-db9d00807b01.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Added a question to Slack about it: https://xwp.slack.com/archives/C01ESBB8ZN1/p1616444452044400
In Figma, the icon buttons are smaller than the Publish button so we'll need UX confirmation first.

It also looks like the button style has changed a bit meanwhile (buttons now have border), might make sense to implement that here, too
<img width="621" alt="Screenshot 2021-03-22 at 22 17 13" src="https://user-images.githubusercontent.com/3294597/112054369-c647b000-8b55-11eb-9e8e-ef6eb53468a8.png">

**Comment by miina** [comment]
Looks like the Publish button in Figma has incorrect size instead -- these should all have 32px height based on Sam's comment. The publish button height hasn't been reflected in Figma yet, waiting for final confirmation.

@bmattb I've removed the bug label from this since it was implemented per Figma before and this seems to be an update to UX instead (button variant change + Publish button height change).
