### ISSUE TITLE
Author changes not saving when Co-Authors Plus plugin is activated

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#6715]
## Bug Description

When the [Co-Authors Plus plugin](https://wordpress.org/plugins/co-authors-plus/) is installed and activated, changing the Author of a Story is not retained after saving.

## Expected Behaviour

The user should be able to change the Author of a Story from the Author drop-down in the Editor and click Update. This should update the Author name 1) on the Dashboard, 2) in All Stories, and 3) in the Editor.

## Steps to Reproduce

1) Install and activate the [Co-Authors Plus plugin](https://wordpress.org/plugins/co-authors-plus/)
2) Open a Story in the Editor
3) In the Document tab, change the Author from the current Author to a different Author
4) Click Update
5) Return to the Dashboard - note that the Author name is still listed as the previous Author
6) Reopen the Story in the Editor - note that the Author name is still listed as the previous Author

## Screenshots

Video: https://jmp.sh/DEJYG96

## Additional Context

- Support issue: https://wordpress.org/support/topic/change-author-name-of-webstories/
- Plugin Version: Web Stories 1.4.0 and Co-Authors Plus 3.4.3
- WordPress Version: Tested and verified in 5.7 and 5.6.2
- Operating System: Mac Big Sur 11.2.2
- Browser: Chrome 89

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
I have used the co-author-plus plugin in another project and know it well. Co author plus save author data as a taxonomy, to doesn't play nicely with WordPress core's authoring system. For that reason, to support it, it likely we do need to write a custom integration for it, similarly to sitekit or jetpack. There is a question, if this code should live in this plugin or in the co-author-plus plugin codebase. I will leave this for Pascal to decide.

**Comment by mxbclang** [comment]
@swissspidy Tagging you in on this old issue per Jonny's comment above – can you please update as needed? Thanks!

**Comment by swissspidy** [comment]
@bethanylang Just did a quick test and I don't see any bug per se. It's just a bit confusing.

When using "Co-Authors Plus", one must manage guest authors via the dedicated Guest Authors meta box:

![Screenshot 2021-09-08 at 14 11 49](https://user-images.githubusercontent.com/841956/132507200-0dc1e48b-ea5c-42b3-84d6-f114c97c0391.png)

This meta box takes precedence over the author selection in the Document panel.

This works the same way in Gutenberg:

![Screenshot 2021-09-08 at 14 14 31](https://user-images.githubusercontent.com/841956/132507396-b6bd49cf-cc70-4638-a8f1-85e91b105556.png)

It's confusing since meta boxes are collapsed by default, so you have to actually open it in the editor to see the guest author selection. But it's there.

**Comment by mxbclang** [comment]
Got it, that makes sense and I'll update the user. Closing this issue.

**Comment by abhisekumar** [comment]
Still happening .. Co-author plus plugin not letting  me change the author .

**Comment by swissspidy** [comment]
@abhisekumar Note that you need to change the author in the Co-Authors Plus meta box, _**not**_ in the Document tab. Also note that this issue was closed 2 years ago. Please consider [opening a new support topic](https://wordpress.org/support/plugin/web-stories/) if you are still having issues.

![Screenshot 2021-09-08 at 14 11 49](https://user-images.githubusercontent.com/841956/132507200-0dc1e48b-ea5c-42b3-84d6-f114c97c0391.png)
