### ISSUE TITLE
Not Able to Convert Text Boxes to Text Presets

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#672]
## Bug Description

UX decision, functionality is not broken. 

## Expected Behaviour

1. When I click on a text element it should switch in the element panel so I can choose a text preset.
2. Choosing a text preset while focused on a text element should convert it, not create a new one. 

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@jauyong Could you add a bit more details / the steps for expected behavior for the issue?

From the title, I read out that the issue is not being able to convert the Text Background color to a preset, do I understand correctly? This will be implemented within #279 (style presets)

The expected behavior section, however, seems to be about a different thing.
Do you mean that clicking on the `+` icon while focused should also apply a color? Or do you mean that clicking on a Preset should apply the color to Text Background (that will be implemented in #279 with Style Presets)?

**Comment by jauyong** [comment]
@miina this is referring the text presets shown in the screenshot below and not the color presets. Basically, if I have a text box in focus on the page and then select "Heading" from the presets for example, it should change the text I currently have in focus to the same styling as the "Heading" e.g. Bold, 29 size etc...
Right now, when I click on heading with a textbox in focus, it adds a new textbox to the page. 


![image](https://user-images.githubusercontent.com/5874851/79385010-e3cbcd00-7f35-11ea-8120-9de0f5fa37c9.png)

**Comment by miina** [comment]
Ah, okay, now I understand -- this issue is about Text Presets. Confused it with the Presets in the Design Panel (which are for colors and styles).
