### ISSUE TITLE
Media: No feedback when inserting unsupported file types via WordPress media modal

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6756]
## Bug Description

Sometimes when users try to add a video to a story page by using the Upload button and press "Insert into Page" it doesn't actually do anything

## Expected Behaviour

After the upload completes, and the user presses the "Insert into page" button the video asset should be place on the currently selected page

## Steps to Reproduce

1. In the editor, select the media upload tab
2. Select upload media
3. Upload a video asset via the WP Media upload modal
4. Select "Insert into Story" from the modal when upload is completed.
5. Feel the warmth of your tears as they fall down your face in disappointment.

https://user-images.githubusercontent.com/58738530/110989073-5bb99780-833f-11eb-91bf-f2366fd3c963.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
While we can limit the media modal to only display supported file types, we **cannot** prevent users from uploading an unsupported file there and then trying to insert it.

That's why we have some custom error messaging here:

https://github.com/google/web-stories-wp/blob/dece33a44439b1c9ab5ca1e536a8f8882104f7eb/assets/src/edit-story/components/library/panes/media/local/mediaPane.js#L160-L180

However, this code is never reached because we bail early here:

https://github.com/google/web-stories-wp/blob/dece33a44439b1c9ab5ca1e536a8f8882104f7eb/assets/src/edit-story/components/mediaPicker/useMediaPicker.js#L112-L116

Since we want to restrict users from inserting an unsupported file type **but** have some error message, it might be easiest to add some `onSelectError` callback.

So in `useMediaPicker` we would do:

```js
if (Array.isArray(type) && !type.includes(mediaPickerEl.mime)) {
  onSelectError(mediaPickerEl);
} else {
  onSelect(mediaPickerEl);
}
```

And in `mediaPane.js` we would do:

```js
/**
 * Error callback when failing to insert media element.
 *
 * @param {Object} mediaPickerEl Object coming from backbone media picker.
 */
const onSelectError = (mediaPickerEl) => {
  if (!allowedMimeTypes.includes(mediaPickerEl.mime)) {
    /* translators: %s is a list of allowed file extensions. */
    const message = sprintf(
      /* translators: %s: list of allowed file types. */
      __('Please choose only %s to insert into page.', 'web-stories'),
      allowedFileTypes.join(
        /* translators: delimiter used in a list */
        __(', ', 'web-stories')
      )
    );

    showSnackbar({
      message,
    });
    return;
  }

  showSnackbar({
    message: __(
      'File could not be inserted. Please try a different file.',
      'web-stories'
    ),
  });
};

/**
 * Callback for successfully inserting media element.
 *
 * @param {Object} mediaPickerEl Object coming from backbone media picker.
 */
const onSelect = (mediaPickerEl) => {
  const resource = getResourceFromMediaPicker(mediaPickerEl);

  // WordPress media picker event, sizes.medium.url is the smallest image
  insertMediaElement(
    resource,
    mediaPickerEl.sizes?.medium?.url || mediaPickerEl.url
  );

  if (!resource.posterId && !resource.local) {
    // Upload video poster and update media element afterwards, so that the
    // poster will correctly show up in places like the Accessibility panel.
    uploadVideoPoster(resource.id, mediaPickerEl.url);
  }
};
```

**Comment by swissspidy** [comment]
@spacedmonkey assigning to you for consideration. We need to ensure there is appropriate user feedback everywhere `useMediaPicker` is used.

Perhaps `onSelectError` could be part of `useMediaPicker` itself. There might be other options too.

**Comment by csossi** [comment]
Verified in QA
