### ISSUE TITLE
Excessive CSS output stripped by AMP sanitization

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6783]
## Bug Description

Support topic: https://wordpress.org/support/topic/formatting-distorted-after-publishing/

Related: #5226

It appears that creating larger stories with tons of animations will result in lots of CSS. Enough to go beyond the 75k CSS limit in AMP and causing the built-in sanitizer to remove any excessive CSS before output to ensure AMP validation.

This can cause stories to appear broken as elements might not be positioned as expected.

## Expected Behaviour

No broken stories

No AMP invalidation

## Steps to Reproduce

Not sure, but seems caused by large stories with lots of animations.

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@choumx any thoughts on how we should treat this?

**Comment by swissspidy** [comment]
Making this a P3 since it hasn't come up again, but would be good to find a solution for (even if it just means adding documentation).

**Comment by dreamofabear** [comment]
A couple unorganized thoughts:
- Inline styles don't count against the 75KB limit, which doesn't help much for animations but could be useful for inlining other CSS to increase overall headroom
- I see a lot of room for improvement in our current CSS in general. E.g. a lot of strange repeats of `:root:not(#_):not(#_):not(#_):not(#_):not(#_)` selector and many opportunities for CSS reuse/inheritance
- I'm curious why we decided to use custom keyframes for all animations instead using the attribute-based API (e.g. for delay/duration): https://amp.dev/documentation/guides-and-tutorials/start/visual_story/animating_elements/

**Comment by maxyinger** [comment]
> I'm curious why we decided to use custom keyframes for all animations instead using the attribute-based API (e.g. for delay/duration)

It allowed us to have more cohesion between the in editor animation system using the web animations api and the outputted story. Basically allows us for a single source of truth shared between the two so animations don't deviate from what you see in the editor vs the outputted story.

Also ended up giving us more flexibility. For example, our background animations completely deviate from the amp presets. We initially used a lot of amp code and completely replicated things like pan and zoom straight from the amp presets, but design found them unintuitive and requested different behavior.

**Comment by swissspidy** [comment]
> * I see a lot of room for improvement in our current CSS in general. E.g. a lot of strange repeats of `:root:not(#_):not(#_):not(#_):not(#_):not(#_)` selector and many opportunities for CSS reuse/inheritance

These are added by the PHP-CSS-Parser which moves all the inline styles to `amp-custom` in a way that preserves the specificity, IIRC. @westonruter can clarify. But it's not strange, it does serve a purpose.

**Comment by westonruter** [comment]
Since the AMP plugin primarily has been focused on converting vanilla HTML into valid AMP, it has to process anything that a theme/plugin may throw at it. Originally AMP didn't allow inline `style` attributes, so that is why initially we moved inline styles to `style[amp-custom]`. Nevertheless, there is another key reason to move the styles: themes/plugins may add inline styles which also contain `!important` qualifiers, and `!important` is not yet allowed by AMP. In order to preserve the CSS cascade, we convert inline styles to style rules with high-specificity CSS selectors using the `:not(#_)` hack. When `!important` is present, we multiply the factor of the number of `:not(#_)` selectors to ensure they are original cascade is preserved. You can see some more exploration of this in https://github.com/ampproject/amp-wp/issues/1313.

This all being said, it seems useful to have a way to configure the style sanitizer to bypass the transformation of `style` attributes into `style[amp-custom]` while also bypassing the `!important` property transformations. With these conversions bypassed, the sanitizer would have to strip out the `!important` qualifiers in order to maintain AMP validity. This seems reasonable in the case of Web Stories since you have complete control over the page construction as being AMP-first.

I'll file an issue (https://github.com/ampproject/amp-wp/issues/6295) to implement this. This being said, you can bypass all of overhead of inline styles today by moving all such rules to `style[amp-custom]` in the first pace.

**Comment by dreamofabear** [comment]
> It allowed us to have more cohesion between the in editor animation system using the web animations api and the outputted story. 

Makes sense, though it looks like in some cases our custom curves may have actually turned out less attractive than the STAMP defaults: https://github.com/google/web-stories-wp/issues/7433#issuecomment-845564732. 😅 

Re: AMP plugin, super interesting -- thanks for the context. That change alone should give us a lot of CSS headroom. 👍

**Comment by westonruter** [comment]
> * Inline styles don't count against the 75KB limit, which doesn't help much for animations but could be useful for inlining other CSS to increase overall headroom

@choumx Actually, this isn't the case. Inline styles are included in the total of the `style[amp-custom]` total. I added an `style[amp-custom]` with 75,000 bytes and then added an inline `style` and got:

![image](https://user-images.githubusercontent.com/134745/119249857-ec3b0200-bb50-11eb-8c7a-d88edf347b01.png)

Also confirmed on amp.dev [docs](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/#add-styles-to-a-page):

> Each AMP page has a 75,000 byte CSS limit. Styles defined in the head of the document and inline count towards this limit.

Also confirmed in looking at [`maybeEmitCssLengthSpecErrors`](https://github.com/ampproject/amphtml/blob/e3abe630d3e0bcce78115e0b51d5da776e427904/validator/js/engine/validator.js#L6671-L6679) in the JS validator code.

**Comment by westonruter** [comment]
Nevertheless, I can see the original Web Story has 81,307 bytes in `style[amp-custom]`. 

There are 387 instances of inline style rules, and where each instance such as the following:

```css
:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-6e8beaa{…}
```

This adds 63 chars of overhead versus if the style was inline.

So all added up, this results in 24,381 added bytes of overhead:

```js
Array.prototype.reduce.call(
	document.querySelector('style[amp-custom]').textContent.match(/:root.+?\.amp-wp-\w+/g).map( (s) => s.length + 2 /*braces*/ ),
	( sum, len ) => sum + len,
	0
)
// => 24381
```

However, when style properties are included in the count, the total amount of CSS bytes in the style rules is 81,418 bytes:

```js
Array.prototype.reduce.call(
	document.querySelector('style[amp-custom]').textContent.match(/:root.+?\.amp-wp-\w+{.+?}/sg).map( (s) => s.length + 2 /*braces*/ ),
	( sum, len ) => sum + len,
	0
)
// => 81418
```

Nevertheless, something important to note is that extracting inline styles into style rules can save bytes when the same inline styles are used over and over again since the AMP plugin uses an MD5 hash of the inline style to serve as the class name on the element. The inline styles are _deduplicated_. As it stands right now, there are many duplicate inline styles. There are 87 inline styles for the given story that are duplicates, with 33 which are duplicated more than 3 times:

Count | Inline `style`
------|-------
82 | `pointer-events:initial;width:100%;height:100%;display:block;position:absolute;top:0;left:0`
82 | `width:100%;height:100%;display:block;position:absolute;top:0;left:0;opacity:0`
48 | `color: #fff`
41 | `font-weight: 700; color: #fff`
33 | `width:100%;height:100%;display:block;position:absolute;top:0;left:0;transform:scale(0.15)`
26 | `display:block;position:relative;left:0;top:0;margin:-0.6417253521126767% 0;-webkit-box-decoration-break:clone;box-decoration-break:clone`
22 | `display:block;position:relative;left:0;top:0;margin:0.9049295774647883% 0;-webkit-box-decoration-break:clone;box-decoration-break:clone`
19 | `position:absolute;pointer-events:none;left:0%;top:-9.25926%;width:100%;height:118.51852%;opacity:1`
18 | `font-weight: 700`
17 | `width:100%;height:100%;display:block;position:absolute;top:0;left:0`
8 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:0;font-family:"Merriweather Sans",sans-serif;font-size:0.242718em;line-height:calc(1.5em + 0.5333349813363657em);text-align:left;padding:0;color:#000000;background-color:rgba(24,24,30,0.2);background:none`
8 | `background-color:rgba(24,24,30,0.2);-webkit-box-decoration-break:clone;box-decoration-break:clone;position:relative;padding:1.4084507042253522% 2.8169014084507045%;text-align:left;border-radius:0px 0px 0px 0px;color:transparent`
8 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:0;font-family:"Merriweather Sans",sans-serif;font-size:0.242718em;line-height:calc(1.5em + 0.5333349813363657em);text-align:left;padding:0;color:#000000;background-color:rgba(24,24,30,0.2);background:none;position:absolute;top:0;left:0;right:0`
8 | `background-color:rgba(24,24,30,0.2);-webkit-box-decoration-break:clone;box-decoration-break:clone;position:relative;padding:1.4084507042253522% 2.8169014084507045%;text-align:left;border-radius:0px 0px 0px 0px;background:none`
7 | `width:100%;height:100%;display:block;position:absolute;top:0;left:0;transform:scale(3)`
7 | `top:0;left:0;right:0;bottom:0;width:100%;height:100%;position:absolute;border-width:5px 5px 5px 5px;border-color:rgba(255,255,255,1);border-style:solid;border-radius:0% 0% 0% 0% / 0% 0% 0% 0%;pointer-events:initial;display:block`
6 | `position:absolute;width:133.63706%;height:100%;left:-16.81853%;top:0%`
6 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:-0.5749211356466882% 0;font-family:"Merriweather Sans",sans-serif;font-size:0.242718em;line-height:1.5;text-align:center;padding:0% 0%;color:#000000`
6 | `color: #102740`
5 | `position:absolute;width:317.11712%;height:100%;left:-108.55856%;top:0%`
5 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:0;font-family:"Merriweather Sans",sans-serif;font-size:0.242718em;line-height:calc(1.5em + 0.5333349813363657em);text-align:right;padding:0;color:#000000;background-color:rgba(24,24,30,0.2);background:none`
5 | `background-color:rgba(24,24,30,0.2);-webkit-box-decoration-break:clone;box-decoration-break:clone;position:relative;padding:1.4084507042253522% 2.8169014084507045%;text-align:right;border-radius:0px 0px 0px 0px;color:transparent`
5 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:0;font-family:"Merriweather Sans",sans-serif;font-size:0.242718em;line-height:calc(1.5em + 0.5333349813363657em);text-align:right;padding:0;color:#000000;background-color:rgba(24,24,30,0.2);background:none;position:absolute;top:0;left:0;right:0`
5 | `background-color:rgba(24,24,30,0.2);-webkit-box-decoration-break:clone;box-decoration-break:clone;position:relative;padding:1.4084507042253522% 2.8169014084507045%;text-align:right;border-radius:0px 0px 0px 0px;background:none`
5 | `width:100%;height:100%;display:block;position:absolute;top:0;left:0;transform:rotate(-356deg) rotateZ(-360deg) rotate(356deg)`
5 | `top:0;left:0;right:0;bottom:0;width:100%;height:100%;position:absolute;border-width:3px 3px 3px 3px;border-color:rgba(255,255,255,1);border-style:solid;border-radius:0% 0% 0% 0% / 0% 0% 0% 0%;pointer-events:initial;display:block`
5 | `position:absolute;width:178.37838%;height:100%;left:-39.18919%;top:0%`
4 | `width:100%;height:100%;display:block;position:absolute;top:0;left:0;transform:rotate(-540deg) scale(0.1);opacity:0`
4 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:0;font-family:"Merriweather Sans",sans-serif;font-size:0.323625em;line-height:calc(1em + 0.39999999999999997em);text-align:left;padding:0;color:#000000;background-color:#d74e49;background:none`
4 | `background-color:#d74e49;-webkit-box-decoration-break:clone;box-decoration-break:clone;position:relative;padding:1.4084507042253522% 2.8169014084507045%;text-align:left;border-radius:0px 0px 0px 0px;color:transparent`
4 | `white-space:pre-wrap;overflow-wrap:break-word;word-break:break-word;margin:0;font-family:"Merriweather Sans",sans-serif;font-size:0.323625em;line-height:calc(1em + 0.39999999999999997em);text-align:left;padding:0;color:#000000;background-color:#d74e49;background:none;position:absolute;top:0;left:0;right:0`
4 | `background-color:#d74e49;-webkit-box-decoration-break:clone;box-decoration-break:clone;position:relative;padding:1.4084507042253522% 2.8169014084507045%;text-align:left;border-radius:0px 0px 0px 0px;background:none`
4 | `pointer-events:initial;width:100%;height:100%;display:block;position:absolute;top:0;left:0;border-radius:0% 0% 0% 0% / 0% 0% 0% 0%`
4 | `background-image:linear-gradient(0turn, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0) 100%)`


So for this story in question, there are 387 style style rules extracted from inline `style` attributes but there are _942_ instances of inline styles. These inline styles all added up together total a whopping 118,817 bytes:

```js
Array.prototype.reduce.call( document.querySelectorAll('[data-amp-original-style]'), ( sum, el ) => sum + el.getAttribute('data-amp-original-style').length, 0 )
// => 118817
```

Therefore, it turns out that the AMP plugin's extraction of inline styles to `style[amp-custom]` rules is actually appearing to _save_ a lot on the total CSS.

I suggest that you add a sanitizer which will preemptively move all inline `style` attributes to `style` rules in a way that will bypass how the AMP plugin will make the style rules more specific. This will allow you to omit the 387 instances of `:root:not(#_):not(#_):not(#_):not(#_):not(#_)`.

**Comment by westonruter** [comment]
Here's a mini plugin that implements my proposal: https://gist.github.com/westonruter/7434da70423460179bb2b574d79c53af

When used with the Travel template, it reduces the overall `style[amp-custom]` size from 23,329 bytes all the way down to 15,435—**reducing the total by a third!**

In the resulting stylesheet, instead of there being multiple selectors that take the form of:

```css
:root:not(#_):not(#_):not(#_):not(#_):not(#_) .amp-wp-1234567{…}
```

Each extracted inline style rule now looks like:

```css
._123{…}
```

This is achieved by bypasses the AMP plugin's style sanitizer specificity hacks which are unnecessary in Web Stories.

**Comment by westonruter** [comment]
This should bring the `style[amp-custom]` in the original Web Story in question from 81,307 bytes down to ~60,000 bytes and thus under the 75,000 maximum to be valid AMP.

**Comment by swissspidy** [comment]
Thanks a lot for your thorough investigation and for providing this proof-of-concept sanitizer!

I‘ll happily give this a try in the coming days and test it on some more existing stories to see its effect.

**Comment by westonruter** [comment]
Correction: I forgot that the use of a hash is required in order to ensure that the style rule selectors are stable across pages. So instead of `._123{…}` the rules would look instead like `._c84718f{…}`, where a hash is used instead of an auto-incremented index. I made this change to the mini plugin.

Still, the total CSS size for the Travel template is reduced to 16,101 bytes which is 31% less than the the original. The savings will be increased the more pages a story has.

**Comment by dreamofabear** [comment]
Great analysis, thanks Weston! ❤️

**Comment by westonruter** [comment]
> This will allow you to omit the 387 instances of `:root:not(#_):not(#_):not(#_):not(#_):not(#_)`.

See also https://github.com/ampproject/amp-wp/pull/6312 which would reduce this down to `:not(#_#_#_#_#_)`.
