### ISSUE TITLE
Web Story widget display options don't work as expected

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6791]
## Bug Description

As a user who has added the Web Stories block as a widget in the theme, there are a couple of issues with the display options.

1. Circle Carousel - Display Title - not working
2. Circle Carousel - Cannot select Display Title & Display Archive link concurrently (if this is intentional then the UI might be better as toggle/radio to telegraph this to user)
3. Circle Carousel - Display Archive link not working
4. Grid Carousel - Display title not working, Display Date not working, cannot select multiple display options concurrently (eg show date & sharp corners)
5. Grid Carousel - Display Archive link not working
6. Grid Carousel - Number of Columns - this doesn't work when the widget is used in the blog sidebar area
7. Grid Carousel - Display title not working, Display Date not working, cannot select multiple display options concurrently (eg show date & sharp corners)
8. List - Doesn't' display anything when used as a widget in the blog sidebar area
9. List - cannot select any of the display options concurrently

## Expected Behaviour

Options should work as expected.

## Steps to Reproduce

1. Add the block as a widget to a theme that supports this functionality
2. In the customizer, add the widget to a display area such as the blog sidebar area
3. Note the issues that are detailed above.

## Screenshots

**List view not working** 
![Screen Shot 2021-03-16 at 3 32 41 PM](https://user-images.githubusercontent.com/58738530/111369320-4e691980-866d-11eb-8fc2-075f1aea8c09.png)

**Title display not working**
![Screen Shot 2021-03-16 at 3 35 09 PM](https://user-images.githubusercontent.com/58738530/111369358-5923ae80-866d-11eb-910d-304e5d45657b.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by csossi** [comment]
@swissspidy 

Widget/Sidebar/Grid
Should the options for columns max out at "2" here? I can bring columns down to 1 or 2, but can't generate 3 or 4 columns here. When I try to change from 2 to 3, all I get are smaller thumbnail images (looks like width will only allow a max of 2)

https://share.getcloudapp.com/p9u80lGY

**Comment by swissspidy** [comment]
> @swissspidy
> 
> Widget/Sidebar/Grid
> Should the options for columns max out at "2" here? I can bring columns down to 1 or 2, but can't generate 3 or 4 columns here. When I try to change from 2 to 3, all I get are smaller thumbnail images (looks like width will only allow a max of 2)
> 
> [share.getcloudapp.com/p9u80lGY](https://share.getcloudapp.com/p9u80lGY)

Good point, but widgets can be placed anywhere and we don't know whether there is enough space for 4 or 2 columns. In another theme or sidebar it might work just fine. We offer the maximum of 4 everywhere, so we keep this consistent here.

**Comment by csossi** [comment]
Results here:
Circle Carousel - Display Title - not working
**Fixed**:![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/39d776f5-ad1f-4a82-80ff-bb310b008fa2)
Circle Carousel - Cannot select Display Title & Display Archive link concurrently (if this is intentional then the UI might be better as toggle/radio to telegraph this to user)
**Fixed**:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/4be6626a-719b-4da2-927c-9487243b43a0)
Circle Carousel - Display Archive link not working
**Fixed** - redirected to Archive page
Grid Carousel - Display title not working, Display Date not working, cannot select multiple display options concurrently (eg show date & sharp corners)
**Fixed**:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/ac6240d8-4896-43a5-ac54-d1251304c5b1)
Grid Carousel - Display Archive link not working
**Fixed**: Appearing and redirecting to Archive page
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/7bc03415-be54-42fa-bd52-713bea0e530f)
Grid Carousel - Number of Columns - this doesn't work when the widget is used in the blog sidebar area
(see previous comment re: column widths)
Grid Carousel - Display title not working, Display Date not working, cannot select multiple display options concurrently (eg show date & sharp corners)
**Fixed**. Assuming this was for List. Excerpt, Author, and Date displayed
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/1666a444-a9f7-4235-8f96-9c0bb63323f7)
List - Doesn't' display anything when used as a widget in the blog sidebar area
**Fixed**:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/fe7c1561-6552-4e7d-aad2-02cbf01e164f)
List - cannot select any of the display options concurrently
**Fixed**:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/8839c430-23a4-45a4-aa37-02552713fdf8)

**Comment by csossi** [comment]
Verified in QA
