### ISSUE TITLE
Text Style - entering a negative value into the field sets a random value

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#6792]
## Bug Description

In the Text style panel if a user enters a negative value into the font size field and focusing away changed the value from 32 to 8. 

## Expected Behaviour

I think it shouldn’t allow negatives but then should reset to the original value\

## Screenshots

![image21](https://user-images.githubusercontent.com/58738530/111373322-2203cc00-8672-11eb-9f6a-879c32282f36.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by embarks** [comment]
@BrittanyIRL I'm gonna close this issue out. Checked in with Matt, Tad, and Sam because I think this was a misreported. The ticket indicates the value it changes to is "random" but it's actually always changing back to the minimum font size (8). We'll see this behavior if you go above the maximum font value, it will change to the maximum font size.

So, changing back to the original value introduces a new state we have to track. [Here](https://user-images.githubusercontent.com/41136059/117515582-8a24af00-af4b-11eb-99b6-9e5dc2814676.mp4
)'s a video showing the new state changes: entering a negative value changes the value back to the original, but changing it to a value between 0 and 8 changes it to 8. 

Seems to me more confusing than before, where all values under 8 would change to 8.

I raised this to Matt and design team. Matt didn't have any strong opinions and Tad agreed the new behavior should stay the same. I have a working example attached to the ticket if we want it to behave in this way.
