### ISSUE TITLE
Web Stories - Please Wait

### ISSUE THREAD

**Issue by KStill3333** [GoogleForCreators/web-stories-wp#6851]
## Bug Description

Can you please help with the new updated plugin, now when I click to add any stories I get stuck at "please wait" screen and it goes nowhere.

**Comment by swissspidy** [comment]
Hi there,

Sorry to hear you‘re having issues with the new version. Since we’ve moved support to the WordPress.org support forums, could you please open a new support topic at https://wordpress.org/support/plugin/web-stories/? Include as much information as possible, like WP version, browser version, console errors, Site Health data, etc.

**Comment by LuckynaSan** [comment]
@KStill3333 This issue has been addressed in the newest version of the Web Stories for WordPress plugin. Please update to version 1.6.0 of the plugin and reach out in the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/) if you continue to experience any issues. Thank you!
