### ISSUE TITLE
Jetpack VideoPress Compatibility

### ISSUE THREAD

**Issue by mxbclang** [GoogleForCreators/web-stories-wp#6909]
## Bug Description

A [support user reported that](https://wordpress.org/support/topic/wp-video-files-not-appearing-in-image-browser/) .MP4 videos are not able to be selected or inserted properly in the Editor:

1. Uploaded videos from the Media Library display in the media tab with the All Types filter applied, but when added to a Story, they do not display a play button and cannot be played as videos. 
2. When the Video filter is applied, no videos from the Media Library display.
3. Videos that are uploaded within the Story Editor using the Upload button have the same issues as videos that have already been uploaded via the Media Library.

This user's website is hosted on WordPress.com hosting, which auto-enables Jetpack's VideoPress feature. I was able to replicate the issue in the WordPress.com hosting environment. I was **not** able to replicate this issue on any other hosting environments, even with VideoPress turned on via Jetpack, so this conflict is specifically occurring with VideoPress on WordPress.com hosting. 

## Expected Behaviour

1. Uploaded videos (via Media Library or the Upload button) auto-play when added to a Story
2. When the user clicks away and then re-selects the video and hovers over it, a play button should appear
3. When the user presses the play button, the video should play

## Steps to Reproduce

1. On a WordPress.com-hosted website (requires Business Plan or above to install plugins), install the Web Stories plugin
2. Upload a .MP4 video via the Media Library or Upload button in the Editor
3. In the media tab of the Editor filtered by All Types, click the video screenshot to insert it into the Story. Note that it does not auto-play and clicking and hovering on the image later does not produce a play button.
4. Filter the media tab by Videos and note that the video does not appear.

## Screenshots

Video: https://jumpshare.com/v/KBRRwiK8rcKJHs9qqLIR

## Additional Context

- Plugin Version: 1.5.0
- WordPress Version: 5.7
- Operating System: MacOS Big Sur 11.2.3
- Browser: Replicated in both Chrome 89 and Safari 

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hmm the file type is `video/videopress`, that's very... unexpected 🤔  and probably why this is broken.

All you see is (poster) images, not videos. That's why there is no pay button.

Jetpack/VideoPress adds that mime type as a supported video type here:

https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/videopress/class.jetpack-videopress.php#L292

I think for VideoPress to work well with Web Stories in that case, they'd need to filter `web_stories_allowed_mime_types` too. We could submit a PR to them.

_OR_ we add `video/videopress` ourselves and see if that works.

cc @spacedmonkey for thoughts

**Comment by mxbclang** [comment]
Noting that we got <a href="https://wordpress.org/support/topic/jetpack-wp-video-not-appearing-in-google-web-stories-media-window">another report of this issue</a>, but this user is only using Jetpack for offloading videos via VideoPress and is *not* hosted on wp.com.

**Comment by swissspidy** [comment]
Few observations from debugging on a WP.com site so far:

First, Jetpack filtering `web_stories_allowed_mime_types` alone would not work as we currently reject anything that's not in `wp_get_mime_types()`. But Jetpack doesn't filter `wp_get_mime_types()` (`mime_types` filter), only `get_allowed_mime_types` (`upload_mimes` filter).

Conclusion: we should use `get_allowed_mime_types()` in `Types` here:

https://github.com/google/web-stories-wp/blob/b517f601839efd250400987bb7891b771db69943/includes/Traits/Types.php#L119

Second, the Web Stories plugin wrongly assumes an attachment's `guid` to be the URL to the actual video file. This is not the case for VideoPress. We should use `source_url` instead:

https://github.com/google/web-stories-wp/blob/b517f601839efd250400987bb7891b771db69943/assets/src/edit-story/app/media/utils/getResourceFromAttachment.js#L33

These two changes will make the video properly appear in the editor, but it won't be playable because of the `video/videopress` mime type the browser won't understand.

<img width="1073" alt="Screenshot 2021-04-06 at 19 13 28" src="https://user-images.githubusercontent.com/841956/113751392-3173b380-970c-11eb-95bd-415153c54107.png">


So we'd need the REST API to somehow return the correct mime type here. Not sure about how best to do this part here. That'd be the last remaining piece.

[See an example REST API response here.](https://cmsdevrel.wpcomstaging.com/wp-json/web-stories/v1/media/?media_type=video&_locale=user)

<img width="832" alt="Screenshot 2021-04-06 at 19 12 52" src="https://user-images.githubusercontent.com/841956/113751295-186b0280-970c-11eb-9ea1-b67962d9d557.png">

**Comment by dreamofabear** [comment]
Do we know if WP.com+VideoPress videos are broken in the output/rendered story as well? Or just in the editor?

**Comment by mxbclang** [comment]
@choumx Videos display as still on stories as well. See the second slide here: https://cmsdevrel.wpcomstaging.com/web-stories/31/. This is supposed to be [this video](https://videos.files.wordpress.com/eNX8rOBT/bannerg004_mp4_hd.mp4), but it's displaying as a jpg.

**Comment by spacedmonkey** [comment]
> Second, the Web Stories plugin wrongly assumes an attachment's guid to be the URL to the actual video file. This is not the case for VideoPress. We should use source_url instead:

This seems like a very quick fix on our end. Should I work on this @choumx ?

**Comment by dreamofabear** [comment]
That would be great, though would it be sufficient to fix the output story? Seems we also need to fix or special-case the `video/videopress` MIME type.

**Comment by swissspidy** [comment]
Let‘s fix the guid and get_allowed_mime_types usage.

special case handling should be done in Jetpack, not our plugin.

we can discuss next week if needed

**Comment by spacedmonkey** [comment]
I have created a little PR #7339 to fix this issue. 

I could create a PR for https://github.com/Automattic/jetpack and add a filter in [web-stories.php](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/3rd-party/web-stories.php). 

```
/**
 * Enable videopress support. 
 * 
 * @param array $mime_types Associative array of allowed mime types per media type (image, audio, video).
 * @return array $mime_types
 */
function maybe_add_videopress_support( $array $mime_types ){
     if ( Jetpack_Plan::supports( 'videopress' ) ) {
         return $mime_types;
     }

     $mime_types['video'][] = 'video/videopress';

     return $mime_types;
}
add_filter( 'web_stories_allowed_mime_types', __NAMESPACE__ . '\maybe_add_videopress_support' );
```

Thoughts @swissspidy ?

**Comment by swissspidy** [comment]
> I have created a little PR #7339 to fix this issue.
> 
> I could create a PR for [Automattic/jetpack](https://github.com/Automattic/jetpack) and add a filter in [web-stories.php](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/3rd-party/web-stories.php?rgh-link-date=2021-04-30T10%3A51%3A36Z).
> 
> ```
> /**
>  * Enable videopress support. 
>  * 
>  * @param array $mime_types Associative array of allowed mime types per media type (image, audio, video).
>  * @return array $mime_types
>  */
> function maybe_add_videopress_support( $array $mime_types ){
>      if ( Jetpack_Plan::supports( 'videopress' ) ) {
>          return $mime_types;
>      }
> 
>      $mime_types['video'][] = 'video/videopress';
> 
>      return $mime_types;
> }
> add_filter( 'web_stories_allowed_mime_types', __NAMESPACE__ . '\maybe_add_videopress_support' );
> ```
> 
> Thoughts @swissspidy ?

That is a good start, but won't fully address the issue at hand.

The problem is that the REST API response for videos will have a mime type `video/videoress` instead of `video/mp4`, and the editor cannot handle this (as it's not a known mime type).

As mentioned above, the REST API response will need to be updated accordingly so the editor gets a correct mime type. Ideally that's done on the Jetpack side as well.

**Comment by spacedmonkey** [comment]
@swissspidy What are the next steps with this ticket? Is there anything needed from our end?

**Comment by swissspidy** [comment]
@spacedmonkey We should be able to provide a PR to Jetpack to make the REST API response work.

I will do some brief testing on a VideoPress-enabled site to verify that this is the very last step.

**Comment by spacedmonkey** [comment]
> We should be able to provide a PR to Jetpack to make the REST API response work.

Can you define work? Do you mean return `video/mp4` or similar for the mime type? This might be a breaking change for other intergrations with videopress that area expecting this value. 

Maybe we should fix this in our plugin in our rest api.

**Comment by swissspidy** [comment]
> > We should be able to provide a PR to Jetpack to make the REST API response work.
> 
> Can you define work? Do you mean return `video/mp4` or similar for the mime type? This might be a breaking change for other intergrations with videopress that area expecting this value.
 
Yes. That's why it should only apply for `web-stories/v1/media` responses.

> Maybe we should fix this in our plugin in our rest api.

Sure yeah we can try that too

**Comment by spacedmonkey** [comment]
I did some discovery on this. It was simple enough to tweak our the mime type in REST API request. 

The issue is the tweaking admin ajax as it hard pretty hard to know that we are in the editor. 

@swissspidy Can you add me to that site with videopress can I can debug.

**Comment by swissspidy** [comment]
> The issue is the tweaking admin ajax as it hard pretty hard to know that we are in the editor.

Is this for the media modal? With `web_stories_allowed_mime_types` filtered? What does it look like?

Would it be easier to change the mime type in JS?

**Comment by spacedmonkey** [comment]
> Is this for the media modal? With web_stories_allowed_mime_types filtered? What does it look like?

I can't easily debug this locally, so couldn't tell you. 

> Would it be easier to change the mime type in JS?

Honestly yes, I think it would be, but I have been trying to avoid this. If is hard work at this locally to see what is happening.

**Comment by spacedmonkey** [comment]
@swissspidy Should I still make a PR to jetpack with this? I am not sure it is required anymore..
```php
/**
 * Enable videopress support. 
 * 
 * @param array $mime_types Associative array of allowed mime types per media type (image, audio, video).
 * @return array $mime_types
 */
function maybe_add_videopress_support( $array $mime_types ){
     if ( Jetpack_Plan::supports( 'videopress' ) ) {
         return $mime_types;
     }

     $mime_types['video'][] = 'video/videopress';

     return $mime_types;
}
add_filter( 'web_stories_allowed_mime_types', __NAMESPACE__ . '\maybe_add_videopress_support' );
```

**Comment by swissspidy** [comment]
I think the code is still required in order for the VP videos to be included in the WP_Query.

Let's keep it as-is for now and see whether more adjustments are needed before contributing upstream.

**Comment by doomsdayblaze** [comment]
Hi all, wanted to note that while I can add my video/videopress videos to Google Web Stories, when I do, they have no sound. I'd change them back to video/mp4, but then it ends up breaking a whole bunch of things. Thanks.

**Comment by swissspidy** [comment]
@doomsdayblaze Could you please open a new issue for that so we can take a closer look? A new [support topic](https://wordpress.org/plugins/web-stories/support/) also works. Provide as much information as possible.

This issue is old and not meant to get new replies :-)
