### ISSUE TITLE
Discovery: Separating Popups by Intention

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#6921]
(Initially focused on tooltips) 
We're currently using portals for our tooltips, historically this is because we need tooltips to overflow out of elements in some occasions across the editor and dashboard. With the redesign though we should know that this is still a design choice we need to follow because portals are more expensive than inline elements and if we can avoid them it might be worth it.  The other thing to consider here are the tails, so this whole thing might be unnecessary but we should do a little discovery and know for sure. 

More info: https://github.com/google/web-stories-wp/pull/6887#discussion_r599128462

Fast forward a year from making this ticket and the underlaying popup of the tooltip in the design system has about 19 different props getting passed to it for various edge case scenerios. This is getting really wacky to maintain and is the source of at least 1 regression per month. We can do better. Let's separate concerns. 

This ticket is to do discovery around alternative methods to handle our many many many popup situations (tooltips, context menus, floating menus, footer popups, dropdown menus, color picker...)

**Comment by BrittanyIRL** [comment]
Let's use this issue as discovery to see if we can't find a way to untangle the current 1 popup for everything structure that avalanched in the design system. 

Inline tooltips is one idea, this library might be another: https://floating-ui.com/ 

POC only here. Let's see what we can do to separate tooltips, color picker, dropdowns, menus so we don't have a popup doing insane calculations causing various whack-a-mole variety regressions. (#10928)

**Comment by BrookeGraham** [comment]
Okay, after splitting things up and taking a close look at the `Popup` and all its implementations I have come up with some suggestions. 

We will get the most bang for our buck by pulling `Popup` out of `Tooltip` and just creating it's own portal. It can still share util functions to get  the needed offsets, but would have some additional logic for positioning. Currently `Tooltips` that are used in the Editor, will dynamically set `placement` depending on whether or `RTL` is true. But we then have some functions that check for overlapping with window edges. So we are potentially changing `placement` two to three times when really we could get this down to one. We could solve this by checking for the window edge inside `getOffset` since we would want all `Popup`s to benefit from that.  There are a couple props that are solely used for these `getOffset` mishaps. 

Another bug I found that is currently being "solved" by circumventing `getOffset` is in Dashboard. The `document.body` isn't actually capturing the entire document. 🤷🏻‍♀️ I didn't really investigate whether this is a weird wp constraint or if something is just a bit whacky. BUT if we can solve that, it would make using all the `Popup`s on the Dashboard a lot more straight forward since getOffset needs to use the `document.body` to properly place the popup. 

The new `Layers` panel is also causing some headache. It is getting negative values for some of the positioning. 🤨 By fixing this, we would be able to remove yet another one-off prop. Perhaps has something to due with it using `SecondaryPopup` from the `Editor` 🤷🏻‍♀️

If we wanted to isolate use cases further, creating a `DropdownPopup` might make some sense. The `Dropdown` `Search` and `DataList` all have very similar use cases, feature, and overall feel for the `Popup`. They act close enough to the general implementations of Popup that they are probably fine to leave as is and use the basic `Popup`. There are a few implementation of `Popup` that may make more sense as a `Dropdown`. For instance, Media's `Insertion Menu`, and Media's `DropdownMenu` 

The following components all all have straight forward uses of `Popup`:  `ColorInput`, `PublishTime`, `Text Styles`, `Style Presets`, `PlayPauseButton`, `PageAttachment`,  `Media Input`

**Comment by BrittanyIRL** [comment]
Thanks, @BrookeGraham 

Created this epic: https://github.com/GoogleForCreators/web-stories-wp/issues/11198 based on your discovery here. I figure we can do this piece meal as an incremental improvement.
