### ISSUE TITLE
Blocks alignment issues for layout style

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#6987]
## Bug Description
Noticed some alignment issues in different layouts.

1. ) Single story URL:
Story is cut off on the far right when you embed a single story URL. 

2. ) Box carousel layout:
Poster image cut in half when set to align center

3. ) Grid layout:
Poster image cut in half when set to align center and is a different size than when aligning left/right. 
Border around view all stories cut off when aligning left/right

## Expected Behaviour

Display is not altered upon different alignment settings or layout styles. 

## Steps to Reproduce

Embed a single story URL and change the setting to align right and notice far right of story is cut off.
Select box carousel layour and change setting to align center and notice poster image cut in half.
Select grid layout and change setting to align center and notice poster image cut in half, and displays differently than when setting to other alignment options. Also notice border around view all stories button is cut off as well. 

## Screenshots

1. Single story URL align right:

https://user-images.githubusercontent.com/66372350/113339785-fb43c780-92f8-11eb-9a62-a60da509a609.mov

2. Box carousel align center

https://user-images.githubusercontent.com/66372350/113339839-0eef2e00-92f9-11eb-939a-ad76d7437a7b.mov

3. Grid layout

https://user-images.githubusercontent.com/66372350/113339860-17dfff80-92f9-11eb-9445-393bc39099e7.mov

## Additional Context

Used default Twenty Twenty-one theme

- Plugin Version: 1.5.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Similar bug that we should fix soon too: #7486

**Comment by spacedmonkey** [comment]
What is the expected behaviour here?

### Current Behaviour

![Screenshot 2021-05-14 at 13 23 46](https://user-images.githubusercontent.com/237508/118295174-75a85f80-b4d3-11eb-9ba2-59d39ee0cb64.png)

### Remove clipping and let overflow

![Screenshot 2021-05-14 at 13 27 03](https://user-images.githubusercontent.com/237508/118295272-8fe23d80-b4d3-11eb-92eb-c91ced89695f.png)

### Change the width of story. 
![Screenshot 2021-05-14 at 13 26 12](https://user-images.githubusercontent.com/237508/118295799-26166380-b4d4-11eb-9baf-54cbbb000e4d.png)

**Comment by swissspidy** [comment]
> What is the expected behaviour here?
> 
> ### Current Behaviour
> ![Screenshot 2021-05-14 at 13 23 46](https://user-images.githubusercontent.com/237508/118295174-75a85f80-b4d3-11eb-9ba2-59d39ee0cb64.png)
> 
> ### Remove clipping and let overflow
> ![Screenshot 2021-05-14 at 13 27 03](https://user-images.githubusercontent.com/237508/118295272-8fe23d80-b4d3-11eb-92eb-c91ced89695f.png)
> 
> ### Change the width of story.
> ![Screenshot 2021-05-14 at 13 26 12](https://user-images.githubusercontent.com/237508/118295799-26166380-b4d4-11eb-9baf-54cbbb000e4d.png)

Which configuration is that showing? Box carousel + `alignright`? I might be missing something, but the current behavior here seems alright to me. The theme just limits the max width, so that's a bit out of our control.

But in the editor the "View all stories" is a bit far away from the block content (regardless of alignment).

---

> Select box carousel layout and change setting to align center and notice poster image cut in half.

Setting `left: 0; right: 0` on `.web-stories-list__story-poster img` seems to fix this.

---

Would it help to go through all block types + alignment combinations to compare current vs expected behavior?

**Comment by spacedmonkey** [comment]
> Would it help to go through all block types + alignment combinations to compare current vs expected behavior?

Yes. I think we need to understand what is the expected behavior is. It is worth noting, that other core block acted a little weird when aligned right and left. I am not sure if our block need to act more like the embed block or like an image block.

**Comment by swissspidy** [comment]
@LuckynaSan could you perhaps help us assemble such a list, going through all block types (list, carousel, etc.) and trying to align them & making screenshots?

**Comment by LuckynaSan** [comment]
@swissspidy Here you go: https://docs.google.com/document/d/1JONZ6_SZnsMJcaZgHxQarHJ4cstLPhSpDcd5a1smSwc/edit?usp=sharing 

Let me know if you are not able to view it.

**Comment by swissspidy** [comment]
Screen recording from #7486: https://drive.google.com/file/d/1X6lN7JfA1elqsmfLnKemChwLZqZPPEBn/view?usp=sharing&resourcekey=0-issFtqpbDc1yI_4mZiQ4ew

**Comment by swissspidy** [comment]
Went through the doc above (https://docs.google.com/document/d/1JONZ6_SZnsMJcaZgHxQarHJ4cstLPhSpDcd5a1smSwc/edit) and made sure the team has edit rights. Added comments inline to annotate clear bugs.

The screenshots show the Twenty Twenty-One, but let's make sure the embed experience is consistent in all core themes.

**Comment by swissspidy** [comment]
@spacedmonkey Does the above doc with the inline comments make it clear enough what needs to be fixed?
