### ISSUE TITLE
Default duration time overrules when using a shorter video

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7053]
## Bug Description
When auto-advance is selected the default page duration setting is overridden by the video element and will auto-advance after the video has finished playing. However, if that video is shorter than the default page duration time, then the page does not advance until the default duration time has completed. If the video is shorter than the default page duration time, should the video duration still override and auto-advance?

## Expected Behaviour

The default page duration is automatically overridden by video.

## Steps to Reproduce
- Add a short video to the story
- Set the default page duration to a time that is longer than the video duration
- Preview the story and notice video has finished playing but the page has not advanced

## Screenshots
This [example story](https://testsite.cmsdevrel.com/web-stories/testing-duration/) uses a 6-second video and has the default page duration set to 9 seconds. 
https://user-images.githubusercontent.com/66372350/113608959-3277e880-9619-11eb-86b0-93dbc85cf42a.mov

## Additional Context

Related support topic: https://wordpress.org/support/topic/frame-duration/

- Plugin Version: 1.5.0
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@o-fernandez perhaps you could answer this product question about expected behavior?

**Comment by o-fernandez** [comment]
Per [the spec](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.wstk3e487ewk), if there are non-looping video or audio, the page should auto advance when the longest video/audio on the page finishes playing. 

I think the spec is wrong on animation, since we decided that if the animation length is shorter than the default duration we'd keep the duration, I'll update that. But, for this instance (non-looping video), it is correct to say that we expect auto advance to kick in when the video plays once through. 

@barklund @miina LMK if I got something off here.

**Comment by swissspidy** [comment]
For reference, here's the code where we choose between default duration and video duration:

https://github.com/google/web-stories-wp/blob/796e96c8cf40e295a6933be6f7bf4be0c14dd965/assets/src/edit-story/output/page.js#L41-L48

I think we can just remove the `minDuration` param from `getLongestMediaElement` so that the video always takes precedence.

**Comment by miina** [comment]
Would that mean that if the user adds a very short (e.g. a 1-second video), the Page would auto-advance right after that?

**Comment by o-fernandez** [comment]
> Would that mean that if the user adds a very short (e.g. a 1-second video), the Page would auto-advance right after that?

@miina yes, unless they set the video to loop. But if they have the video to play once through, and there's no other longer video, then that would happen.

**Comment by o-fernandez** [comment]
@miina @barklund updated the priority label here. This has been reported a few times to me already, and hopefully we can fix it soon?

**Comment by miina** [comment]
> This has been reported a few times to me already, and hopefully we can fix it soon?

Sure, moved it up in the list of P2-s.

**Comment by rajpalsaurabh** [comment]
Thanks for prioritising this.

**Comment by csossi** [comment]
Verified in QA
