### ISSUE TITLE
Add page template as new page

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#7063]
## Feature Description

As a general change of functionality of how a page template is added:

* Remove the warning dialog displayed when adding a template
* Instead, add a new page with the page template content and switch to that page as the current page.

~As a special case: If the current page matches the page template **exactly**, do the above as normal but also inform the user, that a new page has been added in a snackbar message. This is to inform users that something is happening every time they click to apply a page template in case they want multiple pages added with the same template.~

Edit: Always display a message that a new page has been added.
---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@barklund Hm, where do the points in the description come from? Maybe something changed since you wrote it? Or is there another link I'm missing? (Tried to find it under the Layouts section but didn't find anything there)

Currently, [in Figma](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7082%3A531898), it says that it should always create a new Page no matter if previously the page is empty or not, and per examples it's always showing a snackbar message, too:
<img width="288" alt="Screenshot 2021-04-27 at 10 09 08" src="https://user-images.githubusercontent.com/3294597/116200172-4b674b80-a738-11eb-9250-789481435653.png">

I'm following how it is in Figma, if it got updated meanwhile then that's probably correct.

Another note -- In Figma is says to set focus on two things at the same time. Since that's not possible then I'm assuming the idea is to select the new Page after adding.

**Comment by csossi** [comment]
Verified in QA
