### ISSUE TITLE
Media modal requires selecting twice

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#710]
## Bug Description

Selecting an asset in the media modal requires two clicks.

## Expected Behaviour

I should be able to select an image the first time around.

## Steps to Reproduce

1. Add new text element with link
1. Click on brand icon placeholder to select image from media modal
1. Media modal opens with `Upload Files` tab open
1. Click on `Media Gallery` tab, choose an image and click on `Select as link icon`
1. ⚠️ Jump back to `Upload Files` tab
1. Click on `Media Gallery` tab **again**, choose an image and click on `Select as link icon`
1. Now it works! Media modal is closed and link icon is applied.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@swissspidy @wassgha 

It doesn't actually require selecting twice, it just triggers opening the media modal twice due to having the `onClick` both on wrapper and on the icon, should be on icon only. It's also fixed in https://github.com/google/web-stories-wp/pull/667:
https://github.com/google/web-stories-wp/pull/667/files#diff-7efe0f7281e890ed858014270c3fd845L157

**Comment by miina** [comment]
Closing as fixed within #667
