### ISSUE TITLE
Incompatibility with AMP Plugin 2.0.x

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7131]
## Bug Description
Invalid markup removed on Web Stories URL in AMP plugin even though Story has no issues.

Example story URL: https://testsite.cmsdevrel.com/web-stories/amptest2/
Source code message displays: 
AMP optimization could not be completed due to the following:
  - CannotInlineRuntimeCss: Cannot inline the amp-runtime CSS in unspecified version: the <style amp-runtime> element is missing.

![Screen Shot 2021-04-07 at 1 28 19 PM](https://user-images.githubusercontent.com/66372350/113908955-23be3c80-97a5-11eb-8eb8-538fbfc3eabc.png)

## Steps to Reproduce

Activate AMP v2.0.11
Create and publish valid Web Story
See validated URLs tab error in AMP 

## Screenshots

Here is a screenshot of messages after removing duplicates:

<img width="674" alt="Screen Shot 2021-04-07 at 12 55 08 PM 1" src="https://user-images.githubusercontent.com/66372350/113906446-46028b00-97a2-11eb-989e-7cc3a6513855.png">

## Additional Context
Related support topic: https://wordpress.org/support/topic/amp-validation-error-index/

Example on another site
Story URL: https://sgsite.cmsdevrel.com/web-stories/beauty-test-1/
AMP Validated URL screenshot: https://jmp.sh/06oX8TO
Error details: https://jmp.sh/NPumHvh
Page source message: 
AMP optimization could not be completed due to the following:
- CannotRemoveBoilerplate: Cannot remove boilerplate because of an unsupported layout: amp-story

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Here's what I am seeing from an eng perspective:

* In the Web Stories plugin we bundle parts from AMP PHP Toolbox and the AMP plugin repo (currently straight from `dev-develop` branch)
* We define `WEBSTORIES_AMP_VERSION` (version of the AMP library included in the plugin), currently set to `2.1.0-alpha`
* If the AMP plugin is newer or equal `WEBSTORIES_AMP_VERSION`, the AMP plugin handles all processing
* **However**, if the AMP plugin is older than `WEBSTORIES_AMP_VERSION` (like in this reported case), we handle sanitization & optimization ourselves because we got the newer AMP spec.

The problem at hand is that we do all the sanitization & optimization ourselves, but the AMP plugin is still doing the validation, obviously with its oder version of the spec.

That's why it flags all these things as invalid. You can see it best when using Web Stories 1.6.0-alpha (so the `main` branch) and AP 2.0.11, and the AMP plugin reports `amp-story-social-share` as a validation error.

When using AMP plugin 2.1.0-alpha, everything works fine.

Hope my explanation makes sense :-)

Now the question is what we can do about it!

I think ideally we'd want the AMP plugin to use our newer version of the spec, but that seems brittle.

Summoning @westonruter to get his thoughts 😇

**Comment by westonruter** [comment]
@swissspidy What about disabling AMP for the `web-story` post type when the installed AMP plugin version is older than the one bundled with Web Stories? This seems to do the trick:

```php
add_filter( 'amp_skip_post', function ( $skipped, $post ) {
	if (
		'web-story' === get_post_type( $post )
		&&
		defined( 'AMP__VERSION' )
		&&
		version_compare( WEBSTORIES_AMP_VERSION, AMP__VERSION, '>=' )
	) {
		$skipped = true;
	}
	return $skipped;
}, 10, 2 );
```

This seems to do the trick.

**Comment by swissspidy** [comment]
Interesting. Yeah I suppose that could work well for us.
