### ISSUE TITLE
Allow custom user roles to have Web Stories publisher/editor rights

### ISSUE THREAD

**Issue by LuckynaSan** [GoogleForCreators/web-stories-wp#7206]
## Feature Description

Allow custom user roles access to publishing/editing rights for Web Stories. 

As requested in this [support topic](https://wordpress.org/support/topic/support-for-multi-vendor-website-running-on-wcfm-by-wclovers-com/#post-14265705), [WCFM plugin](https://wordpress.org/plugins/wc-frontend-manager/) wants to give the Vendor role the ability to create/edit stories. 
## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
We have a few of tickets for such a request already: #5106, #5569, #4102

Since we're using custom capabilities, one can use plugins like https://wordpress.org/plugins/members/ to change which user roles can edit stories.

Full blown user role and capability management is really out of scope for this plugin.
