### ISSUE TITLE
Composer: update autoloader for latest AMP plugin changes

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7336]
## Bug Description

While testing another PR #7292, I updated AMP Plugin and AMP toolkit. After doing this, I started getting error in unit test. 
I locked the commit down composer file to https://github.com/ampproject/amp-toolbox-php/commit/8e1dfacf4f4df8835c6a9ed1d3be8b4a7bf7b92e and https://github.com/ampproject/amp-wp/commit/1bac57aba4e3b58351381b4967ab6ee9b9b00aa6 that this seem to fix this issue. 

## Screenshots
Error in PHPUnit
<img width="832" alt="Screenshot 2021-04-29 at 18 01 32" src="https://user-images.githubusercontent.com/237508/116590464-b1f59080-a915-11eb-8037-554b7aadff39.png">
After commenting out the line above. 
<img width="919" alt="Screenshot 2021-04-29 at 18 03 00" src="https://user-images.githubusercontent.com/237508/116590525-c5a0f700-a915-11eb-8417-fd60298306b0.png">

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
CC @westonruter @schlessera for visibility

**Comment by westonruter** [comment]
You updated the AMP plugin from what version to what version? If `AMP__VERSION` is not defined, then the `amp.php` file wasn't included.

**Comment by spacedmonkey** [comment]
> You updated the AMP plugin from what version to what version?

I noted the shas above, anything passed that commits, as this issue.

> If AMP__VERSION is not defined, then the amp.php file wasn't included.

I do not believe that we ever include this file. If we include this file, would not bootstrap the whole the amp plugin our plugin.

**Comment by westonruter** [comment]
> I noted the shas above, anything passed that commits, as this issue.

But what was the version you were on before?

**Comment by spacedmonkey** [comment]
These are the shas that were in the lock file. 
> ampproject/amp-toolbox-php@8e1dfac and ampproject/amp-wp@1bac57a

Which is why I locked down to them.

**Comment by swissspidy** [comment]
The stack trace is pretty straightforward:

We call `amp_is_request()`, which in turn calls `amp_is_canonical()` and ultimately `AMP_Options_Manager::get_options()`. If the AMP option is missing, `AMP_Options_Manager::$defaults` is used, which uses the `AMP_VERSION` constant.

But why is `amp_is_request()` even available in unit tests?! We specifically added `amp-helper-functions.php` to `exclude-from-files` in our composer config to ensure it's _not_ available.

Well, the reason is https://github.com/ampproject/amp-wp/pull/6070. The amp-wp autoload config was changed in that PR, which means we need to update our `exclude-from-files` config too.

So the solution is quite simple:


Change the composer config as follows:

```json
{
    "exclude-from-files": [
      "ampproject/amp-wp/includes/bootstrap.php"
    ]
}
```

Then requiring `"ampproject/amp-toolbox": "^0.5.0"` and `"ampproject/amp-wp": "dev-develop"` works like a charm.
