### ISSUE TITLE
Page background should allow opacity

### ISSUE THREAD

**Issue by dvoytenko** [GoogleForCreators/web-stories-wp#739]
## Bug Description

Per Figma page background color allows opacity. That might mean that we have to force underlying story color to #fff for output.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #693

**Comment by wassgha** [comment]
#693 Closes this but the underlaying background is the checkerboard pattern (see below), which in my opinion should force users to choose a color instead of leaving it up to us to decide. To be clear, this only happens when the user changes the opacity of the background element, whether it be a solid shape, an image or a video. The default background is still white (same as it is now).

<img width="1069" alt="Screen Shot 2020-03-24 at 1 04 25 AM" src="https://user-images.githubusercontent.com/591655/77402140-6fa16d80-6d6b-11ea-8ccc-701cec9b76c0.png">

Let's check with @samitron7

**Comment by jauyong** [comment]
Noted in sprint 26 sheet

**Comment by samitron7** [comment]
I personally don't like the thought of having an opacity option for the page. It's there for UX legacy reason but I think it's time that we do away with it (@pbakaus are you on board with this?) Unless someone can think of a good use case for this or an an awesome effect you can only achieve with allowing page opacity to be anything but 1.

**Comment by samitron7** [comment]
Just chatted with Paul and we are removing the opacity option from the page!

**Comment by dvoytenko** [comment]
@wassgha, so it looks like my bug report was wrong 😨 . We don't need opacity for page background color after all. @samitron7 is updating Figma.
