### ISSUE TITLE
Font Rendered Differently in Preview vs Canvas

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#743]
## Bug Description

Created text with font settings as you see here:
![image](https://user-images.githubusercontent.com/5874851/77441484-dc465780-6dbf-11ea-8fcc-c553d5f0f60d.png)

Font looks different when Previewing:
![image](https://user-images.githubusercontent.com/5874851/77441503-e36d6580-6dbf-11ea-8ac2-27b72eb68725.png)

Taken from Claudio in #576
Note: Text in the canvas does update when you change the font.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
This is not a bug it is an enhancement. The dropdown has never implemented a preview of the font. It just list the font name in the system font. 

Should we be working on this?

**Comment by swissspidy** [comment]
@spacedmonkey Ignoring the dropdown for a second, the text on the canvas is not using the same font in both screenshots.

**Comment by dvoytenko** [comment]
Related issues: #922, #923, #921.

**Comment by spacedmonkey** [comment]
Related: https://github.com/google/web-stories-wp/issues/1007

**Comment by miina** [comment]
The issue with fonts is partly improved via #1098, however, the text being in 2 lines vs 1 line is not fixed there.

@barklund @dvoytenko Tagging you since Morten had a potential idea for 1-line vs 2-lines issue and since Dima created the data pixels system.

If I understood the idea of Morten then an option could be directly saving line breaks into the markup, however, there seem to be more potential issues with Text element sizes, for example:
The height calculated in `usePresubmitHandler` in `StylePanel` after changing the font size of the element from the design panel in some cases doesn't match the actually required height of the element and even though the text is on two lines, the element height is calculated for one line only:
<img width="747" alt="Screenshot 2020-04-08 at 13 15 24" src="https://user-images.githubusercontent.com/3294597/78778375-75b66180-799b-11ea-9640-d663d5464837.png">

Changing the font size:
![font-size](https://user-images.githubusercontent.com/3294597/78778548-be6e1a80-799b-11ea-88ff-d45909a6c347.gif)

Any thoughts on the potential underlying issue?

**Comment by barklund** [comment]
> If I understood the idea of Morten then an option could be directly saving line breaks into the markup, however, there seem to be more potential issues with Text element sizes, for example:
> The height calculated in `usePresubmitHandler` in `StylePanel` after changing the font size of the element from the design panel in some cases doesn't match the actually required height of the element and even though the text is on two lines, the element height is calculated for one line only.

That is the precise issue if been struggling with locally. I'm unfortunately not near a solution, as I can't really figure out a good way to structure this without too much work going on every whenever a text field renders (I have something that "works", but requires watching all text fields and continually slightly adjusting them whenever something changes, which is horrible and not really useful in the rendered story).

@dvoytenko, I think my whole idea isn't panning out here and I'm anxious to hear your thoughts.

**Comment by dvoytenko** [comment]
@miina @barklund the specific problem in Miina's video, I think, is a measurer bug. I'll try to look into it first thing tomorrow morning. It's possible that given different rounding rules it'd be impossible to reliably have auto-scaling and correct height, in which case we'd have to do some form of "soft line breaks". But I'd rather first ensure that it's not just a measurer bug.
