### ISSUE TITLE
Database Upgrade Routines

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#754]
## Feature Description

Now that we're reaching a point where we store more and more data outside the single story and within wp_options, we need to have a robust mechanism for doing database upgrade routines. Just like the story migrations we have, but for the DB.

In essence, we need a new constant in PHP, e.g. `WEBSTORIES_DB_VERSION`, with an incremental number. This db version is then stored in wp_options, and whenever `WEBSTORIES_VERSION` is higher than what's in the DB, we need to run our upgrade routines.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
Within this issue we would just create the (base) logic / structure for migration, without having any actual migration happening.  It would be good to add a class for doing migrations which would run a list of migrations if the version numbers differ. Initially, the list of migrations would be empty, the migrations would be added within PR-s which actually need migrations.

Logic from the FE for reference:
https://github.com/google/web-stories-wp/blob/d28447dbfacfac4533102966f9b5de25bcfc09c9/assets/src/edit-story/app/story/effects/useLoadStory.js#L77-L78

https://github.com/google/web-stories-wp/blob/d28447dbfacfac4533102966f9b5de25bcfc09c9/assets/src/edit-story/migration/migrate.js#L64-L76

@swissspidy Please add any relevant information if I missed anything.

**Comment by spacedmonkey** [comment]
I have done some research into what other popular WordPress plugins. 
- [Yoast WordPress database upgrader](https://github.com/Yoast/wordpress-seo/blob/6f5e2eb2c851b5b1d515e0109306ccdb11942e03/inc/class-upgrade.php). 
- [BBPress Database upgrader](https://github.com/bbpress/bbPress/blob/afa6030c3e27c4fe582743074a603d25b5e4de48/src/includes/core/update.php#L278).
- [BuddyPress Database upgrader](https://github.com/buddypress/BuddyPress/blob/3790f7e44122af86fd2ee9b131fa4b133d11f41f/src/bp-core/bp-core-update.php#L174).

All of these above example seem to work well and are hooked into `admin_init` meaning that the upgrade only really happens when a user logged into the CMS. 

To be clear, this database migration should only ever be used for upgrading global settings and never used to update existing stories. Any upgrade of stories would have to be a different upgrade path, as it would need to batch migrate stories in a scalable way. Simple to how the [split term migration](https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/) was done in WordPress 4.2.
