### ISSUE TITLE
Lack of upload permission checks for contributors

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7755]
## Bug Description

When clicking on select poster image no error message is shown and user is able select poster image to dismiss prepublish check list item. See video 

## Expected Behaviour

UX to confirm.

## Steps to Reproduce

See video. 

## Screenshots

https://user-images.githubusercontent.com/237508/119808421-028fe780-bedc-11eb-8eb5-176bddc3beb3.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
I assume this also applies to video caption and video poster upload fields, as well as the link icon upload field?

@aaecheverria Curious to hear your team's thoughts on this.

In WordPress, not every user might have the capability to upload media. That's why we currently show a "You don't have access to upload images" dialog when clicking on the Upload button in the media library.

As you can see in the video above, the same dialog is currently missing for other areas of media upload.

There seem to be two options to fix this:

1. Show this dialog for _all_ upload buttons in the editor (like for the media library)
2. Remove all upload buttons if the user does not have upload permission

I would suggest the latter, because it doesn't make sense to show an option the user can't use anyway.
Users without such permission are already aware of this fact, since they can't access Media management in WordPress in general. Nor do they see upload buttons in Gutenberg.

So removing the Upload button would make this experience consistent throughout the WP admin area.

**Comment by spacedmonkey** [comment]
I wonder if we can tweak the media picker to not show the upload tab at all if the user does not have rights to access this.

**Comment by swissspidy** [comment]
> I wonder if we can tweak the media picker to not show the upload tab at all if the user does not have rights to access this.

AFAIK there's only a single [`upload_files`](https://wordpress.org/support/article/roles-and-capabilities/#upload_files) cap for media access. Without it, you can neither upload nor manage media (there's no Media admin menu item).

**Comment by spacedmonkey** [comment]
You are right, in gutenberg, contributors can not select videos or pick featured media. 

<img width="283" alt="Screenshot 2021-05-27 at 12 11 11" src="https://user-images.githubusercontent.com/237508/119816641-daf14d00-bee4-11eb-9481-43068bb4ab74.png">
<img width="652" alt="Screenshot 2021-05-27 at 12 11 38" src="https://user-images.githubusercontent.com/237508/119816646-ddec3d80-bee4-11eb-831b-0360b5fd6fa5.png">

I guess this is where https://github.com/google/web-stories-wp/issues/471 would come in.

**Comment by swissspidy** [comment]
@aaecheverria Something I forgot to repeat from the original report and would like to stress out:

There are pre-publish checklist items like "missing story poster" or "missing video poster" that say "Add poster image". But the user might not have the permission to actually add/upload these poster image.

What should we do in this case?

cc @o-fernandez

**Comment by swissspidy** [comment]
More areas where this is confusing:

Users with the "Contributor" role are shown options to edit and delete items in the media library on the left hand side, but because they don't actually have permissions to do that it doesn't work of course.


https://user-images.githubusercontent.com/841956/119869314-5fad8c80-bf20-11eb-933f-4f7e2a0ddb29.mov

**Comment by spacedmonkey** [comment]
> Users with the "Contributor" role are shown options to edit and delete items in the media library on the left hand side, but because they don't actually have permissions to do that it doesn't work of course.

This seems like a simple fix, just hide those options for Contributor. Should we create another ticket for this?

**Comment by swissspidy** [comment]
> > Users with the "Contributor" role are shown options to edit and delete items in the media library on the left hand side, but because they don't actually have permissions to do that it doesn't work of course.
> 
> This seems like a simple fix, just hide those options for Contributor. Should we create another ticket for this?

Created #8221

**Comment by swissspidy** [comment]
Let's go with the following:

1. Remove/Hide all upload buttons if the user does not have upload permission
2. Remove `MissingUploadPermissionDialog`

**Comment by csossi** [comment]
Verified in QA
