### ISSUE TITLE
Publish time displaying incorrectly when site and user timezones don't match

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#7780]
## Bug Description
Currently, the publish time is not converted properly to/from the local time when displaying/saving the time in the calendar.

## Steps to Reproduce
First make the site and user timezone not match, for that go to the Settings menu and change the Timezone value to something that is not your current timezone.
1. Change the publish time in the calendar.
2. Save and refresh the page
3. See the time has changed

## Screenshots
![time](https://user-images.githubusercontent.com/3294597/120157100-f0bb8680-c1f2-11eb-9f6d-ddaa2c40d8b4.gif)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
@swissspidy We might need to get the timezone value from the config here perhaps? Or should the date be converted to the correct timezone based on the Timezone setting value already in PHP? Thoughts?

**Comment by swissspidy** [comment]
I'll have to take a closer look to see what the culprit is, but at first glance I can say that using `new Date()` in the `DateTime` / `DatePicker` components is tricky because this uses your computer's  timezone, not the timezone configured in WP.

**Comment by miina** [comment]
> I'll have to take a closer look to see what the culprit is, but at first glance I can say that using new Date() in the DateTime / DatePicker components is tricky because this uses your computer's timezone, not the timezone configured in WP.

Note that this issue is happening without the use of `new Date()` in the `DateTime` as well, on current `main`.

I wonder if it would make sense to ensure the correct time in the backend considering the editor would eventually be independent of WP. I think that Gutenberg is using UTC offset value received based on the General Settings and uses this to adjust the time. The time correction is done in React (as far as I saw quickly checking). If we want the editor to be as independent of WP as possible, then perhaps we should assume that the time received from the backend is already correct instead of using the WP settings (Timezone) value in the FE?

**Comment by swissspidy** [comment]
> Note that this issue is happening without the use of `new Date()` in the `DateTime` as well, on current `main`.

On `main` I see multiple  uses of `new Date()`:

https://github.com/google/web-stories-wp/blob/77e85bc500f148c7c18e0c7b5f547a136099119b/assets/src/edit-story/components/form/dateTime/dateTime.js#L51

https://github.com/google/web-stories-wp/blob/77e85bc500f148c7c18e0c7b5f547a136099119b/assets/src/edit-story/components/form/dateTime/datePicker.js#L33

> we should assume that the time received from the backend is already correct instead of using the WP settings (Timezone) value in the FE?

Agreed to this part.

With this bug, I don't think the issue is with the backend though, but with the frontend not setting the correct timezone.

Just tested the following scenario:

Local time: 16:49 (CEST)
UTC: 14:49
Local timezone: Europe/Zurich
Server timezone: America/New York
Server time: 10:49 (EDT)

1. Create new story
2. Set publish date to yesterday, 10:49 EDT
3. Publish story
3. The `date` in the request body is `2021-05-30T08:49:00.000Z`, so that's 08:49 UTC, not the expected 14:40 UTC or 10:49 EDT.
4. Reload editor, see publish time 04:49 -> so that's the 08:49 UTC with the 4hr subtraction to get the EDT date.
5. Go to "All Stories", also see that the date is set to 04:49, not 10:49
6. Check database, see `post_date` is `2021-05-30 04:49:00`

Doing the same thing in Gutenberg, 10:49 stays 10:49 throughout. In the database, the blog post's `post_date` is stored as `2021-05-30 10:49:00` as well.

The issue is with step (3), the `date` should have been set to `2021-05-30T14:49:00.000Z`.

My guess regarding `new Date()` was that this is where the datepicker takes the `10:49` time (thinking it's my local Zurich time) and makes it UTC by subtracting 2hrs.

Instead, the datepicker should treat the `10:49` as EDT from the beginning.

----

Aside:

Showing the timezone in the datepicker like Gutenberg does would be helpful

![Screenshot 2021-05-31 at 16 56 44](https://user-images.githubusercontent.com/841956/120212037-d1901980-c231-11eb-98a0-a1a5eabfe9a7.png)

**Comment by miina** [comment]
> My guess regarding new Date() was that this is where the datepicker takes the 10:49 time (thinking it's my local Zurich time) and makes it UTC by subtracting 2hrs.

Yep, looks like that's what's happening. 

> Showing the timezone in the datepicker like Gutenberg does would be helpful

This would assume timezone information in addition to the date of the story. But yep, if we'll be showing a time that's different from the local time, would be useful to show the timezone, too.

An alternative to displaying the timezone next to the time could be converting the time from `date` to local time and for saving, from local back to the timezone it was. So that the user would see the local time only. Thoughts?

**Comment by swissspidy** [comment]
> This would assume timezone information in addition to the date of the story. But yep, if we'll be showing a time that's different from the local time, would be useful to show the timezone, too.

The timezone info could be displayed like this:

```js
import { format } from '@web-stories-wp/date';

format(date, 'T'); // Timezone abbreviation. Examples: EST, MDT.

format(date, 'e'); // Timezone identifier. Examples: UTC, GMT, Atlantic/Azores.
```

Gutenberg shows the abbreviation in the picker, and the abbreviation+identifier in a tooltip.

> An alternative to displaying the timezone next to the time could be converting the time from `date` to local time and for saving, from local back to the timezone it was. So that the user would see the local time only. Thoughts?

In this case the UX would differ from what users are familiar with in Gutenberg. Consistency is preferable here IMO.

Plus, it seems to be safer to avoid any additional timezone conversion wherever possible. To prevent more bugs.
