### ISSUE TITLE
Admin menu icon broken on WordPress.com

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#7785]
## Bug Description

When the plugin is installed on WordPress.com,  stories icon styling broken in sidebar.

## Screenshots

<img width="278" alt="Screenshot 2021-06-01 at 12 18 44" src="https://user-images.githubusercontent.com/237508/120314857-96462700-c2d3-11eb-8ad0-6359d7518cb1.png">
<img width="141" alt="Screenshot 2021-06-01 at 12 18 29" src="https://user-images.githubusercontent.com/237508/120314868-99d9ae00-c2d3-11eb-9ed9-f396fe6ff63a.png">

## Additional Context

- Plugin Version: 1.7
- WordPress Version: 5.7.2
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Interesting. Just checked this on our test site and it looks like any more icons are shifted upwards like this — but only when on the dashboard or in the editor. Works fine on "All Stories".

Looks like this CSS reset in the design system is causing this:

https://github.com/google/web-stories-wp/blob/7a178bc07b470b8b4ea0719cc473a0ce30580355/assets/src/design-system/theme/global/styles.js#L31-L35

Since it's global it also affects the WP admin menu.

We could work around it by adding `#adminmenu div.wp-menu-image:before { box-sizing: content-box; }`to `edit-story/style.css` and `dashboard/style.css`
