### ISSUE TITLE
Allow Story page image assets to be set as poster

### ISSUE THREAD

**Issue by shishirm** [GoogleForCreators/web-stories-wp#7908]
## Feature Description

Currently the only way to set a Story poster is to use one previously uploaded to the media library or alternatively upload one from the computer. It would make it much more convenient for users to be able to set a poster using one of the images that already exist in the Story.

A side effect of this change is that it will allow users to add stock images from the unsplash library into Stories and then subsequently allow them to be set as the poster.

## Alternatives Considered

The workaround now is that a user has to manually download the image from the Story and then upload it separately which a lot of creators are not very comfortable doing.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
@miina @swissspidy wondering if we could look into what we might need to make this happen - and whether we can implement this using existing patterns or would need new UX. 

I'm envisioning in the poster selection step we can include any assets used in the story in their own section, then the full wp media library separate. But not sure how feasible that'd be without building a brand new picker, etc.

**Comment by miina** [comment]
@BrittanyIRL Tagging you for Omar's question since this seems to be assigned to Pea pod.

**Comment by BrittanyIRL** [comment]
Thanks @miina  - I'm not super sure why Pascal assigned this to the pea pod, we haven't done anything within this realm. Has prometheus? Might make more sense for you to take it.

**Comment by miina** [comment]
> I'm not super sure why Pascal assigned this to the pea pod

Probably because it also has the quick action menu tag -- I assume the idea was to assign the poster from the quick action menu then :)

I'll reassign to Prometheus if you feel like that one is not for Pea pod (already finished for tonight, will take a closer look tomorrow).

**Comment by BrittanyIRL** [comment]
> > I'm not super sure why Pascal assigned this to the pea pod
> 
> Probably because it also has the quick action menu tag -- I assume the idea was to assign the poster from the quick action menu then :)
> 
> I'll reassign to Prometheus if you feel like that one is not for Pea pod (already finished for tonight, will take a closer look tomorrow).

Ah, the quick menu should be super easy to add to! I think it's a good thing to make sure more people understand how those work. Anyway, not trying to punt it to you - we just definitely don't have capacity for this right now 😅

**Comment by miina** [comment]
@o-fernandez The story poster image (`featured_image`) is stored by using the ID of the media in the WP media library, for being able to use images from the 3rd party media as posters we'd also need to upload the chosen image to the WP media library. (cc @spacedmonkey in case you have additional comments from the WP side since Pascal is on time off).

On how to implement this: could this perhaps be an option in the quick actions menu of the image element? Although the users would somehow need to know about this option while trying to set the poster from the panel.

If we'd have an option to directly in the panel to choose from the existing assets in the story then a separate picker would be necessary indeed. Or maybe the users could click "Choose an image from the page" from the panel, and then click on an image on the current page for selection?

**Comment by swissspidy** [comment]
@miina We could store that 3P poster URL separately somehow. Should avoid having to upload.

Using Quick Actions was also my first suggestion 👍

**Comment by o-fernandez** [comment]
Thanks for the input. I think that adding to the quick actions or right click menu could work. But, it also feels natural want to set from the document panel, so I think it's worth exploring options to improve that experience. 

That said, let's mock up the suggestion here, then! @tmagalhaes-huge @aaecheverria would be good to mock up quickly this suggestion to ensure it looks good. the overall flow is... 

- User can select an image already on the page (either bg or fg) on any page of the story
- User can easily set that image as their story poster image - either using the quick actions menu or the right-click menu. 

Also @BrittanyIRL for thoughts since Pea pod has been working on those features.

**Comment by BrittanyIRL** [comment]
I agree that this getting added to the document panel as well as in the quick action or right click menu is a good idea so that users can find it 2 ways. The quick action/right click menus aren't really doing much that the panels themselves aren't also capable of - just providing "faster" routes to likely actions to take.
