### ISSUE TITLE
Deep dive and improve editor performance

### ISSUE THREAD

**Issue by o-fernandez** [GoogleForCreators/web-stories-wp#8006]
## Bug Description

This should probably turn into an Epic with a breakdown, but filing as a bug for now: 

We have several credible reports of users experiencing significant editor sluggishness - this comes from users that have had great experiences with other online editors such as Canva. We should look at our editor resource utilization in various scenarios / setups and improve editor performance, particularly focused on mid-range set ups (not just high performance macbook pros)

## Expected Behaviour

The stories editor should be highly responsive/performant on mid-tier laptop/computer setups across the major browsers supported. 

## Steps to Reproduce

Test many scenarios including: 

1. long sessions with a ton of different actions over a 2-hour period
2. stories with lots of media, videos, gifts, text elements, etc. 
3. test multiple browsers (safari, chrome, edge, firefox)
4. wp instance with a ton of media files
5. lots more! 

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Related: #5328, #868

**Comment by dreamofabear** [comment]
Some common themes from our performance bug bash ([full notes](https://docs.google.com/document/d/1FafOqS5D_gsyp_0ZVfGDtx1abaJTbLoGjT9HYC8ic18/edit#)):
- Slow network
  - "New story" action takes a really long time (x2)
  - Text sets take a long time to load (x2)
  - Media or 3P media thumbnails take a long time to load (x2)
    - Large assets like GIFs and video are especially painful
  - Context-switching takes a long time, probably due to queued network requests
- Slow CPU
  - Input latency is long
  - Scrollers (page templates, text sets) are laggy/janky
- Safari
  - Input latency is long (select, drag+drop, resize, navigate between pages)
  - Scrollers (page templates, text sets) are laggy/janky
  - Memory usage is high (triggers Safari warning)
  - Bugs (canvas flashing/blinking, checklist has incorrect margin)

Some performance patterns/practices to consider:
- Before coding, always quantify expected impact/headroom with instrumentation first
  - Profile with Chrome DevTools and [React Profiler](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html)
- Use React DevTool's `Highlight updates when components render` to visually find unnecessary re-rendering
- For subtrees that are unavoidably slow, consider rasterizing to flat images (text sets, page templates, stories on dashboard, page thumbnails in editor)

**Comment by swissspidy** [comment]
> Input latency is long (select, drag+drop, resize, navigate between pages)

Just yesterday I opened the editor in Firefox and duplicated the pre-existing, empty page. Switching between those two empty pages was super slow as well.

> For subtrees that are unavoidably slow, consider rasterizing to flat images (text sets, page templates, stories on dashboard, page thumbnails in editor)

#7987, #8117, #5136 

> Some performance patterns/practices to consider:

There's much more to consider, and a lot of valuable information tailored to the story editor can be found here:

https://docs.google.com/document/d/18m9HamHkOvvTrv-mSOJawha0K4KTdn49HrnfXShULDI/edit
