### ISSUE TITLE
Animations: `prefers-reduced-motion` workaround breaks animations

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8046]
## Bug Description

In #7601 we added a workaround to honor the user's "Reduce motion" preference on the frontend.

If that setting is enabled, elements should still be visible; just not animated.

Now this fix appears to cause issues with animation effects like "Whoosh in", where the element is not animating as expected.

It's unclear whether #7601 broke this, or whether there was a recent change on the format side, since they are also looking into addressing this. See: https://github.com/ampproject/amphtml/pull/34466, https://github.com/ampproject/amphtml/pull/26286, https://github.com/ampproject/amphtml/pull/34442

Just reverting 4b896f60ebd427495ae55954f46dc409df5ec254 (#7601) does not solve the issue as this would break the "Reduce motion" honoring again.

## Expected Behaviour

Reduce motion? Yes -> no animation, but element visible on page
Reduce motion? No -> Element animated, visible after animation ends (e.g. fly in)

## Steps to Reproduce

1. Add new element to page
2. Add "Whoosh In" animation
3. Preview story
4. See that element is now not visible on the page anymore

## Additional Context

- Plugin Version: 1.8.0
- WordPress Version:
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @littlemilkstudio @choumx for any insights

**Comment by maxyinger** [comment]
Okay, I think it's a selector issue and we're only noticing it in whoosh in because it's the only animation that uses nested animations that also has opacity as one of the nested animations.

The rendered output ends up looking like this:
```
<div className="_c4f8efd">
  <div
    id="anim-720620da-3524-4c2c-b688-e80e9f633c54"
    className="_5c87fdf animation-wrapper"
  >
    <div
      id="anim-b998fb98-d203-4c5b-a89c-7747eaeb46f0"
      className="_731419b animation-wrapper"
    >
      <div
        id="anim-d6b18aa5-fc9c-4572-9ba2-ca057d4cc48b"
        className="_7826534 animation-wrapper"
      >
        <div
          className="_89d52dd mask"
          id="el-023bfc0c-56de-4a1f-8774-8a9d91e7a049"
        >
          <div className="_5184185 fill" />
        </div>
      </div>
    </div>
  </div>
</div>;
```

I think the issue is stemming from our selector which looks like this:
```
@media (prefers-reduced-motion: no-preference)
.animation-wrapper {
  /* some css var that equates to opacity: 0 */
}
```

Which causes all the `.animation-wrappers` to have an initial opacity of 0, while only one of them is animating to `opacity: 1`

**Comment by littlemilkstudio** [comment]
So I feel like a more proper (but tougher) solution would be to have wrapper specific selectors. Can't think of how to do this off the top of my head right now.

The other simpler solution would not actually fix the root problem, but avoid it, and just to just unify all the keyframes and use one animation wrapper here instead of nesting them. so the final rendered output would look something like this:
```
<el>
  <whooshInAnimWrapper>
    <mask>{/* rest of contents */}</mask>
  </whooshInAnimWrapper>
</el>
```
vs what we currently have below:
```
<el>
        <translateAnimWrapper>
          <opacityAnimWrapper>
            <scaleAnimWrapper}>
              <mask>{/* rest of contents */}</mask>
            </scaleAnimWrapper>
          </opacityAnimWrapper>
        </translateAnimWrapper>
</el>
```

The initial decision on one vs the other was pretty arbitrary tbh

**Comment by maxyinger** [comment]
sorry, it's early.

I think just switching the nesting to look like this could fix the issue:
```
<el>
  <translateAnimWrapper>
    <scaleAnimWrapper}>
      <opacityAnimWrapper>
        <mask>{/* rest of contents */}</mask>
      </opacityAnimWrapper>
    </scaleAnimWrapper>
  </translateAnimWrapper>
</el>
```

Or we could add `opacity: 1` keyframes to animations that don't actually touch opacity

**Comment by maxyinger** [comment]
alright, quick fix here:
https://github.com/google/web-stories-wp/pull/8065

**Comment by csossi** [comment]
Verified in QA
