### ISSUE TITLE
Performance Sprint: Pea

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#8133]
## Feature Description

Part of the performance epic (#8006), this is an umbrella issue for work in the upcoming performance sprint (7/5 - 7/16) for the Pea pod. 

Consider using this issue as a tracker and discussion forum for performance-related projects during the sprint. 

For reference and ideas, see the performance bug bash takeaways: https://github.com/google/web-stories-wp/issues/8006#issuecomment-871805740

## Additional Context

Helpful document from last round of perf: 

Editor: https://docs.google.com/document/d/18m9HamHkOvvTrv-mSOJawha0K4KTdn49HrnfXShULDI/edit#heading=h.5irk4csrpu0y 

Dashboard: https://docs.google.com/document/d/1ulDbJEWA9Q-5QyNsb2NpTACne8RMw8dpqfshkXlEgRI/edit

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Before more investigation, what we have to implement for perf in the dashboard is: 
- #5147 - for story previews 
- #4816 - publisher logos with srcset 

Editor: 
- #6309 excess renders of `updateCurrentUser`

**Comment by swissspidy** [comment]
Related: #8251

I think there's some potential to use `React.lazy`/`Suspense` and other dyanmic imports in the dashboard as well.

**Comment by BrittanyIRL** [comment]
So, doing a lighthouse audit of the dashboard our time to first contentful paint from the last time I did this last year went from 8.1s to 1.2s, so that's good to see that it's not as bad as it was. 

That said, everything that lighthouse is recommending is focused on the amount of stories we're loading. 

I think a great starting point for the dashboard perf is to swap the stories to use the story cover image, this is actually a more reliable thing to show the user since this is what their users would be seeing. 

To keep a "preview" sense we could either load the story on hover orrrrr we could load a story just like we do the template details, and have a 'story details' page that looks the same as the template details one so the user can explore their story that way. 

We'd lose the story hover on animation/focus but I think this will speed everything up and lighten the load drastically. 


@choumx are you ok with us running with this idea for like a day and seeing if it plays out how I think it will? 

From there it'll be easier to glean other areas that need assistance.

**Comment by dreamofabear** [comment]
Sounds good! 

Other thoughts on story posters: 
- What should a missing/placeholder poster look like?
- We can considering auto-generating posters e.g. removing text on the first page and running `html-to-image`
- Might make obsolete: #6430

**Comment by BrittanyIRL** [comment]
thinking a blank poster will look like a blank story currently: 
<img width="242" alt="Screen Shot 2021-07-08 at 3 12 37 PM" src="https://user-images.githubusercontent.com/10720454/124997102-f03aba80-dffe-11eb-94aa-2daec689c358.png">

Or we can mirror the blocks that Pascal and Jonny implemented a while back with the gradient
<img width="210" alt="Screen Shot 2021-07-08 at 3 20 38 PM" src="https://user-images.githubusercontent.com/10720454/124997759-0eed8100-e000-11eb-896b-2f7b039db3ad.png">

I like the idea of it being consistent with the blocks since those use the poster image as well.

**Comment by BrittanyIRL** [comment]
Closing, we're making progress on the dashboard. Anything further we find will have its own specific ticket.
