### ISSUE TITLE
Performance Sprint: Prometheus

### ISSUE THREAD

**Issue by dreamofabear** [GoogleForCreators/web-stories-wp#8134]
## Feature Description

Part of the performance epic (#8006), this is an umbrella issue for work in the upcoming performance sprint (7/5 - 7/16) for the Prometheus pod. 

Consider using this issue as a tracker and discussion forum for performance-related projects during the sprint. 

For reference and ideas, see the performance bug bash takeaways: https://github.com/google/web-stories-wp/issues/8006#issuecomment-871805740

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by miina** [comment]
These two issues would be good for the Performance week:
- Rendering Text Sets as images (#7985)
- Rendering thumbnails as images (#7987)

These can be worked on at the same time and #7985 was considered for the next sprint anyway. The next step to follow the Text Sets could be rendering Page Templates as images.

**Comment by miina** [comment]
Another potentially a good task for the performance week would be a performance analysis of the editor's first render that seems to take quite some time even on fast computers, it's not clear why but understanding and measuring the render time of different components might be useful for finding specific ways how to improve it.  E.g. page re-rendering seems to take quite some time, especially when there are multiple elements. Not sure if it's just because of the thumbnails or the page itself but would be good to look into this more thoroughly.

Maybe we could also consider some placeholders for the page / text sets / thumbnails etc. for when it's still loading -- to reduce the jumpiness.

@choumx Thoughts?

**Comment by dreamofabear** [comment]
A deep dive into initial render sounds like a good idea!

**Comment by miina** [comment]
Issue added: https://github.com/google/web-stories-wp/issues/8185
