### ISSUE TITLE
Smart text color: newly added background flashes when adding text

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8260]
## Bug Description
Reported in bug-bash.

After adding background media to a page, the first time when adding a text element, the background flashes. This happens just once after adding a background, seems to be related to the Smart Text Color feature.

## Steps to Reproduce
1. Enable the Smart text color experiment
2. Drag any media from the library and drop it as a background
3. Add a text preset
4. See the background flashing for a moment

Note: this happens only the first time after assigning the background, in my testing, it didn't happen every time.

## Screenshots
See the [bugbash findings ](https://docs.google.com/document/d/1hmQd46k1FzNjaNrrOEwymwnidT17imAhFt192IlF0IA/edit#heading=h.thawwo4c5khe)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by o-fernandez** [comment]
I also see instances in which when I add multiple pages, add background, then add the text preset the image doesn't flash and the text is just added as black (even if it has low contrast). Then I insert text again and the background flashes and the second text added has better contrast. 

I think we can still ship the feature, but should treat this as a P1 bug to fix, since it can get annoying. I think net net it still saves time for the user, but if the bg flash/reload is slow it can be more annoying than helpful.

**Comment by merapi** [comment]
I've tested many scenarios but have not yet come to a conclusion why that happens.

Tested:
- is there a difference between loading the image from memory cache or disk cache? doesn't seem so
- heuristics for cleaning the cache and loading it again are unclear (but even loading the image from cache can cause a flash)
- it can happen even in a very simple project/example
