### ISSUE TITLE
Editor: Add loading screen

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8279]
## Feature Description

When the editor is loading is a primitive loading screen is displayed, showing the words, "Please wait..." with a black background. 

![Screenshot 2021-07-07 at 15 26 25](https://user-images.githubusercontent.com/237508/125261170-ebc11b00-e2f8-11eb-9c7b-4e7d0dbfe1c2.png)

Styling on this loading page should improved, not only to make it look a little nicer, but also adds some sort of loading animation / progress bar ( that does not need to be actuate ), to give the user some feeling like that "something" is happening, to improve user's perception of speed of the application. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by maxyinger** [comment]
Should we just use the loading spinner that we have in the dashboard for switching between story tags? or are we waiting for new designs here?

**Comment by swissspidy** [comment]
Just adding a loading spinner doesn't seem like much of an improvement UX-wise.

I'd imagine we could perhaps display some skeleton UI or similar.

**Comment by spacedmonkey** [comment]
I think some kind of loading screen with a loading animation would be fine. It is what Google docs does. See this screen, there is a ball style animation to show it is loading. 

<img width="1780" alt="Screenshot 2021-07-14 at 09 57 14" src="https://user-images.githubusercontent.com/237508/125594315-23b00bb2-da27-467e-8d11-096d59d1a893.png">

**Comment by BrittanyIRL** [comment]
We can't do a skeleton really without it being a good amount of work because the app's not loaded yet so we don't have access to it. I was going to whip up just a more aesthetically pleasing loading screen with the same spinner (or mostly the same, i have to do it in pure css) in the design system that we use in various spots.

I know a loading spinner doesn't really _help_ alot but it should boost confidence that something is happening  - plus it won't take me very long.

**Comment by BrittanyIRL** [comment]
(tests with #8280 )

**Comment by csossi** [comment]
Not seeing the spinner:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/3f115cf7-45bc-4ba7-885a-46dc8b32296b)
