### ISSUE TITLE
Best practice for adding validation for meta-box

### ISSUE THREAD

**Issue by PatelUtkarsh** [GoogleForCreators/web-stories-wp#8284]
## Feature Description
We have added a custom WordPress meta box for taxonomy selection and we have a web story URL based on it - `/web-stories/{taxonomy-term-slug}/{post-name}`. 

We would like to set up validation to make taxonomy required before web stories can be published. 

What is the best practice to add custom validation for meta-box for web-story? 

## Alternatives Considered
Maybe we can provide a way of extending checklist for custom validation.

## Additional Context

Web-story plugin uses styled components which uses generated class name on build which makes selector unreliable for custom Javascript validations.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Great question! It actually touches on multiple areas.  

First and foremost, you might be pleased to hear that proper custom taxonomies support is on our to-do list (#489). I don't have a timeline for it yet, but it's definitely something we want to implement in a proper way. It would be very similar to how taxonomy support in Gutenberg works (i.e. register public taxonomy -> it will automatically show up in the editor).

Using the legacy custom meta boxes feature to display custom taxonomies selection already today is an interesting workaround and I am glad to hear that it seems to work as intended so far.

Next, there is currently no public API for developers to touch into any parts of the editor state or interactions, such as into hooking into the saving process to perform any additional validation. We simply don't have this yet.

Related to that, we don't currently have any ways of extending the checklist within the editor either.

So to answer your question:

> What is the best practice to add custom validation for meta-box for web-story?

Since there is currently no public API there is also not really a best practice here that we could share or advocate for.

-----

> Web-story plugin uses styled components which uses generated class name on build which makes selector unreliable for custom Javascript validations.

What component are you trying to target? The publish button? `header button[type=primary]` would work I think.

-----

cc @choumx as FYI

**Comment by dreamofabear** [comment]
Thanks for creating this issue. 

> We have added a custom WordPress meta box for taxonomy selection and we have a web story URL based on it - `/web-stories/{taxonomy-term-slug}/{post-name}`.

Adding a taxonomy to the permalink structure for web stories should be doable in the WordPress "Permalinks" page, right? 

> We would like to set up validation to make taxonomy required before web stories can be published.

This is the first time I've heard of this requirement -- seems like we'd have to integrate this into the checklist and have a setting that toggles registered taxonomies as "required". 

@PatelUtkarsh Are there any other product requirements that you can share here? E.g. a detailed, step-by-step user journey would help us understand the complete scope of this FR.

**Comment by swissspidy** [comment]
> Adding a taxonomy to the permalink structure for web stories should be doable in the WordPress "Permalinks" page, right?

No, something like this is not usually user-facing in WordPress and is instead customized by plugins with some PHP code.

Some plugins like WooCommerce provide an option to change the permalink base from something like `/products/<slug>` to `/whatever/<slug>` in the UI, but that's it.

We have a ticket for supporting that as well, see #4459

**Comment by PatelUtkarsh** [comment]
Thank you for your comments @swissspidy and @choumx. 

> What component are you trying to target? The publish button? header button[type=primary] would work I think.

Yes, but we would like a parent component as the primary button itself changes to various states like schedule and update.

Safe option is to have a default fallback term for taxonomy just like uncategorised.

> @PatelUtkarsh Are there any other product requirements that you can share here? E.g. a detailed, step-by-step user journey would help us understand the complete scope of this FR.

This is a really unique scenario where curation happens on a single WordPress instance and is copied to different sub-sites in read-only mode. (1-1 mapping).

The required taxonomy is to select subsites and in addition to that, we also have paid vs free content taxonomy which defaults to free.

Structure - `/web-stories/free/sub-site/story-name`.

An editor will curate a story in this WordPress instance, Selects which sub-site it should go to, Selects free/premium, Publish. 

On publish we will queue it up and push it to the sub-site.
