### ISSUE TITLE
Convert HEIC image files to a web safe image format

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8292]
## Feature Description

As of [iOS 11 and macOS High Sierra](https://support.apple.com/en-gb/HT207022) , Apple start using the HEIF format to save images. Sadly HEIF files can not be viewed in web browsers. For those taking images on their iPhone, this would mean to embed a raw iPhone photo, would require them to use a third party tool to convert that image into a web safe format like jpeg.
WordPress core should convert this image to a web safe format while keeping the original for reference.

As the [iPhone is one of the world's most popular cameras](https://www.cnet.com/tech/mobile/iphone-top-camera-flickr-2017-report/), it is reasonable to guess that content creators will take photos on their phone to upload to the editor. It would save the users a step of having to convert the image. 

WordPress core ticket [#53645](https://core.trac.wordpress.org/ticket/53645)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
To be able to use this library. https://github.com/alexcorvi/heic2any

**Comment by swissspidy** [comment]
We'd probably want to use [squoosh](https://github.com/GoogleChromeLabs/squoosh) here, though it's not ready yet for easy use on the web, see https://github.com/GoogleChromeLabs/squoosh/issues/1084.

An alternative in the meantime might be https://github.com/kleisauke/wasm-vips, though it's also not stable yet, see https://github.com/kleisauke/wasm-vips/projects/1

I think both might support HEIC files though.

Bumping priority here due to user feedback, but this is not actionable yet.

**Comment by kleisauke** [comment]
FWIW, wasm-vips does not support the patent-encumbered HEIC format. See: https://github.com/kleisauke/wasm-vips/issues/3#issuecomment-838422064.
