### ISSUE TITLE
Pre-Publish Checklist: Add check for missing publisher name

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8357]
## Feature Description

The publisher name is displayed on a story when it surfaces in Discover or in Search, so it's quite important to set. If it's not provided, it is inferred from the domain.

The publisher name can be missing if a site has an empty Site Title under Settings -> General in WordPress.

We should add a check to the PPC to look for an empty publisher name. If it's empty, tell users to set the Site Title in the Settings or, if that doesn't help, go to the support forums.

The publisher name can be checked via `const { metadata: { publisher: { name } } = useConfig();`

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@o-fernandez for consideration.

cc @shishirm

**Comment by o-fernandez** [comment]
Let's add this. It can be added to the priority list in the checklist and have help text: 

- Add Site Title
- Go to Settings -> General in WordPress to add a Site Title.

I think that just aligning it to the WordPress wording here, Site Title, instead of publisher name may be easiest. But LMK if you think we need to clarify that WP Site Title = STAMP Publisher Name?

Also, @swissspidy, is it safe to assume that the Settings -> General is always going to be in wp-admin/options-general.php? Maybe we can make that a hyperlink that opens in a new tab so people can easily navigate there, instead of figuing out what "Settings -> General in WordPress" means.

**Comment by swissspidy** [comment]
Yes that is always there. A link makes sense.

**Comment by BrittanyIRL** [comment]
Tried to take the comments above and write copy, thoughts @o-fernandez ?

<img width="270" alt="Screen Shot 2021-07-28 at 4 57 46 PM" src="https://user-images.githubusercontent.com/10720454/127411110-bf76d79c-0d86-4296-828d-1d53bd71f81c.png">

**Comment by swissspidy** [comment]
I'd remove "in your WordPress Dashboard".

a) Users are already in WordPress admin
b) Avoids users going to the actual dashboard in WordPress, which is a different page :-)

**Comment by o-fernandez** [comment]
Thanks @BrittanyIRL - looks great! Let's remove "in your WordPress Dashboard" per @swissspidy's suggestion!

**Comment by BrittanyIRL** [comment]
Great, thank you both for your copy help!

**Comment by csossi** [comment]
Verified in QA
