### ISSUE TITLE
Disable PiP button on video elements

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8372]
## Bug Description

When inserting, then playing the video, a picture in picture will appear. 

## Expected Behaviour

PIP button should not appear. 

## Screenshots

<img width="1792" alt="Screenshot 2021-07-19 at 15 52 30" src="https://user-images.githubusercontent.com/237508/126180599-f629b7fa-d3bf-4027-9200-f289fc88eca3.png">## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Is that a Firefox specific feature? Looks like there's currently no option to disable that there: https://bugzilla.mozilla.org/show_bug.cgi?id=1610522

**Comment by spacedmonkey** [comment]
I feel like there was a way to fix this, youtube would have fixed it. Okay, maybe we can mark this as cantfix.

**Comment by swissspidy** [comment]
In the draft spec there is a proposed [`disablePictureInPicture`](https://w3c.github.io/picture-in-picture/#disable-pip) attribute, but since Firefox is not following the spec, [they won't support this](https://bugzilla.mozilla.org/show_bug.cgi?id=1611831#c5).

If there is another way to address this, I am all for it. But doesn't seem like a pressing issue to invest time for investigating it.

So I'd say _maybelater_

**Comment by spacedmonkey** [comment]
is there any problem with adding `disablePictureInPicture` attribute? What would it hurt?

**Comment by swissspidy** [comment]
Well, does it actually do anything in other browsers?
