### ISSUE TITLE
Broken gradients in SVG icons due to duplicate IDs

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#8401]
## Bug Description

Original report. https://github.com/google/web-stories-wp/pull/8339#issuecomment-881460560

The icon for the web stories block is looks off in customizer widget screen in WordPress 5.8. See screenshot. 

## Steps to Reproduce

1. Open customizer.
2. Click on widgets.
3. Click on plus icon. 
4. Search web stories. 

## Screenshots

<img alt="Screenshot 2021-07-16 at 14 42 28" width="572" src="https://user-images.githubusercontent.com/237508/125957423-5e345c2c-ceec-4278-9f11-8eb2ddbd330d.png">

## Additional Context

- Plugin Version: 1.9.0
- WordPress Version: 5.8
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Coping my reply from https://github.com/google/web-stories-wp/pull/8339#issuecomment-882720523:

This is not an issue introduced by this PR. Unfortunately this bug also exists in `main` and probably every plugin release before that.

It's caused by duplicate IDs in the SVG and the SVG being used multiple times in the document, causing collisions.

Related tickets:

https://github.com/svg/svgo/issues/674
https://github.com/gregberge/svgr/issues/150

This needs some further investigation and probably requires some changes to the webpack config. We should definitely do this in a dedicated ticket.

**Comment by spacedmonkey** [comment]
Found a very simple workaround [here](https://github.com/google/web-stories-wp/tree/fix/icon-id). 

That fixed the original issue.
<img width="349" alt="Screenshot 2021-07-23 at 12 01 17" src="https://user-images.githubusercontent.com/237508/126773224-5c44712d-ceea-4499-935e-c2e1e3e98a46.png">

**Comment by swissspidy** [comment]
That's the one from https://github.com/svg/svgo/issues/674#issuecomment-328774019?

Hmm that does not seem to do anything in my testing at all, the final SVG in the DOM remains unchanged and there's no prefix there. Not even using `cleanupIDs: { prefix: 'foo-', }` works 🤷 

The gradient is still broken when selecting the block and seeing its toolbar:

![Screenshot 2021-07-23 at 13 13 07](https://user-images.githubusercontent.com/841956/126774493-3eebeac5-aef0-4f72-8132-6f0718a1ff3a.png)

My understanding is that, when the SVG is used multiple times on a page, every instance must have a unique ID. But with a SVGO config the SVG would only be transformed once during bundling, not many times. So we need to do something in React (so with SVGR rather than SVGO).

**Comment by swissspidy** [comment]
I suppose an easy workaround would be to define the SVG in React instead of importing from `icon.svg` and then just use `useInstanceId()` there to increment the ID.

That would be quite trivial and saves hassle with dealing with those configs.

**Comment by csossi** [comment]
Verified in QA
