### ISSUE TITLE
Not saving correctly

### ISSUE THREAD

**Issue by DanielCryptoK** [GoogleForCreators/web-stories-wp#8444]
See attached video

https://user-images.githubusercontent.com/45933242/126736823-b9473d0e-ed0b-4bb5-86cc-a8e5ec93a2d7.mp4

**Comment by swissspidy** [comment]
Heya, interesting issue you're running into here! THanks for the detailed explanation in the video.

Please note that we concentrate our support efforts on the [WordPress.org support forums](https://wordpress.org/support/plugin/web-stories/). Whenever you're facing some roadblocks or have some questions, our support representatives can help you there. We only move over to GitHub for confirmed & reproducible bugs.

That said, since you are already here, please try a few things:

1. Temporarily deactivate all other plugins and see whether this still happens.  
  You can use the [Health Check & Troubleshooting](https://make.wordpress.org/support/handbook/appendix/troubleshooting-using-the-health-check/) plugin to enter troubleshooting mode where other plugins are only deactivated for your own user account, but not anyone else. This is a super easy & safe way for debugging.
2. If it works in troubleshooting mode, that means there's a conflict with one of your plugins. You can activate plugins one by one to find the culprit.
3. Send us your Site Health information [via this form](https://docs.google.com/forms/d/e/1FAIpQLSd-AeFLOIJd4NLYz7EDUa9vMfzZIoT5Bn1leV3dL2CM_B1C6Q/viewform).  
  This way we can check for any potential plugin conflicts as well.
4. Analyze the REST API network requests in the browser's dev tools to find anomalies.  
    1. Open the dev tools (press F12)
    2. Clear any items in the list
    2. Filter by `web-stories` 
    3. Save the story
    4. For the entry saying `/wp-json/web-stories`..`, analyze the response status, headers and the response body.
    5. Share a video or screenshots here.

For (4), here's a quick demo of what I mean:

https://user-images.githubusercontent.com/841956/126783582-b9baf2c5-7ce3-4c30-af48-91ccd0bcf54f.mov

**Comment by mxbclang** [comment]
@DanielCryptoK Hi there! Checking in here – are you still having trouble?
