### ISSUE TITLE
Performance: Optimize checklist rendering

### ISSUE THREAD

**Issue by merapi** [GoogleForCreators/web-stories-wp#8446]
## Feature Description

Checklist currently renders the list even if it's closed.
For example page preview/thumbnail is rendered for "text too little" warning as soon as you add something to the page (and on many pages in real-world stories).
Then the list is re-rendered with some basic actions like DND (affects #8259).
Thumbnail rendering will be improved with #7987 but I think it still shouldn't render checklist contents if they are not visible.

![image](https://user-images.githubusercontent.com/21036224/126774496-3db41ca0-2bde-46c6-b41a-19d2954bdb43.png)

![image](https://user-images.githubusercontent.com/21036224/126774007-32d903fc-1f31-4b0d-a187-945977f3e554.png)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by BrittanyIRL** [comment]
Appreciate the eyes here and agree we can cut back on the updates, but it's actually quite important that this renders when the checklist is closed because we have to show a little tally of priority issues on the toggle button once specific "checkpoints" of a story are hit. Ie) you try to publish a 2 page story - you need to get a dialog asking you if you're sure and to review the checklist or if you have a story and it looks great but you didn't name it - you should also be told to review the checklist, etc. 

So that data's all based on what checks are coming back as needing updates. 

I think here we can work on making sure that those checks only update when their potential value has changed is a good next step. We do have to keep checking based on a lot of story changes.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio tagging you for your thoughts since I know looking at checklist perf after the lift of getting it updated to the new structure was something you'd already been thinking on.

**Comment by maxyinger** [comment]
Yea we set it up so these checks only run when the relevant part of the story they're testing against update. That being said, a lot run whenever the elements or page update because they need to test every element on the page. I'm guessing this would get triggered by DND.

We definitely need to run certain checks every time elements/pages update, but we could hold off on the rendering of the presentational thumbnails/cards for those checks.

something like:
```
  const isRendered = failingElements.length > 0;
  useRegisterCheck('ImageElementResolution', isRendered);

  return (
    isRendered && isChecklistCompanionOpen && (
      <ChecklistCard
```

**Comment by BrittanyIRL** [comment]
> We definitely need to run certain checks every time elements/pages update, but we could hold off on the rendering of the presentational thumbnails/cards for those checks. 

💯  - let's try that and see what wins we gain. I'll throw this in the sprint backlog for next time our runway is low. We might have room next week.

**Comment by maxyinger** [comment]
we can add individual performance improvements to checks as well. i.e. any checks that run against every element or page, we could use like a requestIdleCallback or some other amortization approach to do deprioritize that work when there's other expensive tasks like DND.

Might cause some minor delays in updating the count/rendering of cards, but could be worth looking into to trim as much fat as possible perf wise.

Might be worth taking like an idle until active approach, but active could be considered when the checklist companion is open, so you only notice sluggishness in the checklist count update when it's closed.

I'm open to any and all suggestions tho and also happy to further discuss the rationale behind the choices we made for the existing architecture if you're curious.

**Comment by BrittanyIRL** [comment]
(bumped to a 5 for more exploration, pointed hastily)

**Comment by maxyinger** [comment]
I guess to summarize, the approaches I mentioned (we can do both, or one or the other):
- Remove diffing of presentational components when checklist closed (~ 2pts)
- Add an amortization strategy for performing logical checks against all elements/pages (~3pts)

We can group these together in that same ticket and leave it as a 5, or spit them up. I'm fine with whatever. Also open to other approaches/suggestions

**Comment by merapi** [comment]
> Appreciate the eyes here and agree we can cut back on the updates, but it's actually quite important that this renders when the checklist is closed because we have to show a little tally of priority issues on the toggle button once specific "checkpoints" of a story are hit.

I'm fine with the little tally, my concern was about rendering the contents of the list when it's not expanded.
(simplified solution):
```jsx
{isExpanded && children}
```

Anything beyond that is nice to have, because I think we don't need that counter to update instantly, it can be updated in the next JS loop (maybe idle callback can be used here?), but the initial improvement should be a low hanging fruit?
