### ISSUE TITLE
Dashboard: Loading spinner not disappearing for contributor user

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8532]
## Bug Description

Originally reported by Claudio, I just verified it:

When logging in as a contributor user, it can happen that the infinite scroller's loading spinner never disappears, even though the HTTP requests finished properly.

Happens constantly on the dev site, but can also be reproduced locally.

On the dev site, the interesting bit is that the returned `body` is an empty array for some unknown reason.

And if you scroll up and down, it tries to load page 3, 4, 5, etc. and gets an empty array back every time.

## Steps to Reproduce

1. Ensure you have plenty of stories with various statuses, including `private`
2. Log in as a contributor user
3. Go to "My Stories"
4. Scroll to bottom
5. See loading spinner for ever

## Screenshots

![Screenshot 2021-08-02 at 16 02 52](https://user-images.githubusercontent.com/841956/127875199-de00e5da-077c-46b2-95e9-e19e687ffeef.png)

## Additional Context

- Plugin Version: 1.10
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @spacedmonkey as perhaps this is related to the WP REST API improvements we've made recently.

**Comment by BrittanyIRL** [comment]
pretty sure i figured this out. So the loading state is accurate when digging into the React Dev Tools. It's tied to the issue we were talking about a while ago where the dashboard story count is telling us all the stories regardless of if the user has access to those stories. 

For instance, on our staging site I've made myself a contributor account and I can see 1 story but there are 710 stories total. 

![Screen Shot 2021-08-02 at 4 05 15 PM](https://user-images.githubusercontent.com/10720454/127934303-9cf174cd-6b23-4f52-aaec-83b2c27124d6.png)

See #6613 

It comes down to this in the dashboard: `action.payload.page >= action.payload.totalPages` where totalPages is set from the header response when retrieving stories: `parseInt(response.headers['X-WP-TotalPages']);`

**Comment by maxyinger** [comment]
@swissspidy So I think this is two separate issues:

1) I think the backend does user story filtering after pagination. 

So querying pages from an admin might look like this:
[
  [a, b, c],
  [d, e, f],
  [g, h, i]
]

Where the same paginated data for a contributor might look like this:
[
  [a, c],
  [],
  [i]
]

This accounts for the empty arrays you were seeing getting returned when you were logged in as a user.

2) The frontend just works by incrementing the pagination index every time the infinite scroller intersects into the viewport. This becomes an issue when the paginated data only returns < 1 row of stories and never puts the infinite scroller outside of the viewport to be able trigger again.

So I'm open to whatever solutions come to mind. First ideas I've had:

- Fix issue 1 on the backend, and filter out permission stories before paginating the stories on the backend. I don't think we would run into issue 2 any more if we did this.
- We could give the infinite scroller loading wheel a unique key based on the current page index so that it keeps triggering the incrementing of pages until it loads enough stories to push it out of the viewport.

I think the second approach here might not be as clean of a user experience (especially if there's a bunch of empty pages that have to load before you get to anything the user has access to), but it wouldn't be that bad to implement. 

I'm not sure how complex doing the first solution here would be. Very dependent on the setup of the backend. Would definitely be a better user experience tho.

**Comment by swissspidy** [comment]
I completely forgot about this one, so thanks for the ping & taking a look to find the root cause!

Agree that this ideally should be fixed on the backend in that case. Bit fuzzy on the details of #6613, but wondering if a solution like https://github.com/google/web-stories-wp/issues/6613#issuecomment-797496290 would help there.

Let's wait until Jonny's back from PTO so he can take a look.

Assigning to WP & Infra pod accordingly.

**Comment by maxyinger** [comment]
Awesome. Sounds good!

**Comment by spacedmonkey** [comment]
Are we sure this still valid? I can't seem to validate this locally. I think that https://github.com/google/web-stories-wp/pull/8598 may have fixed this issue. I also think that https://github.com/google/web-stories-wp/pull/8976 is fixed, this will also help.

**Comment by BrittanyIRL** [comment]
> Are we sure this still valid? I can't seem to validate this locally. I think that #8598 may have fixed this issue. I also think that #8976 is fixed, this will also help.

Your PR for #8976 fixes this

**Comment by swissspidy** [comment]
Closing this then as a duplicate of #6613 / #8976
