### ISSUE TITLE
Remove duplicate button styles

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8557]
## Feature Description

This spring we implemented a new design system that has some `Button` styles that are reusable. Mostly these have replaced the former buttons but there are 2 left that could use the new design system version instead. They are the icon buttons:   `ArrowDown` and `More`.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Remove the duplicate Button style, use design system for these two icon buttons (`buttonType="icon"`)

**Comment by g-sqiao** [comment]
Since these two issues (#8557 and #8555) are basically changing the same thing, I feel it's very confusing and hard to manage these two threads at the same time. I'll combine all changes into PR #8651 and closing current issue so everything will be tracked by using one issue (#8555) and one PR (#8651)
@BrittanyIRL @choumx
