### ISSUE TITLE
Carousel Secondary Navigation Buttons Have Inconsistent Padding

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8612]
Our new design teammember noted that the buttons on the secondary navigation of the carousel in the editor don't have consistent padding. This ticket is to give those button icons all consistent spacing so that they are always the same amount of space. 

![image.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/7e367bb8-303d-4f37-9e7b-9a88d3e846eb)

**Comment by maxyinger** [comment]
ah I think this is because all the svgs have varying amount of negative space embedded in the icon itself. will have to make all the paddings different to make them visually the same.

Also, my latest main for the keyboard shortcuts button doesn't have an outline like in the screenshot above. Is that update still in the pipeline?

**Comment by maxyinger** [comment]
oh you already have it linked as being blocked by the in flight a11y pr. just now seeing that, makes sense.

**Comment by BrittanyIRL** [comment]
@littlemilkstudio this is unblocked now :)

**Comment by csossi** [comment]
Verified in QA
