### ISSUE TITLE
Handle saved color overflow in basic color picker

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8656]
## Feature Description

Display scrollbar (correctly scrolling all but the header and the close-icon) in basic color picker if contents overflow due to too many saved colors.

| Normal | Overflow |
|-|-|
| <img width="1896" alt="new heading" src="https://user-images.githubusercontent.com/4030811/131366126-55af687e-75e8-4671-90e3-82594c06d288.png"> | <img width="1896" alt="with scroll" src="https://user-images.githubusercontent.com/4030811/131366121-f151608e-dd3f-4884-98c9-333028ecf760.png"> |

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by aaskedall** [comment]
Updated files
<img width="1896" alt="with scroll" src="https://user-images.githubusercontent.com/4030811/131366121-f151608e-dd3f-4884-98c9-333028ecf760.png">
<img width="1896" alt="new heading" src="https://user-images.githubusercontent.com/4030811/131366126-55af687e-75e8-4671-90e3-82594c06d288.png">

**Comment by miina** [comment]
It looks like the behaviour is almost as expected already now. The improvements could be the following:
- Consider admin bar -- currently the header part of the color picker can get hidden behind it
- Ensure only unique custom colors can be added, currently allows duplicates (might deserve its own issue but I'm planning to fix this since I'm already working on the color picker anyway)

**Comment by csossi** [comment]
Verified in QA
