### ISSUE TITLE
Align Left/Right vs. Top/Bottom - Safe Area

### ISSUE THREAD

**Issue by csossi** [GoogleForCreators/web-stories-wp#8695]
## Bug Description

When I opt to Align Top or Align Bottom, the element selected stays within the safe area. However, if I choose to Align Left or Align Right, the element moves and disregards the safe area

## Expected Behaviour

Would have expected consistent behaviour here

## Steps to Reproduce

- position element on page
- select Align Top icon
- Note that element stays within safe area
- Now select Align Left
- Note that image now goes past the safe area

## Screenshots

Selected Align Top icon:
![image](https://user-images.githubusercontent.com/16945664/129491481-72b71fdf-3773-4318-b1e6-63a43c0d3caf.png)

Selected Align Left icon:
![image](https://user-images.githubusercontent.com/16945664/129491541-71cc1b32-2086-4a0e-9505-c6ed012d5d30.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
cc @barklund @o-fernandez

**Comment by o-fernandez** [comment]
I think this needs UX input as it may be working as intended. 
* Depending on the aspect ratio of the device where the story is being viewed, the area above/below the safe zone may get cropped. 
* The area to the left and right of the safe zone does not get cropped, but you are advised not to put any cta/clickable/tappable elements in there since the system navigation would overlap and not allow the user to tap into the CTA. 
* Given that, I can see why there's a difference in the way the alignment works, but this is unclear to the user since the safezone design doesn't communicate any of this. 
@aaskedall thoughts?
