### ISSUE TITLE
Taxonomy Support: API support

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#8830]
(@swissspidy bit of a placeholder to make sure that our pods are on the same page for adding taxonomy support for 1.12, please edit as you set fit.)

- [ ] Communicate with Infra to get proper structure for saving tags and categories. 
- [ ] Make sure nothing new needs to get added on the infra side of things for tags and categories to be created/edited/deleted from a story in the editor.

**Comment by swissspidy** [comment]
Taxonomy handling in the REST API already exists in WordPress core to its full extent. I doubt we'll have to do any custom work on this end. Perhaps some slight modification to make usage a bit easier.

REST API reference for tags and categories:

https://developer.wordpress.org/rest-api/reference/tags/
https://developer.wordpress.org/rest-api/reference/categories/

And for posts:

https://developer.wordpress.org/rest-api/reference/posts/

What's important to understand is that a story can potentially have **X taxonomies associated with it**. Not just categories or tags.

All supported taxonomies are exposed via `_links` in the REST API response, where there is a dedicated `wp:term` entry. Example of a post that has 2 taxonomies:

![Screenshot 2021-08-30 at 11 13 50](https://user-images.githubusercontent.com/841956/131316335-7ac5b6ea-2287-42af-80e7-a72810f87f11.png)

And because these resources can be **embedded** using `?_embed`, it's easy to get a list of all associated **terms** in those taxonomies. Example of a post that has 1 term in the "category" taxonomy.

![Screenshot 2021-08-30 at 11 15 12](https://user-images.githubusercontent.com/841956/131316486-7f291d5c-e8b0-421d-aad2-f2dc5fd2d2b6.png)

I defer to the REST API reference for documentation, but basically to **create a new term** you'd `POST` to `wp/v2/<taxonomyslug>`, to **update an existing term** you'd `POST` to `wp/v2/<taxonomyslug>/<id>`

There's no UI in the editor to _delete_ terms themselves, so we don't need to worry about that.

To **associate a term with a post/story**, just provide the list of terms in a `POST` request to `/web-stories/v1/web-story/<id>` as per the reference.

Example for posts:

```curl
curl -X POST https://example.com/wp-json/wp/v2/posts/<id> -d '{"categories":<array of terms in the category taxonomy>}'
```

**Comment by swissspidy** [comment]
To get you started testing taxonomy support in stories, drop this file in `wp-content/plugins` or upload it as a plugin through WordPress admin:

https://gist.github.com/swissspidy/62d54f3f48a81b88a0f2b07fd32f844e

This will set up 4 new taxonomies for testing. You will see them all in the admin menu after activating the plugin.

**Comment by swissspidy** [comment]
@littlemilkstudio To get a list of all taxonomies available for stories: `GET wp/v2/taxonomies?type=web-story`. Or in `packages/story-editor/src/app/api/apiProvider.js`:

```js
const getTaxonomies = useCallback(() => {
    return apiFetch({
      path: addQueryArgs('/wp/v2/taxonomies/', { type: 'web-story' }),
    });
  }, []);
```

Can use the `hierarchical` field to determine whether to show the freeform component or not.
Can use `name` for the actual panel/label name in the editor UI (so it will be translated automatically)
