### ISSUE TITLE
Page Templates: Confusing play button when image not set

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#8942]
## Bug Description

Originally reported by @bmattb 
The template titled One Day City Cover has an animation play button that seemingly does nothing

![image12](https://user-images.githubusercontent.com/58738530/131916654-9f558b48-aeed-4154-a89a-65406d577a26.png)

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

**Comment by swissspidy** [comment]
The background image on that page has a Pan animation.

The issue is that the image itself is removed for page elements, so you see that gray area with a grid which obviously doesn't really animate.

You'll properly see the animation once you add an actual image:

https://user-images.githubusercontent.com/841956/131924956-56989067-1a6d-44cd-aeac-2ce277c99d53.mov

So what you're describing here is not an image with a specific template but just general current behavior in the editor for page templates.

And I don't think we can really detect that, so perhaps it's simply a wontfix.

Pinging @littlemilkstudio and @choumx to chime in.

**Comment by dreamofabear** [comment]
Agree this is technically WAI. We could consider replacing the default grid placeholder image with something that animates well e.g. checkerboard pattern.

/cc @aaskedall

**Comment by BrittanyIRL** [comment]
We're removing the grid placeholder image as of this: https://github.com/google/web-stories-wp/issues/9093#issuecomment-926197776 which will go out in 1.14 release so i'm going to close this as it is not applicable and the grid is going away.
