### ISSUE TITLE
Decoupling: Force `isSaving`/`isEnabled` state when saving meta boxes

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8952]
## Background

The WordPress story editor supports a WordPress-specific feature called "custom meta boxes" that allows other WordPress plugins to integrate with the editor by showing their custom UI for customizing some story settings. This is particularly useful for SEO plugins like All in One SEO or Yoast SEO, as users can configure some SEO metadata from within the editor this way.
See #5048 for a demo.

Due to the way custom meta boxes work in WordPress, we need hook into the saving process of the editor and save any custom meta boxes in a separate HTTP request.

So basically, whenever the story has just been saved (but it wasn't an autosave), we save the meta boxes as well.

The interesting part:

Whether we are saving the story itself _or_ the meta boxes, we show a loading spinner next to the publish buttons. This happens here:

https://github.com/google/web-stories-wp/blob/9ab1bd62ab46ed47362ffe4db30a2b78beb8c416/packages/story-editor/src/app/story/storyProvider.js#L167

Similarly, we always allow updating the story when there are any custom meta boxes, even if the story itself hasn't changed:

https://github.com/google/web-stories-wp/blob/9ab1bd62ab46ed47362ffe4db30a2b78beb8c416/packages/story-editor/src/components/header/buttons/update.js#L70-L74

## Proof-of-concept

Recently, @sayedtaqui has been working on extracting all custom meta boxes logic from `packages/story-editor` into `packages/wp-story-editor`.

See https://github.com/rtCamp/web-stories-wp/pull/763 for a POC.

Now, solving the `isSaving` and `isEnabled` parts is really the last remaining piece for finalizing this.

With all custom meta boxes functionality moved to `wp-story-editor`, how can we force the `isSaving` state while meta boxes are saving, without having any meta boxes logic within `story-editor` itself? And how can we enforce `isEnabled` if there are any meta boxes present?

## Context

Gutenberg has faced the same question and has basically solved this by moving the whole header area with the publish/update button to the `edit-post` package (which is basically `wp-story-editor`), but keep the individual components to assemble the header in the `editor` package (aka `story-editor`), with `forceIsSaving` props to override the state.

Source:

https://github.com/WordPress/gutenberg/blob/408170a9b4007857166b41041aceedb1cef012c8/packages/edit-post/src/components/header/index.js#L66-L82

https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/editor/src/components/post-saved-state/index.js#L72-L76

https://github.com/WordPress/gutenberg/blob/9580b45e6e18dd06076af9f7e1ea66babee22bf5/packages/editor/src/components/post-publish-button/label.js#L51-L65

## Implementation Brief

In theory, we could do the same thing as Gutenberg, which would make implementations a bit easier on other platforms.

For example, a standalone playground doesn't need a "Publish" button anyway, just "Preview", so the playground would simply not render that component.

But perhaps there are alternatives.

**Comment by swissspidy** [comment]
@choumx @barklund Would love to hear your thoughts on this

**Comment by swissspidy** [comment]
@sayedtaqui Curious about your thoughts as well of course. Perhaps a proof-of-concept for the above idea would help

**Comment by mohdsayed** [comment]
I think the Gutenberg approach makes a lot of sense, let me try a POC.

**Comment by mohdsayed** [comment]
@swissspidy 
Updated the existing [proof-of-concept ](https://github.com/rtCamp/web-stories-wp/pull/763/files)

I think we need more granular control over the components and therefore the core editor would need to export all the pieces of header so that they can be assembled in the `wp-story-editor` package.

https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/story-editor/src/components/header/index.js#L17-L22

https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/wp-story-editor/src/components/header/index.js#L48-L59

The first step would be to export `Layout` from the `story-editor` so that we can pass the header as one of its props and we can use its `children` to add extra content ( For example to pass `MetaBoxes` component, instead of sending it via `StoryEditor` configuration )
https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/story-editor/src/index.js#L24

https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/story-editor/src/components/layout/index.js#L92-L95

Then use it in the `wp-story-editor`
https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/wp-story-editor/src/components/layout/index.js#L19-L55

And now, since we are assembling the header pieces in `wp-story-editor`, we can grab the loader from its neck and update `isSaving` as we need.

https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/wp-story-editor/src/components/header/buttons/index.js#L61-L68

And pass an extra prop to handle `isEnabled` 
https://github.com/google/web-stories-wp/blob/e3c00112889d4527129b082bf77a637bfa1a46ba/packages/wp-story-editor/src/components/header/buttons/index.js#L113

**Comment by mohdsayed** [comment]
This will also open the door for giving more control of the configuration like [changing some labels](https://github.com/WordPress/gutenberg/blob/a7e2895829c16ecd77a5ba22d84f1dee1cfb0977/packages/edit-post/src/components/layout/index.js#L51-L63) which may not be relevant for non-WordPress environments or allowing more `InterfaceSkeleton` props ( like `library`, `inspector` ) if required, instead of passing all the configuration via `StoryEditor` component.

**Comment by swissspidy** [comment]
That POC looks really promising 👍  As you said, this will unlock a bunch of other things as well, which is great!
