### ISSUE TITLE
Disable video transcoding for non-WP media

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#8982]
## Feature Description

Video trimming and muting should only be allowed for videos that reside on the WP installation itself, and not for Coverr videos nor hotlinked videos.

Muting is currently not an option for Coverr videos, as they're always without sound by default, but hotlinked media could have audio and should not be mutable.

Video trimming should always be disabled for any non-WP videos similarly.

### Implementation

One simple way to check this is to see if `!isNaN(element.resource.id)`, as Coverr elements have `id="media/coverr:XXX"` and hotlinked videos don't have an id at all.

A more future-proof way would be to add a new flag to the resource object when adding external content (both from the third-party library and via hotlinking) and add a migration for this (setting the flag on old stories based on the above id check).

**Comment by swissspidy** [comment]
How would we solve this UX wise? Mark the trim/mute button as `aria-disabled` and add a tooltip saying "External videos can't be muted/trimmed"? Or hide completely?

Also, why the double pod assignment? That makes sprint planning a bit confusing. Seems like Jonny can cover this. Otherwise this would need to be split up into two tickets, one per pod.

Thanks for the implementation brief!

I think we could totally establish a new `isExternal` prop on resource objects, as you suggest. That could be set to `true` by `getResourceFromUrl()`. And for Coverr & other media, we can add a migration.

**Comment by spacedmonkey** [comment]
> I think we could totally establish a new isExternal prop on resource objects, as you suggest

We could also just check to see if the resource id is present ( not present in hotlinked resources ) and is a int ( is a string for coverr) videos. Similarly just a new attribute and migrated could be used.

**Comment by swissspidy** [comment]
Right, which is the easy approach Morten mentioned. But I'd prefer the more future proof approach with a new prop & a migration.

**Comment by csossi** [comment]
Verified in QA
![image](https://user-images.githubusercontent.com/16945664/133831609-b829bb6f-dfbf-42a9-9c8e-29dc35f175f2.png)
