### ISSUE TITLE
Right-click / Context Menu

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#97]
## Feature description

The right-click menu will enable easy operations without relying on remembering keyboard shortcuts or having to find some common actions in the design panel. A few actions that are difficult to find today and good candidates for the right-click menu include: 

**Right click on page elements**
- Copy, Paste, Delete
- Layer manipulation (Send to Back, Send Backward, Bring Forward, Bring to Front)
- Add link

**Right click on media element in foreground**
- Set as background
- Zoom/Crop

**Right click on page with no background**
- Copy would copy the background color

**Right click on page with background image**
- Copy would copy the background image to be pasted as background on another page 
- Detach image from background
- Zoom/Crop (equivalent to double-click)

Note: some of these may not make sense to include if included in the Quick Actions menu #5896

**Comment by jauyong** [comment]
UX and maybe brief needed. I don't see any references to a context menu over pages or blocks/elements.

**Comment by aaecheverria** [comment]
Hi @o-fernandez @choumx @bmattb  ,

I'm sharing the Figma file with the right click menu design and flows. We will have a hand-off session this week to go over this, but in the mean time feel free to add your comments/questions:

https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories---Post-Stable?node-id=4462%3A0

**Comment by dreamofabear** [comment]
@aaecheverria I think the basic actions (copy/paste/delete) and layer ordering sections look good and should be straightforward to implement.

The other actions don't seem to map to the feature description in the [original post](https://github.com/google/web-stories-wp/issues/97#issue-554065943) -- some actions in the UX spec are new, and some actions in the post seem to be missing from the spec (add link).

My personal 2c is that some of the new actions are not immediately intuitive or obviously high value e.g. copy/paste text style. The page actions (duplicate page, add new page) seem more appropriate for the quick actions menu.

**Comment by miina** [comment]
Is this a duplicate of the issues that @BrittanyIRL has created (epic here: https://github.com/google/web-stories-wp/issues/6139)?

**Comment by BrittanyIRL** [comment]
> Is this a duplicate of the issues that @BrittanyIRL has created (epic here: #6139)?

I think so!

**Comment by aaecheverria** [comment]
Hi @choumx 

Thanks for checking this out. We used the information in tickets 97 and 5896 as the baseline for proposing a holistic approach for Right click and Quick actions menu. So, in order to avoid having duplicated actions in both menus, you will notice that some of the “missing actions in this list are included in the Quick Actions Menu  (i.e. Add link).
The actions we included are based on a matrix we created with some key considerations that serves the MVP decision for both menus:
- Most common actions
- Recommended actions for story’s best practices
- Not repeating actions between Right Click Menu and Quick Actions Menu
 You can see the full list in this matrix we created for this task: https://docs.google.com/spreadsheets/d/1iOe7uEOytkUmBOq8xYiPGrQg-m0rBG9lJmUngAZ6WRQ/edit#gid=0

For the near future, our goal is to include these menus in our next user testing in order to validate some of the assumptions and iterate based on the user feedback.

**Comment by BrittanyIRL** [comment]
I'm closing this so we don't have duplicates for conversations as we start working on this next release cycle.
